### ISSUE TITLE
[Question] Manage two WinDivert handles

### ISSUE THREAD

**Issue by kelvinomolumo** [basil00/Divert#100]
Hello.
I want to manage two WinDivert handles. Is it possible? 
So i open two handles on different layers with WinDivertOpen (Forward Layer & Normal Layer).
Then use the WinDivertRecvEx on both handles with an overlapped structure. Now i wan to use WaitForMultipleObject for both handles.
Will this work? Is it the correct way to acheive this? If not can it be done another way? 

I don't know if i am making sense but if you need more clarification i would explain further

**Comment by basil00** [comment]
> Will this work? Is it the correct way to acheive this?

Yes this should work.
