### ISSUE TITLE
How Do I Modify Domain Responses?

### ISSUE THREAD

**Issue by volomike** [basil00/Divert#101]
Let's say I want to make an ad blocker on a web page that shows a message like "Ad Blocked By ___ Ad Blocker" when pulling an ad from some domain. I see that I can modify packets, but can this be done? And will it work even if the ad is pulled via https?

Or would it be better to intercept domain requests and reroute them to a mini web server in memory on an alternative port?

**Comment by TechnikEmpire** [comment]
This can't be done easily. You can take control of packets sure but that's where the library ends and your work begins. You need to handle one or more protocols above and beyond that, either http/s or DNS or both to accomplish this. If you just hijack dns and nxdomain stuff, web pages are going to have errors all over them.

**Comment by volomike** [comment]
That's what I thought. So what I need to do is make a browser extension, and see how the source code of Ad Block extension for Chrome works.

**Comment by volomike** [comment]
So here's a question. Can I use this driver to intercept x.com and HTTP redirect them to y.com? That way, I could show a message perhaps?

**Comment by TechnikEmpire** [comment]
@volomike I have an open source implementation url filtering via the adblock plus filter syntax [here](https://github.com/TechnikEmpire/DistillNET) but it's in C#. The CSS selector filter side of things is not complete, and the URL filter syntax is not 100% complete but it's more than sufficient to apply 99.99% of ABP filters to urls.

With regards to intercepting sure you can do that, it would be trivial to capture and synthesize plain HTTP requests and responses. Look at the [webfilter](https://github.com/basil00/Divert/tree/master/examples/webfilter) example in this same repo. The problem you're going to have is HTTP/S. That's not trivial, you'd need to MITM such requests and that's non-trivial.

**Comment by TechnikEmpire** [comment]
@volomike btw your website's certificate expired 3 days ago. I thought my filter was broken when I visited it :(

**Comment by TechnikEmpire** [comment]
@volomike If you have command line access to your server, [letsencrypt](https://letsencrypt.org/) is free.

Anyway sorry to get off topic. I dunno about DNS, you could capture DNS queries with WinDivert instead and just process them that. Unfortunately, tools in C/C++ land for managing DNS are few and far between and generally a pain. I'm not sure what languages you work in but there's a very nice, easy to use and [complete DNS library](http://arsofttoolsnet.codeplex.com/) in C#, I used to grab DNS with WinDivert and pass it to that lib and then spoof etc.

Whatever you do, just reply to every query at your fake server with HTTP `204 No Content`. That way your web pages won't show that they're broken apart.

**Comment by basil00** [comment]
As @TechnikEmpire hints, it is possible to do this kind of stuff, but WinDivert is rather low-level and only handles the network layer (raw IP packets).  All higher protocols (even including transport) must be correctly handled by your application, which can be non-trivial.  You should look at some of [TechnikEmpire's projects](https://github.com/TechnikEmpire) that use WinDivert for HTTP(S) interception and modification.
