### ISSUE TITLE
WinDivert1.4 Wishlist

### ISSUE THREAD

**Issue by basil00** [basil00/Divert#103]
Some API changes that are to be considered for WinDivert 1.4.  Other suggestions are welcome.

* The `WINDIVERT_ADDRESS` structure is updated to include a `Timestamp` field indicating when the packet was captured.  The filter language is extended to include a `timestamp` value.  The `Timestamp` field is ignored by `WinDivertSend`.
* The `WINDIVERT_ADDRESS` structure is updated to include a `Loopback` field indicating if the packet is loopback or not.  The filter language is extended to include a `loopback` value, making it easy to filter/ignore such traffic.
* Support a `WINDIVERT_FLAG_DEBUG` flag for `WinDivertOpen` that forces `WinDivertSend` to block until the packet injection result is known.  This is much slower, but provides better error messages if injection fails, so will be useful for debugging.
* Make WinDivert consider all loopback packets to be outbound only.  This is because (1) inbound injection of loopback packets is known to be problematic (see #17), and (2) outbound-only should be sufficient (currently the same loopback packet will captured twice anyway, once for outbound then once again for inbound, which seems redundant).

**Comment by TechnikEmpire** [comment]
Oh! Grabbing the PID associated with the packet. I think this was discussed a while ago. Not sure important because you can pretty efficiently track this for TCP using existing ip table fetching apis but IIRC there it something built in to WFP that provides it.

**Comment by TechnikEmpire** [comment]
My engine is about to have maintenance costs dropped to nil so maybe I can fork and provide that in a PR sometime in the future.

**Comment by basil00** [comment]
I think the correct way to implement that in WinDivert is to support the `FWPM_LAYER_ALE_FLOW_ESTABLISHED` layers.  However, this is a more major project requiring a generalization of the current API (so should also be rolled into layer-2 support, if we choose to do it), so will not be ready for version 1.4.

**Comment by TechnikEmpire** [comment]
True true, I was just being greedy. Lol as long as you call GetTcpTable and v6 variant whenever you detect SYN it's not expensive at all to accomplish this manually so I see no urgency in such a feature.

**Comment by basil00** [comment]
There is a kernel version of the IP helper API but it appears to be different than the user-mode version (e.g. I can't find `GetTcpTable`).  Either way, the IP helper functions generally require `IRQL<DISPATCH_LEVEL` which means a BSOD if you attempt to call it from `IRQL=DISPATCH_LEVEL` (from where the WinDivert filter is mostly invoked).  Finally, "not expensive" is relative.

**Comment by Areithus** [comment]
Getting the process id would indeed be great to have. It would make usage a lot easier for a lot of different projects out there. I know you can use some other functions but having it integrated would be great.

**Comment by basil00** [comment]
I don't think the IP helper idea will work, but I will look more into the `FWPM_LAYER_ALE_FLOW_ESTABLISHED` idea.  No promises however.

**Comment by basil00** [comment]
I do not think it is possible.  Although, we can get the process ID in the ALE layers, there is no direct method (that I know of) to forward this information down into the network layers where WinDivert operates.  It could be possible to do it manually, e.g. via a hash table mapping the network 5-tuple -> process ID, but that is too big of a change just for this release.

Besides, even if this is implemented, we still haven't solved the fundamental race condition between the packet and the PID.  (This is the apparently the reason why Microsoft do not support the process ID at the network layer in the first place).  In other words, by the time you get a packet via `WinDivertRecv`, the process which created the packet may no longer exist.  Or worse, the PID may be reassigned to an unrelated process.

**Comment by Areithus** [comment]
> Besides, even if this is implemented, we still haven't solved the fundamental race condition between the packet and the PID. (This is the apparently the reason why Microsoft do not support the process ID at the network layer in the first place). In other words, by the time you get a packet via WinDivertRecv, the process which created the packet may no longer exist. Or worse, the PID may be reassigned to an unrelated process.

I don't think that's a problem, for several reasons. Windows doesn't reuse PIDs that often (not in the time it gets sent around at least). Also, usually if you're interested in a specific process then you have at least one handle to the process. As long as *any* handle is still open in the process, the PID won't be recycled. It's also the PID at the time it's received. Even if it doesn't exist anymore, it wouldn't be invalid as such.

Regarding:
> I do not think it is possible. Although, we can get the process ID in the ALE layers, there is no direct method (that I know of) to forward this information down into the network layers where WinDivert operates. It could be possible to do it manually, e.g. via a hash table mapping the network 5-tuple -> process ID, but that is too big of a change just for this release.

I've been reading up on this, and I think it's possible with a callout at ALE.

>   1) get the processId member from the FWPS_INCOMING_METADATA_VALUES passed into the classifyFn.
>   2) Call FwpsFlowAssociateContext to associate the process ID with the flow (if you have no other data needed, you can simply pass the PID as the flowContext parameter.  It will then show up in the classifyFn parameters as the flowContext.

Hope you don't mind some comments about this, I'm just trying to help you a little with this :)

**Comment by basil00** [comment]
> I've been reading up on this, and I think it's possible with a callout at ALE.

I already tried this method but could not get it to work.  I could not find any information as to whether it even works for `FWPM_LAYER_OUTBOUND_IPPACKET`, which is where WinDivert operates.  In the quoted [post](https://social.msdn.microsoft.com/Forums/vstudio/en-US/8c923f6b-ce7d-4246-a919-2424d6e1991f/process-id-from-fwpmlayeroutboundippacketv4-layer), the Dusty's answer relates to `FWPM_LAYER_OUTBOUND_TRANSPORT`.

Note: in my prototype, I can see that the ALE classify function is called, and that the call to `FwpsFlowAssociateContext` returns `STATUS_SUCCESS`, but the flow context always remains `0`.

> Hope you don't mind some comments about this

Not at all.  I also want a PID feature.

**Comment by Areithus** [comment]
Great 👍 

Yes, but the thread is about the WPM_LAYER_OUTBOUND_IPPACKET layer (and LeoLiuQingJun also states that you should be able to implement it with flow context).
Did you also specify [FWP_CALLOUT_FLAG_CONDITIONAL_ON_FLOW](https://msdn.microsoft.com/en-us/library/ff551224(v=vs.85).aspx)? It looks as if that flag is required to get the classify to work, but I'm not sure if that's also required to get the flow context. 
[This](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/10c89f43-828b-4329-bd8a-e1289d5b1454/wfp-layer-and-filter-conditions-to-capture-all-packets?forum=wfp) also suggests that it's possible to use the callouts to send data between flows.

I think you might also be able to use the provider context, there's an example [here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/41843edc-0140-4b7a-ab1d-b2c4b335401e/sharing-data-in-wfp?forum=wfp#bf1071ab-5257-4d28-9ec5-493117144110).

**Comment by basil00** [comment]
It seems there was some confusion about this, even internally from Microsoft.  In [this thread](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/58a339ab-4fd3-46aa-8ccc-e4d1f6ab5a13/how-to-associate-packets-at-the-ippacket-layer-with-a-condition-on-the-aleauthrecvaccept-or) Dusty Harper initially said it was possible to get the flow context at the `IPPACKET` layers, but changes his mind later in the thread:

> After code review, apparently this is by design.  Flow contexts are not indicated at the IPPACKET Layers.

So looks like it is not possible.  The only way around this is to reimplement WinDivert to use the `TRANSPORT` layer instead, which is a major change.

@Areithus writes...
> I think you might also be able to use the provider context, there's an example here.

Getting data across the layers is not a problem, since both callouts share WinDivert's internal `context` structure.  The problem is tracking which PID belongs to which packet, which flow tracking is ideal for.  To do it manually, we'd need to implement some other mechanism, such as a hash table.

**Comment by Areithus** [comment]
Very interesting that link, didn't find that before. What an odd design decision then.

So you can send data across (some) layers but not from ALE to IP? 
If there's information readily available such as the packet hash it shouldn't be too difficult to add an hash table I think?

**Comment by basil00** [comment]
> If there's information readily available such as the packet hash it shouldn't be too difficult to add an hash table I think?

It is too much for the 1.4 release, but can consider it for 1.5.  For 1.5, it might make more sense to support other WFP layers directly.

**Comment by Areithus** [comment]
Fair enough @basil00. Looking forward to it and if I can help with this (such as research or testing), please leave a message. I'll be glad to help.

**Comment by basil00** [comment]
Sure, any reasonable solution will be considered.  As I mentioned, I also think this would be a useful feature.  But at the moment it does not look like there is an easy way of implementing it, short of WinDivert implementing its own flow tracking mechanism.

**Comment by ljani** [comment]
Please also consider including thread ids and more imporantly [service tags](http://www.alex-ionescu.com/?p=52) if possible.

Thanks for the wonderful project!

**Comment by sgeto** [comment]
would be nice if you could update the build system with the next release (just the VS and WDK stuff)

**Comment by basil00** [comment]
Are the MINGW builds compatible with VS?  If not, then I will revisit VS support.

I never use VS, so prefer not to support it if possible.  If I do support it, it should be in the form of a script that I can from the command line run that automatically builds everything, like the existing `msvs-build.bat`.

**Comment by sgeto** [comment]
> Are the MINGW builds compatible with VS?

Yes they are. It's just that it's bit outdated and that I find that it could offer a bit more flexibility.

For example starting in Windows Driver Kit (WDK) 8, MSBuild replaced the Windows Build Utility (Build.exe), so the command `build -cZg` in `wddk-build.bat` breaks/errors with newer SDK's.
If the wddk related files (dirs, sources, Makefile.inc etc.) could be converted to/replaced with VS project files, they could be used by anyone regardless of their SDK version.
And MSBuild.exe is a command line tool just like Build.exe so the full IDE won't be needed still.

I can hand in a PR if you're interested.

**Comment by basil00** [comment]
The main motivations for WDK7 is that it is (1) free, and (2) generates a `sys` files that are compatible with Windows 7 and up without coinstaller files.  If those requirements can be met by WDK 10, then there is no reason not to upgrade.

**Comment by basil00** [comment]
### Checksum changes

I am experimenting with some changes to the way checksums are handled by WinDivert.

Currently, it is assumed that the full TCP/UDP/IP checksums needs to be calculated before injection.  If NIC checksum offloading is enabled (which is usually is), the packets will have invalid checksums, meaning that the user application must calculate them.

However, offloaded packets have so-called "pseudo" checksums based on the *pseudo header* for TCP/UDP checksum calculations.  When offloading is enabled, it is sufficient to inject packets with merely the pseudo rather than full checksums.  Pseudo checksums are also much cheaper to calculate.

So to incorporate this into the WinDivert API I propose:

* New flags in `WINDIVERT_ADDRESS` that indicates whether the checksums are full or pseudo.  `WinDivertRecv` will set the flags based on the captured packet, and `WinDiverSend` will read the flags to determine what kind of checksums are used.
* `WinDivertHelperCalcChecksums` now takes an optional `WINDIVERT_ADDRESS` parameter, which will read the flags and calculate the full or pseudo checksums.
* The driver no longer zeroes checksum fields, and the `WINDIVERT_HELPER_NO_REPLACE` flag will be deprecated.

The main benefits of the new approach are:

* It is no longer necessary for the user mode application to call `WinDivertHelperCalcChecksums` for *unmodified* packets (like the pre-Windivert1.2 days).
* There is no checksum calculation for unmodified packets at all (user mode or kernel), saving CPU cycles.
* `WinDivertHelperCalcChecksums` may instead calculate pseudo checksums for *modified* packets if the NIC supports it (most do), again saving CPU cycles.

Although this saves some CPU usage, the benefit will be small since there is still the overheads of copying the packet to and from the driver, which is still the dominate cost.

**Comment by Areithus** [comment]
Do user mode applications need to do anything for this besides adding the extra parameter for `WinDivertHelperCalcChecksums`? It is unclear to me whether one has to check themselves whether a NIC supports offloading.

**Comment by basil00** [comment]
If the application is just modifying packets, there is no need to do anything other than preserve the address flags.  If the application is crafting packets from scratch, then the application can just calculate the full checksums.  Either way, it should not be necessary to check if the NIC supports offloading or not.

I might invert the flags, so `0` indicates the full checksum and `1` means pseudo checksum.  So zeroing the address reverts to the "sensible" default (full checksums).

**Comment by basil00** [comment]
### Impostor packets

There was some attempt to fix the driver infinite loop problem.  However the current solution is inadequate.  Specifically, (1) internally (re)injected packets can still loop, (2) the solution is currently incompatible with the checksums patch, and (3) the user application is not informed of the problem.

To fix these issues I am thinking of introducing a new "type" of packet, called an "impostor", that indicates that the packet was injected by another driver rather than originating from the network or TCP/IP stack.  The API changes include:

* A new filter condition `impostor` for impostor packets.  This allows user applications to ignore impostor traffic if they wish to (by filtering on `!impostor`).
* A new `WINDIVERT_ADDRESS` flag `Impostor` for impostor packets. 
* To prevent infinite loops, `WinDivertSend()` will decrement the TTL for impostor packets, and return `ERROR_HOST_UNREACHABLE` when the counter reaches zero.
* Also to prevent loops, internally re-injected impostor packets will also have their TTL decremented.  This includes packets captured in `SNIFF` mode.

Hopefully this will be the last main API change for version 1.4.

**Comment by Areithus** [comment]
> If the application is just modifying packets, there is no need to do anything other than preserve the address flags. If the application is crafting packets from scratch, then the application can just calculate the full checksums. Either way, it should not be necessary to check if the NIC supports offloading or not.
I might invert the flags, so 0 indicates the full checksum and 1 means pseudo checksum. So zeroing the address reverts to the "sensible" default (full checksums).

Thank you for the information. I think that makes more sense indeed. Does this also mean that it's no longer required to manually call the calculate checksum when creating a new packet OR modifying an existing packet?

**Comment by basil00** [comment]
No, it is still required.  Only unmodified packets do not require checksum (re)calculations.  That said, pseudo checksums are cheaper to calculate, so even modified packets will benefit (assuming NIC checksum offloading is enabled).

**Comment by Areithus** [comment]
Expected as much (made most sense to me), thank you very much 👍 
Have you decided whether you are going to invert the flags?

**Comment by basil00** [comment]
I've inverted the flags.  I think this is the more sensible default.

Most of the main 1.4 stuff is done I think.  I plan to work on a release, aiming for early December.

**Comment by madilsaeed** [comment]
Hi,
I am working with DNS based filtering. I am using WinDivert. First of all I must appreciate the work you have done. This is great. 

I am intercepting DNS resolving request, right now I am just dropping unwanted url requests. but I need to construct a response DNS packet (specifically need to modify answers session and I want to show a block page in the browser. I was able to show block page playing with TCP packets. But in TCP challenge was HTTPS traffic. ) and send it back to the browser. 

How I can do it using Windivert?

How I am trying to do it?
---------------------------
using filter "outbound and udp.DstPort == 53" to capture DNS resolve requests.
Drops packet if black listed, followed 'netfilter' example.

**Comment by TechnikEmpire** [comment]
@madilsaeed You shouldn't hijack bug & feature requests to ask your own personal "how to" question. If you want to show a block page, be in by DNS or HTTPS, you're still going to need HTTPS because you need to establish trust with the browser to show the page when you spoof a fake DNS response.

What you're asking is beyond the scope of anything here and is no small task. I have a [C# library](https://github.com/TechnikEmpire/CitadelCore.Windows) and an abandoned [C++ library](https://github.com/TechnikEmpire/HttpFilteringEngine) that do what you're after if you care to inspect the code there and see what's up. C/C++ this is just an extraordinarily complex endeavor. C# we lean heavily on libraries provided by Microsoft, hence why I've abandoned the C++ version for a portable C# version.

**Comment by TechnikEmpire** [comment]
@basil00 Not trying to self promote, sorry about that. Please feel free to mop up my recent posts here.

**Comment by madilsaeed** [comment]
@TechnikEmpire I will definitely look in to the suggested links.
thx.
and I didn't realized that I am starting a personal conversation in bug & feature session.

**Comment by basil00** [comment]
@madilsaeed, next time open a new issue for a new query, or post on stackoverflow (but email me the link otherwise it will get buried).  No point cleaning up these posts since better to have the question + answer on record somewhere.

Back on topic - so far the repository version passes all of my tests, so should release in a week or so.

**Comment by kelvinomolumo** [comment]
Please let there be an MSVC build for WinDivert v1.4. Thanks!!!

**Comment by stonedreamforest** [comment]
yes , support pid please

**Comment by basil00** [comment]
The WinDivert1.4 dev cycle is now closed.  It should be released as soon as the drivers are signed.

@stonedreamforest Unfortunately PID cannot be implemented for the reasons discussed earlier in the thread.

**Comment by basil00** [comment]
WinDivert 1.4.0-rc is now available [here](https://github.com/basil00/Divert/releases).

Notes:

* There are two variants (A and B) whose only difference is the digital signature.  Both variants are otherwise functionally equivalent.
* Version 1.4.0 is a backwards incompatible change (& the WinDivert project does not use semantic versioning yet).  In particular, the `WINDIVERT_ADDRESS` layout and `WinDivertHelperCalcChecksums` interface have changed, and it is also no longer necessary to recalculate checksums on unmodified packets (like WinDivert 1.0.X and 1.1.Y).

Otherwise, check the `CHANGELOG` for the new features and details.

**Comment by kelvinomolumo** [comment]
Still no MSVC build 😢...anyways thanks for the new release

**Comment by basil00** [comment]
Updating the MSVC build system will require some work, so was not ready for this release.
