### ISSUE TITLE
How to capture/modify/drop the package of a process?

### ISSUE THREAD

**Issue by huge818** [basil00/Divert#104]
I'm interested in a process packet.  not all of the package of interface.

if  there is a process  

> client.exe

,  How to capture/modify/drop the package of it?

How to determine  the packet come from which process?

**Comment by Areithus** [comment]
Please also check this: https://github.com/basil00/Divert/issues/103
Currently it's not possible in WinDivert to get the process.

**Comment by basil00** [comment]
As mentioned, it is currently not possible.  You can try to get the process ID via the IP helper API.
