### ISSUE TITLE
Example Compile issue

### ISSUE THREAD

**Issue by faanigee** [basil00/Divert#105]
Dear brother,
i m compiling netfilter project from example folder but it shows error 
![capture](https://user-images.githubusercontent.com/16011236/32491317-1230644c-c3d8-11e7-9d99-ea6c8fc2dc3f.PNG)
anyone can help me how to solve these issue...??
where i could find windows.h file
i think its main issue in this project

**Comment by faanigee** [comment]
Note i m using visual studio 2012 edition

**Comment by faanigee** [comment]
![image](https://user-images.githubusercontent.com/16011236/32497685-282dd3a8-c3ef-11e7-8820-247e90efe9bc.png)
here is visual c++ 6.0 compilation issues in windivert.h here windows.h is included but windivert.h show 102 errors and 6 warnings

**Comment by basil00** [comment]
Maybe someone with VS knowledge can answer this.  I never use VS so do not know.

**Comment by edlau2** [comment]
Without looking at the code, it seems like something is either not #define’d or #define’d incorrectly. ‘const’, ‘PVOID’, etc. should be defined if you include <windows.h>, doesn’t seem like they are, which leads to all sorts of subsequent compile errors.

**Comment by basil00** [comment]
Well, `windows.h` should be a standard include so I have no idea why it would be missing.  This is not a WinDivert issue, so closed.

**Comment by TechnikEmpire** [comment]
@faanigee why are you using vc 6? It's not 1999. You should download Visual Studio 2017 community edition it's full featured and free for independent devs and open source devs.

**Comment by TechnikEmpire** [comment]
100 percent this is because you're using a fossilized version of visual studio. You're missing basic windows headers, standard sdk stuff that will come with a modern version built for modern platforms.

**Comment by faanigee** [comment]
Going to give a try on visual studio 2015 professional edition :)
