### ISSUE TITLE
Blue-screen error with "fwpkcln.sys" driver on Windows 10

### ISSUE THREAD

**Issue by rajeshvr83** [basil00/Divert#106]
Hello,

We are facing Blue-screen error in newly installed Windows 10 machines. This issue is happens when we install Windivert driver and then try to connect to a network. Machine suddenly go for Blue-screen error when we connect to a network. When we analyze the memory dump file then found that the crashing module is "fwpkcln.sys" driver (WFP Kernel Client). Kindly give some suggestions to solve this issue.

![capture1](https://user-images.githubusercontent.com/25902753/32547533-be67655a-c4a8-11e7-8fd0-41e044e797e8.JPG)
![capture2](https://user-images.githubusercontent.com/25902753/32547538-bff8ebd2-c4a8-11e7-9752-4fad1439646d.JPG)
![wfp](https://user-images.githubusercontent.com/25902753/32547545-c6371b5e-c4a8-11e7-9578-4178e2bd99f9.png)

Regards,
Rajesh

**Comment by basil00** [comment]
Which version of WinDivert?  It appears to be the same issue as #90, in which case you need to upgrade to WinDivert version 1.3.0.

**Comment by basil00** [comment]
I assume this error was fixed.
