### ISSUE TITLE
Inject only  - filter string = "false"

### ISSUE THREAD

**Issue by thalomatt** [basil00/Divert#107]
I get an invalid handle when I attempt an     _handle = WinDivertOpen("false", WINDIVERT_LAYER_NETWORK, 0, 0); -- 
The docs say this is an ideal "inject only" filter.  The call to GetLastError sent back 3081390800 -- seemingly garbage.

**Comment by basil00** [comment]
I was not able to reproduce the problem.  Which version of WinDivert?

**Comment by thalomatt** [comment]
1.3  using google test (as well as in my code)  - a filter with only "true" works as expected, but "false" fails each time.

    auto _handle = WinDivertOpen("false", WINDIVERT_LAYER_NETWORK, 0, 0);
   EXPECT_NE(_handle, INVALID_HANDLE_VALUE);  (fails)
;//

    auto _handle = WinDivertOpen("true", WINDIVERT_LAYER_NETWORK, 0, 0);
   EXPECT_NE(_handle, INVALID_HANDLE_VALUE);  (passes)

**Comment by basil00** [comment]
I still cannot reproduce, even with 1.3.0.  Which operating system, and is it 32bit or 64bit WinDivert?

**Comment by thalomatt** [comment]
I apologize, I thought I had already replied to this.  64 bit Windows 10 with the fall update.  I ended up using a filter that should catch no packets ("tcp and udp").   I do however experience the occasional issue when using the WinDivertSend  with error 1233. "ERROR_PROTOCOL_UNREACHABLE" which has the description: The network location cannot be reached.  I'm not sure if it's tied to this new "send only filter" or not.  I'm trying to get logs to sort that out -it happens very rarely.

**Comment by basil00** [comment]
I also tried with Windows 10 a few days ago but also failed to reproduce the problem, so very strange.  I'll try again with different versions later.

As for the 1233 error, based on the description, I are you sure it is just not the network temporarily dropping out?

**Comment by thalomatt** [comment]
figured out thr 1233 issue just a few hours ago.  they were multicast
packets

**Comment by basil00** [comment]
Interesting, I may need to document that behavior.

**Comment by basil00** [comment]
I finally was able to observe this bug, so could track it down quickly.  Fixed.
