### ISSUE TITLE
error: failed to open the WinDivert device (1753)

### ISSUE THREAD

**Issue by nmweizi** [basil00/Divert#108]
D:\WinDivert-1.3.0-WDDK\amd64>netdump.exe true 999
error: failed to open the WinDivert device (1753)

windows 10  64bit 1703
windivert 1.12-1.3.0

**Comment by basil00** [comment]
Error 1753 is `EPT_S_NOT_REGISTERED`: *There are no more endpoints available from the endpoint mapper.*

I am not sure what that means.
I also cannot reproduce the problem.  Does it work after reboot?

**Comment by nmweizi** [comment]
thanks。
after reboot，it dont work！

**Comment by basil00** [comment]
WinDivert does not return that error code directly, which means the error occurs in a library or service that is used by WinDivert (e.g., driver installation, or WFP transactions, etc.).  After googling, it seems this is something to do with the RPC configuration on your computer, and there are some online guides regarding how to fix the problem.  Other than that, I do not know the underlying cause of the problem nor can I offer any solutions.

**Comment by nmweizi** [comment]
it is work.
https://github.com/jagt/clumsy/issues/24

**Comment by basil00** [comment]
Thanks for tracking that down, I have [updated the documentation](https://github.com/basil00/Divert/commit/af5cd698837a679c85198de678be28f7225538aa).
