### ISSUE TITLE
Where there is an Ethernet hijacking project？

### ISSUE THREAD

**Issue by huge818** [basil00/Divert#109]
Divert is a greate project! I like it!
but,
Where there is an Ethernet hijacking project？

It is similar the Divert proejct?

I hope hijacking some protocol  not justthe  IP protocol.

who can help me?  Recommend a good project？

**Comment by basil00** [comment]
There is `winpkfilter` which can do Ethernet filtering.  However, this project is commercial so be prepared to pay for a license.

Note also that you can reconstruct the Ethernet headers with WinDivert and the IP helper API.  The `IfIdx` field can be mapped to the Ethernet address.
