### ISSUE TITLE
WINDIVERT_TCPHDR definition different to RFC793

### ISSUE THREAD

**Issue by GreatFireWall** [basil00/Divert#112]
Node that the ```Reserved1``` and ```HdrLength``` in WINDIVERT_TCPHDR is reversed.

WINDIVERT_TCPHDR:
![image](https://user-images.githubusercontent.com/4510984/34552309-9b82883c-f15b-11e7-828f-7a4f6f44f34f.png)

RFC793 (https://tools.ietf.org/html/rfc793#page-15):
![image](https://user-images.githubusercontent.com/4510984/34552253-613d98ec-f15b-11e7-8725-6bc7cfb7c97e.png)

**Comment by ffalcinelli** [comment]
I think it's right cause you should consider the network byte order

**Comment by GreatFireWall** [comment]
@ffalcinelli 
But I saw the source of ```WinDivertHelperParsePacket``` in https://github.com/basil00/Divert/blob/master/dll/windivert_helper.c#L250:13, there isn't any netword order reversing operation for other fields like ```SrcPort```, ```DstPort```, etc...

Another evidence is in the source code of "Divert.Net"(a WinDivert C# Wrapper), it do ByteSwap operation before return:
```
uint16_t TCPHeader::SourcePort::get()
{
	if (m_tcpHeader != nullptr)
	{
				
		return ByteSwap(m_tcpHeader->SrcPort);
	}

	return 0;
}
```
ref: https://github.com/TechnikEmpire/Divert.Net/blob/master/src/DivertTCPHeader.cpp#L74

So that means WinDivert **do not** tranfer the network order to host order.

**Comment by GreatFireWall** [comment]
emm, I have seen a few knowledge of "Bit field", I think it's my misunderstanding.

**Comment by basil00** [comment]
Bit fields fill the LSB first (at least for the target compilers), which can be a bit counterintuitive. The definitions should be correct otherwise the WinDivert test suite will fail.

**Comment by GreatFireWall** [comment]
well, thanks your guide.
