### ISSUE TITLE
Is there any other way to redirect all tcp traffic to local proxy ?

### ISSUE THREAD

**Issue by GreatFireWall** [basil00/Divert#114]
The example "streamdump" is too complex and low flexibility.

**Comment by TechnikEmpire** [comment]
@GreatFireWall https://github.com/TechnikEmpire/HttpFilteringEngine/blob/master/src/te/httpengine/mitm/diversion/impl/win/WinDiverter.cpp

**Comment by TechnikEmpire** [comment]
Also see https://github.com/TechnikEmpire/CitadelCore and https://github.com/TechnikEmpire/CitadelCore.Windows

The only thing missing is port independent protocol mapping but if you feel like a fun exercise you can modify the ndpi library to play nice with WinDivert.

https://github.com/ntop/nDPI

**Comment by GreatFireWall** [comment]
thanks.

**Comment by basil00** [comment]
The `streamdump` sample is a bit more complicated than it needs to be because it uses overlapped I/O.

I assume this issue is resolved?
