### ISSUE TITLE
Duplicate packets on FORWARD LAYER WIN10

### ISSUE THREAD

**Issue by kelvinomolumo** [basil00/Divert#116]
On windows 10 i have been seeing packet being duplicated when ICS is enabled. 
WinDivertOpen filter used is “tcp or udp“ on WINDIVERT_LAYER_FORWARD with priority -1000
1st packet looks like this:
192.168.137.1:54321 ——> external IP (website):80
Then the 2nd packet looks the same but now it looks like coming from the main NIC:
192.168.1.2:54321 ——-> external IP (website):80

What could be causing this? Right now I whitelist the duplicate

**Comment by kelvinomolumo** [comment]
Ok. I meant « tcp or udp ». Sorry my bad. I will soon post a minimal code to reproduce the problem.

**Comment by basil00** [comment]
I assume this issue was resolved?
