### ISSUE TITLE
Windivert's documentation as CHM and/or PDF

### ISSUE THREAD

**Issue by sgeto** [basil00/Divert#119]
This is more of an request than an issue.
May I ask how you generate Windivert's HTML documentation? With doxygen, from XML or something else? 
If so, can we have a copy of that raw sheet/config file/markdown file/etc? I would like to create a chm and PDF version of it.

Thanks.

**Comment by basil00** [comment]
The documentation is written in HTML directly, so if you want PDF or something else you need to convert it yourself.
