### ISSUE TITLE
[Feature Request] static windivert

### ISSUE THREAD

**Issue by sgeto** [basil00/Divert#121]
In include/windivert.h, if you were to change

```
#ifndef WINDIVERTEXPORT
#define WINDIVERTEXPORT     __declspec(dllimport)
#endif      /* WINDIVERTEXPORT */
```

to

```
#ifndef WINDIVERTEXPORT
#define WINDIVERTEXPORT     __declspec(dllimport)
#else
#define WINDIVERTEXPORT
#endif      /* WINDIVERTEXPORT */
```

Then simply adding `-DWINDIVERTEXPORTS` to one's compile flags should do the trick.

This, however, introduces two "problem":

1. There would always be this harmless but annoying redefinition warning since `WINDIVERTEXPORTS` is being defined twice (on the command line and in windivert.h)

2. `WINDIVERTEXPORTS` isn't a very suitable name to instruct static linkage. It would probably be much clearer to define something like `WINDIVERTSTATIC` instead:

```
#ifdef WINDIVERTSTATIC
#define WINDIVERTEXPORT
#else
#define WINDIVERTEXPORT     __declspec(dllimport)
#endif      /* WINDIVERTSTATIC */
```

I also inverted the order to make this change more backward compatible (having to explicitly define static will break builds).

But it doesn't have to stop there:
Windivert currently uses a def file for exports, and `WINDIVERTEXPORT`  resolves to `__declspec(dllimport) ` which is kind of weird. Also, the speed/performance of the DLL can be increased by dropping the def file in favor of __declspec(dllexport)  for which the `WINDIVERTEXPORT` macro can then be used:

```
#ifdef WINDIVERTSTATIC
/* windivert is being built or linked statically */
#define WINDIVERTAPI
#elif WINDIVERTEXPORT
/* windivert is being built dynamically */
#define WINDIVERTAPI  __declspec(dllexport
#else
/* windivert is being linked dynamically */
#define WINDIVERTAPI     __declspec(dllimport)
#endif      /* WINDIVERTAPI */
```

And then also rename all instances of `WINDIVERTEXPORT` to `WINDIVERTAPI`

**Comment by basil00** [comment]
I am not sure why adding the `-DWINDIVERTEXPORT` compiler flag would not already work?  Then the macro would not be redefined and will already resolve to the empty string.

**Comment by sgeto** [comment]
Not really. Defining `-DWINDIVERTEXPORT` currently means not resolving the macro at all.

**Comment by sgeto** [comment]
The steps to reproduce:
```
cl -DWINDIVERT_DEBUG -Iinclude /DWIN32 /D_WINDOWS /W3 /MDd /Zi /Ob0 /Od /RTC1 /Fodll\windivert.c.obj /Fddll\libWinDivert.pdb /FS -c dll\windivert.c

link.exe /lib  /machine:x64 /out:dll\libWinDivert.lib dll\windivert.c.obj

cl -DWINDIVERT_DEBUG -Iinclude /DWIN32 /D_WINDOWS /W3 /MDd /Zi /Ob0 /Od /RTC1 -DWINDIVERTEXPORT /Foexamples\netdump\netdump.c.obj /Fdexamples\ /FS -c examples\netdump\netdump.c
```
I just noticed that `-DWINDIVERTEXPORT=` (with an equal sign) is what my compiler is expecting to resolve `WINDIVERTEXPORT` to an empty string.

**Comment by basil00** [comment]
That should work for the time being -- although not the most elegant solution.  Maybe I revisit this for the next release.

**Comment by sgeto** [comment]
Can you confirm static linkage on MinGW?

**Comment by basil00** [comment]
It's not officially supported, so it is up to you to get it working.

**Comment by sgeto** [comment]
I can confirm that on MinGW, a similar flag (`-DWINDIVERTEXPORT=""`) is needed

**Comment by boris9000** [comment]
Just for reference, on MSVC it would be `/DWINDIVERTEXPORT=`

**Comment by basil00** [comment]
I've used static linking for the WinDivertTool project and it seems to work fine.  So time for this to close.
