### ISSUE TITLE
Compiling with "webfilter.c" in VC++ causes unknown symbol errors

### ISSUE THREAD

**Issue by mrteenageparker** [basil00/Divert#122]
I am trying to compile the sample "webfilter.c" example in a C++ project, and have done all nessessary customizations in order for the file to correctly work in VC++, however when compiling the following errors occur:
![image](https://user-images.githubusercontent.com/2037716/36469305-a751ebc0-169b-11e8-88d2-265f8b822c1d.png)

I have linked the .lib file and placed the DLL in the executable directory and followed all needed steps in order for the linking to work, however I am met with these errors.

If possible please guide me in the right direction, am I missing something possibly?

I wasn't sure whether or not to email about this issue, so my apologies if this is the incorrect place to post it.

**Comment by basil00** [comment]
It is OK to post this issue here.  However, I never use VC++ so not sure what the problem would be (I'm guessing some dependency configuration not set up correctly?).  But perhaps someone else will know.

**Comment by TechnikEmpire** [comment]
This is a linkage error, where something can't find the `.lib` files for `WinDivert.dll`. Check your additional library paths under project settings.

**Comment by edlau2** [comment]
Another thing to look at is how you are compiling - are the unrecognized imports being listed with mangled names, perhaps? Something along the lines of “SomeFunction@<bunch of extra stuff here>”. You may be compiling as C++ and the library is exporting as C, you can see the exported functions by typing “dump bin /exports WinDivert.lib” (or .dll) at a command prompt. You can declare the #include definitions as extern “C” and/or compile as “C” rather than C++, if that’s the issue.

I don’t happen to have the library in front of me to look at or the exact link error you’re seeing, so this is just a guess.

Ed

**Comment by sgeto** [comment]
There should be a file called webfilter.log (or-whatever-your-project-is-called.log) in you intermediate directory. Post it here.

**Comment by mrteenageparker** [comment]
(censored names due to privacy concerns):

  Wrapper.cpp
c:\users\username\documents\visual studio 2017\projects\wrapper\wrapper\applicationsettings.h(36): warning C4200: nonstandard extension used: zero-sized array in struct/union
  c:\users\username\documents\visual studio 2017\projects\wrapper\wrapper\applicationsettings.h(36): note: This member will be ignored by a defaulted constructor or copy/move assignment operator
c:\users\username\documents\visual studio 2017\projects\wrapper\wrapper\applicationsettings.h(112): warning C4101: 'i': unreferenced local variable
c:\users\username\documents\visual studio 2017\projects\wrapper\wrapper\wrapper.cpp(142): warning C4715: 'genRSA': not all control paths return a value
Wrapper.obj : error LNK2019: unresolved external symbol __imp__WinDivertOpen referenced in function "public: void __thiscall ApplicationSettings::InstallProvider(void)" (?InstallProvider@ApplicationSettings@@QAEXXZ)
Wrapper.obj : error LNK2019: unresolved external symbol __imp__WinDivertRecv referenced in function "public: void __thiscall ApplicationSettings::InstallProvider(void)" (?InstallProvider@ApplicationSettings@@QAEXXZ)
Wrapper.obj : error LNK2019: unresolved external symbol __imp__WinDivertSend referenced in function "public: void __thiscall ApplicationSettings::InstallProvider(void)" (?InstallProvider@ApplicationSettings@@QAEXXZ)
Wrapper.obj : error LNK2019: unresolved external symbol __imp__WinDivertHelperParsePacket referenced in function "public: void __thiscall ApplicationSettings::InstallProvider(void)" (?InstallProvider@ApplicationSettings@@QAEXXZ)
Wrapper.obj : error LNK2019: unresolved external symbol __imp__WinDivertHelperCalcChecksums referenced in function "public: void __thiscall ApplicationSettings::InstallProvider(void)" (?InstallProvider@ApplicationSettings@@QAEXXZ)
C:\Users\username\Documents\Visual Studio 2017\Projects\Wrapper\Debug\Wrapper.exe : fatal error LNK1120: 5 unresolved externals

**Comment by sgeto** [comment]
is that all? lol I thought it would be longer 😄 

I am after the linker command-line. Can you run plain msbuild.exe on the project file from a VS developer command prompt and post the output here?

**Comment by mrteenageparker** [comment]
It keeps trying to build it in x64 which is causing tons of errors since the project strictly requires x86, is it possible to make it build x86?

**Comment by sgeto** [comment]
```
msbuild /nologo /maxcpucount /verbosity:quiet /consoleloggerparameters:ErrorsOnly;NoItemAndPropertyList;NoSummary;Verbosity=minimal /fileLogger /fileloggerparameters:Append;NoItemAndPropertyList;NoSummary;Verbosity=normal;Encoding=UTF-8 /target:"Rebuild" /property:platform=x86;Configuration="Debug" **your-project-file-here** & if not %errorlevel% == 0 type msbuild.log
```

**Comment by sgeto** [comment]
1. The issue says "webfilter.c". What's up with that?
2. Looks like "Wrapper" is a cmake project. Are you the author
3. Whatever the case, the problem doesn't seem to be MSVC. Rebuilding Windivert may help. You should get rid of the old Windivert stuff first. Are you building from master?

**Comment by mrteenageparker** [comment]
1. I said that to allow people to know which code I am working with in case that should arise. I customized the sample to adapt to the needs for the project
2. Wrapper is entirely made by me, and I am not familiar with CMake at all - I just started an empty C++ project and went from there.
3. I didn't build it myself, I got it from the releases for the project - I am not financially capable at the moment to sign a driver and submit it to Microsoft for review.

Hopefully this clears up a few things - sorry for being confusing at the start.

**Comment by sgeto** [comment]
Forget my cmake comment. I guess I misread your build log.

You would only need to sign the driver, not the userland stuff. So if you can, you should build Windivert form the tip of the master branch. and use to resulting import library and DLL + the sign 1.4-RC kernel module from the release page to power your app.
If the problem isn't resolved by then, then there may be something wrong code-wise. See also @edlau2 comment.

**Comment by mrteenageparker** [comment]
It seems like building it from source fixed the issue - I will close this issue and confirm it soon.

Thank you for all your help. I'd suggest using a newer version of visual studio - preferably 2015 or higher which might prevent this sort of issue.

**Comment by mrteenageparker** [comment]
Yep it worked - opening the .vcxproj in the dll directory then building it that way worked.

Closing the issue - thank you. Probably should update the documentation to reflect this maybe?
