### ISSUE TITLE
Changing Destination IP address in the received packet and resend the packet

### ISSUE THREAD

**Issue by Muruganalagesan** [basil00/Divert#123]
Hi admin,
Following is the scenario I am trying to do.
	

- I have two machines one is an application machine (IP: 192.168.0.17)  and other DB machine (IP: 192.168.0.173) (1433 port) (Both are windows 2012).
- I have configured the application with correct db machine IP,it works(normal) 
- Now i have configured invalid DB machine IP (IP: 192.168.0.177) with the application(application wont work).

Under these assumptions I am trying to change the incorrect IP of the destination machine Using Driver.net and WinDivert.dll

Able to do the following
	
Created a sample application( based on Windivert sample from @basil00 ) to receive the packets destined for the remote machine and I was able to change the incorrect IP with Correct IP?
	
How I can send the modified packet to the network, so the appliation works as expected?
 Any helps how i can acheive this?

MyCode: 

  class Program
    {
        static void Main(string[] args)
        {

            bool running = true;

            Console.CancelKeyPress += delegate
            {
                running = false;
            };

            Diversion diversion;

            Diversion diversionforward;

            String filter = "outbound && tcp.DstPort == 1433";

            try
            {
                diversion = Diversion.Open(filter, DivertLayer.Network, -1000, 0);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return;
            }

            if (!diversion.Handle.Valid)
            {
                Console.WriteLine("Failed to open divert handle with error {0}", System.Runtime.InteropServices.Marshal.GetLastWin32Error());
                return;
            }

            IPHeader ipHeader = new IPHeader();
            IPv6Header ipv6Header = new IPv6Header();
            ICMPHeader icmpHeader = new ICMPHeader();
            ICMPv6Header icmpv6Header = new ICMPv6Header();
            TCPHeader tcpHeader = new TCPHeader();
            UDPHeader udpHeader = new UDPHeader();

            Address address = new Address();

            byte[] buffer = new byte[65535];

            uint receiveLength = 0;
            uint sendLength = 0;

            string processName;

            uint pid = 0;

            while (running)
            {
                pid = 0;

                receiveLength = 0;
                sendLength = 0;

                if (!diversion.Receive(buffer, address, ref receiveLength))
                {
                    Console.WriteLine("Failed to receive packet with error {0}", System.Runtime.InteropServices.Marshal.GetLastWin32Error());
                    continue;
                }

                diversion.ParsePacket(buffer, receiveLength, ipHeader, ipv6Header, icmpHeader, icmpv6Header, tcpHeader, udpHeader);

                if (ipHeader.Valid && tcpHeader.Valid)
                {
                    Diversion.GetPacketProcess(address, tcpHeader, ipHeader, ref pid, out processName);

                    // FILTERING AREA STARTS*************************

                    if (ipHeader.DestinationAddress.ToString().Contains("192.168.0.177"))
                    {
                        diversionforward = Diversion.Open(filter, DivertLayer.NetworkForward, 0, 0);

                        if (tcpHeader.DestinationPort == 1433)
                        {
                            ipHeader.DestinationAddress = IPAddress.Parse("192.168.0.173"); //Ip of the local machine

                            if (address.Direction == DivertDirection.Outbound)
                            {
                                diversionforward.CalculateChecksums(buffer, receiveLength, 0);
                            }

                            diversionforward.SendAsync(buffer, receiveLength, address, ref sendLength);

                            diversionforward.Close();
                            continue;
                        }

                    }
                    // FILTERING AREA ENDS*************************

                    if (address.Direction == DivertDirection.Outbound)
                    {
                        diversion.CalculateChecksums(buffer, receiveLength, 0);
                    }

                    diversion.SendAsync(buffer, receiveLength, address, ref sendLength);
                }

                diversion.Close();
            }

        }
    }

[ConsoleApp1.zip](https://github.com/basil00/Divert/files/1751314/ConsoleApp1.zip)

Any help for the same ? or any ideas to acheive it?****

**Comment by basil00** [comment]
Are you also changing the address for the packets on the reverse (inbound) path?  If you do not do this, then the inbound TCP packets will have the wrong source address and be rejected.

You are using some WinDivert wrapper which is not directly supported here.

**Comment by TechnikEmpire** [comment]
I might just blow away divert.net and leave the pinvoke project. @Muruganalagesan please don't open tickets for the driver author with stuff from my repo (I saw you double post back to back). I'm closing the issue on my repo.

**Comment by basil00** [comment]
I assume this has been resolved.
