### ISSUE TITLE
[C#] need help，WinDivertHelperCalcChecksums  Not modify of packet check bits and length bits

### ISSUE THREAD

**Issue by boyyao** [basil00/Divert#124]
code like：
IntPtr handle = WinDivertMethods.WinDivertOpen(Filter, WINDIVERT_LAYER.WINDIVERT_LAYER_NETWORK, -1, 0);
byte[] buffer = new byte[MAXBUF];
while (true)
{
Array.Clear(buffer, 0, buffer.Length)；
if (WinDivertMethods.WinDivertRecv(handle, buffer, MAXBUF, ref windivert_ADDRESS, ref packetLen))
{
fixed (byte* buffer_fixed = buffer)
{
WinDivertMethods.WinDivertHelperParsePacket(buffer_fixed, packetLen, &IPHDR, null, null, null, &TCPHDR, null, &ppData, null);
..........some code...
string data = Marshal.PtrToStringAnsi((IntPtr)((void*)ppData));
if(date.contains("need Modify data"))
{
byte[] newbody = System.Text.Encoding.ASCII.GetBytes("i'm is new data");
//use new data modify raw data ，，40byte is tcp/ip head
Buffer.BlockCopy(newbody, 0, buffer, 40, newbody.Length);

//redefinition packetLen to newdata + 40byte head
packetLen = (uint)newbody.Length + 40;

}
}
}
//....invalid....... buffer not modify  ?????????????????
WinDivertMethods.WinDivertHelperCalcChecksums(buffer, packetLen, 0UL);

}

wait for your help thx......

**Comment by TechnikEmpire** [comment]
Where are you getting C# code from? Another repo? Or did you write it?

**Comment by boyyao** [comment]
thx for reply...
i use https://github.com/TechnikEmpire/DivertPInvoke for  windivert in C#

**Comment by boyyao** [comment]
post full code:`public static string Filter = "outbound && tcp && tcp.DstPort == 8888 && tcp.PayloadLength > 120";
        public unsafe static void RunDiversion()
        {
            IntPtr handle = WinDivertMethods.WinDivertOpen(Filter, WINDIVERT_LAYER.WINDIVERT_LAYER_NETWORK, -1, 0);
            IntPtr INVALID_HANDLE_VALUE = new IntPtr(-1);
            if (handle == INVALID_HANDLE_VALUE)
                Console.WriteLine("open error:" + Marshal.GetLastWin32Error());

            const uint MAXBUF = 0xFFFF;
            byte[] buffer = new byte[MAXBUF];

            while (true)
            {
                Array.Clear(buffer, 0, buffer.Length);
                WINDIVERT_ADDRESS windivert_ADDRESS = default(WINDIVERT_ADDRESS);
                uint packetLen = 0u;

                if (WinDivertMethods.WinDivertRecv(handle, buffer, MAXBUF, ref windivert_ADDRESS, ref packetLen))
                {
                    fixed (byte* buffer_fixed = buffer)
                    {
                        WINDIVERT_IPHDR* IPHDR = null;
                        WINDIVERT_TCPHDR* TCPHDR = null;
                        byte* ppData = null;
                        WinDivertMethods.WinDivertHelperParsePacket(buffer_fixed, packetLen, &IPHDR, null, null, null, &TCPHDR, null, &ppData, null);
                        if (IPHDR != null && TCPHDR != null && ppData != null)
                        {
                            string data = Marshal.PtrToStringAnsi((IntPtr)((void*)ppData));

                            if (data.Contains("need modify data"))
                            {
                                Console.WriteLine("old data:");
                                for (int i = 0; i < packetLen; i++)
                                {
                                    Console.Write("{0:X2}", buffer[i]);
                                }
                                Console.WriteLine("");

                                byte[] newbody = System.Text.Encoding.ASCII.GetBytes("new data");

                                Buffer.BlockCopy(newbody, 0, buffer, 40, newbody.Length);
                                packetLen = (uint)newbody.Length + 40;

                                Console.WriteLine("new data:");
                                for (int i = 0; i < packetLen; i++)
                                {
                                    Console.Write("{0:X2}", buffer[i]);
                                }
                                Console.WriteLine("");
                            }
                        }
                    }

                    WinDivertMethods.WinDivertHelperCalcChecksums(buffer, packetLen, 0UL);
                    Console.WriteLine("send data:");
                    for (int i = 0; i < packetLen; i++)
                    {
                        Console.Write("{0:X2}", buffer[i]);
                    }
                    Console.WriteLine("");
                    WinDivertMethods.WinDivertSendEx(handle, buffer, packetLen, 0UL, ref windivert_ADDRESS, IntPtr.Zero, IntPtr.Zero);
                }
            }

        }`

**Comment by TechnikEmpire** [comment]
@boyyao Then open tickets on that repo. As you can plainly, easily see, the diver pivoke project is not created/run/maintained by the same person as WinDivert itself. You're cross posting and bugging people who can't even help you.

**Comment by boyyao** [comment]
I'm very sorry, because I'm in a hurry. And think there are more people here.

**Comment by TechnikEmpire** [comment]
Sure but they're following a C repository not a c# one and most of them have never heard of my wrappers anyway.

**Comment by boyyao** [comment]
Your wrappers is very good. It's very suitable for a novice like me. Thank you for your Class. I tried Divert.Net before, but x86 compiled the error.

**Comment by basil00** [comment]
This issue is handled here: https://github.com/TechnikEmpire/DivertPInvoke/issues/5

In general, issues posted here should only relate to the core WinDivert driver and libraries.  If you are using a wrapper, then please report the issue to the wrapper's maintainer.
