### ISSUE TITLE
Send captured tcp/ip packet twice

### ISSUE THREAD

**Issue by RaynV** [basil00/Divert#126]
```
    HANDLE handle;
    WINDIVERT_ADDRESS addr;
    char packet[MAXBUF];
    UINT packetLen;

    handle = WinDivertOpen("tcp.DstPort == 1250, WINDIVERT_LAYER_NETWORK, 0, 0);
    if (handle == INVALID_HANDLE_VALUE)
    {
        exit(1);
    }

    while (TRUE)
    {
        if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
        {
            continue;
        }

        WinDivertHelperCalcChecksums(packet, packetLen, &addr, 0);
        if (addr.Direction == 0)
        {
           WinDivertSend(handle, packet, packetLen, &addr, NULL);
        }
        if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
        {
            // Handle send error
            continue;
        }
    }
```
Im trying to double outgoing packet. why isn't this working ?

**Comment by basil00** [comment]
Replace `"..."` with `"outbound"` in `WinDivertOpen`?

**Comment by RaynV** [comment]
i forgot to edit that. 
But still it doesn't seem to send the packet twice. I think it has something to do with ack packet.

**Comment by basil00** [comment]
OK.  But what exactly do you mean by "not working"?  Do you mean that the duplicated packet is not visible locally (e.g., netdump.exe or wireshark), or at the destination?

**Comment by RaynV** [comment]
i tried it on chat application. it only send the message once. i can't use wireshark because the application protected. it can't run while wireshark or other sniff program detected.

**Comment by basil00** [comment]
The TCP protocol automatically ignores duplicate packets, so the chat application will not be affected.  To duplicate messages at the application layer, you'd need to intercept the TCP stream, then parse and duplicate the messages from the stream.  This assumes the stream is not encrypted.  It might be possible as a modification of `streamdump`, but is a lot more complicated.
