### ISSUE TITLE
Can't detect drive, but my driver is with the application

### ISSUE THREAD

**Issue by Szj-kagami** [basil00/Divert#127]

**Comment by basil00** [comment]
What happens if you try to run one of the WinDivert sample applications?

**Comment by basil00** [comment]
Specifically, what error does it print?

**Comment by Szj-kagami** [comment]
failed to open the WinDivert device     I'm sure the driver is already in the application file



szj_kagami@Rayvision.com
 
From: basil00
Date: 2018-04-20 10:25
To: basil00/Divert
CC: Szj-kagami; Author
Subject: Re: [basil00/Divert] Can't detect drive, but my driver is with the application (#127)
Specifically, what error does it print?
―

**Comment by basil00** [comment]
The error should be something like `failed to open WinDivert device (N)` where `N` is some number.  What is the number?

**Comment by Szj-kagami** [comment]
number is 2  And one more thing is that I can start the driver WinDivert64.sys, and the weird thing is after i start the driver WinDivert64.sys   the driver WinDivert32.sys
were started



szj_kagami@Rayvision.com
 
From: basil00
Date: 2018-04-20 10:41
To: basil00/Divert
CC: Szj-kagami; Author
Subject: Re: [basil00/Divert] Can't detect drive, but my driver is with the application (#127)
The error should be something like failed to open WinDivert device (N) where N is some number. What is the number?

**Comment by basil00** [comment]
For 32bit applications you need *both* the `WinDivert32.sys` and `WinDivert64.sys` files in the application directory.  Otherwise, if you try to run the application on 64-bit Windows, you will get a file-not-found error.

**Comment by Szj-kagami** [comment]
thanks for your answer



szj_kagami@Rayvision.com
 
From: basil00
Date: 2018-04-20 10:59
To: basil00/Divert
CC: Szj-kagami; Author
Subject: Re: [basil00/Divert] Can't detect drive, but my driver is with the application (#127)
For 32bit applications you need both the WinDivert32.sys and WinDivert64.sys files in the application directory. Otherwise, if you try to run the application on 64-bit Windows, you will get a file-not-found error.

**Comment by Szj-kagami** [comment]
I would like to ask if multi-threaded accepting and sending packets can improve the efficiency of sending and receiving. Why do I use multi-threaded sending and receiving, but the efficiency is lower (using 3 threads), and the WinDivertSend function gives an error parameter error (87), and I The code: WinDivertSend(handle1, buf, j, &send_addr, NULL); the variables inside are guaranteed to be valid. What could be the reason?


szj_kagami@Rayvision.com

**Comment by TechnikEmpire** [comment]
Use the WinDivertRecvEx and WinDivertSendEx variants with the entire IO loop (while(TRUE) section in the examples) being independently run by each thread you want to spawn.

Example of using those functions:

https://github.com/basil00/Divert/blob/master/examples/streamdump/streamdump.c

If I had to guess I'd say you're sharing resources (buffer, address) across threads, which you can't do you must make the entire loop scoped to each thread with it's own resources.

**Comment by basil00** [comment]
See #52 for some performance measurements.  In general, multithreading is much better than single threading performance-wise, but the benefit quickly diminishes as more threads are used.  Having too many threads can be sub-optimal.  It's usually best to experiment if performance is important.

As for the 87 error for `WinDivertSend`, this usually means you are attempting to inject an invalid packet or address structure.

**Comment by Szj-kagami** [comment]
Sorry to bother you again, the last time I simplified the program to use multi-threaded function WinDivertRecv () to receive data, in fact, the performance has indeed improved a lot, but with the increase in the number of threads, performance began to plummet, in Windows Sever2012 R2 8163 2.5GHZ 8G computers can only use up to 3 threads (a lock is used in the thread). Is this normal? Is there a thread that can be used by the computer (without a negative growth in performance) can only be tried out?


szj_kagami@Rayvision.com
