### ISSUE TITLE
FORWARD_LAYER how to block UDP packet?

### ISSUE THREAD

**Issue by kelvinomolumo** [basil00/Divert#130]
On windows 7 there is no way to block or drop a forwarded packet by just specifying the flags. What other ways can i use to block or drop outgoing UDP packets originating from another machine? With TCP packets its just a simple RST packet back to the client. but UDP is connectionless so how do i successfully drop a UDP packet?

**Comment by basil00** [comment]
For UDP you can send an ICMP(v6) "destination unreachable" message back to the client.  See the `netfilter.c` program for an example.  It should work just as well for the `FORWARD` layer.

**Comment by kelvinomolumo** [comment]
This doesnt actually seem to work. I tried the netfilter sample along with Wireshark for ICMP packets. The netfilter only blocks the packets because the handle is open with flag 0. No ICMP "destination unreachable" is returned to the packet's source... Please let me know if i am doing something wrong

**Comment by basil00** [comment]
> No ICMP "destination unreachable" is returned to the packet's source...

I am not sure I understand.  Your application must create and inject an ICMP destination unreachable packet itself.  Or are you saying that the ICMP packet is somehow getting lost?

**Comment by kelvinomolumo** [comment]
Yes I think it’s somehow getting lost because with the net filter sample + Wireshark I still can’t see any ICMP packet

**Comment by basil00** [comment]
Packets injected in the FORWARD layer are not visible in Wireshark, I think.

**Comment by kelvinomolumo** [comment]
Alright but i also tried on WINDIVERT_LAYER_NETWORK i still can't see any ICMP destination unreachable packet in Wireshark... I wrote an ICMP ping program for testing purposes and i am getting a reply as expected... But using netfilter sample program no ICMP destination unreachable packet is ever detected in Wireshark

**Comment by basil00** [comment]
I am not sure of the problem then.  Maybe it is just some other generic bug, like a malformed packet or incorrect checksums?

**Comment by kelvinomolumo** [comment]
I am also suspecting it’s a malformed packet because after adding the DEBUG flag, WinDivertSend returns error 1233. Which translate to Protocol Unreachable.

**Comment by TechnikEmpire** [comment]
I've only ever seen that error returned from WinDivert when I've mistakenly tried to push a packet off a public interface to the loopback adapter or vice versa.

**Comment by kelvinomolumo** [comment]
Yeah but in this case even with netfilter it gives me that error 1233 if I add the DEBUG flag. Doesn’t happen automatically. Have to wait some few minutes before it start showing... basically I am only looking for a simple way to drop UDP packet on the forward layer. With TCP it’s pretty simple. I open an injection handle and I do whatever I want. But UDP being connection less i just don’t know how to go about it
