### ISSUE TITLE
Windivert forward layer modify-reinject issue with NAT

### ISSUE THREAD

**Issue by debugaman** [basil00/Divert#132]
Hi Basil,
I have been using Windivert to develop firewall applications for years.
My firewall works as a server and my clients will direct all the traffic through my firewall and then to the internet.

The handle opened is handle = WinDivertOpen(filter, WINDIVERT_LAYER_NETWORK_FORWARD, 0, 0)
[client 192.168.100.2(for tunnel)] -------> [Server Public: 19.200.20.14 Private(for tunnel): 192.168.100.10 internet: 172.20.18.33] ----> Internet

The version I used in my project is 1.12 and there is no problem in capture-modify-reinject for forward layer  traffic, although the ip address of the packet captured sourcing from client is not their private address(192.168.100.2) but the NATed address 172.20.18.33.

And now I try to update the Windivert version to 1.4, there are two issues:
1. ip address of the packet captured sourcing from client is corrected to 192.168.100.2
2. My firewall can no longer reject the packet to traffic (my firewall can capture it but cannot send it using WindivertSend function)

I have been trying to modify the packets(IP address translation) to perform NAT itself but the result is the  same. Do you have any idea on this?

**Comment by basil00** [comment]
I assume you mean WinDivert 1.1.2 which is a very old version.  Looking at the changelog, the position of the WinDivert driver might of changed, so from after NAT to before NAT, although that was a long time ago so I cannot really remember.

For `WinDivertSend`, using a separate non-FORWARD handle for injection might work.  Injecting at the FORWARD layer means the packet will be intercepted by the NAT, and maybe this is causing problems.

Generally, the combination of the WinDivert FORWARD layer and the NAT is confusing.
