### ISSUE TITLE
[Question] Release 1.4.3 Visual Studio 2010

### ISSUE THREAD

**Issue by wreighsantos** [basil00/Divert#136]
Hi, I have a question, how can I use your latest release (1.4.3) in a C# environment with Visual Studio 2010? Sorry for my ignorance.

**Comment by TechnikEmpire** [comment]
You can't. I have pinvoke classes for WinDivert in my repos but they're for 1.3.x and not 1.4.x. The two are not compatible. You can however copy the pinvoke class out of my repository CitadelCore.Windows and use it with 1.3 or port it to 1.4.

**Comment by TechnikEmpire** [comment]
https://raw.githubusercontent.com/TechnikEmpire/CitadelCore.Windows/master/CitadelCore.Windows/Diversion/WinDivert.cs 

or

https://github.com/TechnikEmpire/DivertPInvoke/blob/master/WinDivert.cs

Or if you're really brave and feel like compiling a separate DLL when it's not necessary, you can go here:

https://github.com/TechnikEmpire/Divert.Net

**Comment by wreighsantos** [comment]
Ok thanks! I'll try that.
