### ISSUE TITLE
Basic question: How can I modify the TCP/IP header without fabricating a new packet?

### ISSUE THREAD

**Issue by PantherJohn** [basil00/Divert#137]
e.g. modify SrcPort in tcp headers.

**Comment by TechnikEmpire** [comment]
Look at the examples? The website/docs?

**Comment by PantherJohn** [comment]
I've tried, though:
```
void intercpt(int opt, HANDLE handel) {

	//HANDLE handel;
	UINT8 packetRecv[MAXBUF];
	UINT packetRecv_len;
	PDATAPACKET packet;
	UINT packet_len;
	PWINDIVERT_IPHDR ip_header;
	PWINDIVERT_TCPHDR tcp_header;
	PVOID payload;
	UINT payload_len;
	WINDIVERT_ADDRESS windivt_addr;


	bool control = true;

	while (control) {

		packet = (PDATAPACKET)malloc(sizeof(DATAPACKET) - 1);
		memset(packet, 0, sizeof(PACKET));
		
		WinDivertRecv(handel, packet, sizeof(PACKET), &windivt_addr, &packet_len);

		//WinDivertRecv(handel, packetRecv, sizeof(packetRecv), &windivt_addr, &packetRecv_len);
		//WinDivertHelperParsePacket(packetRecv, packetRecv_len, &ip_header, NULL, NULL, NULL, &tcp_header, NULL, &payload, &payload_len);
		//packet = (PDATAPACKET)malloc(sizeof(DATAPACKET) + sizeof(payload) - 1);
		
		//packet->header.ip = *ip_header;
		//packet->header.tcp = *tcp_header;

		//memcpy(packet->data, payload, payload_len);
		//WinDivertRecv(handel, packet, sizeof(PACKET), &windivt_addr, &packet_len);

		printf("=");

		if (opt == JIMMY_DST) {

			packet->header.tcp.DstPort = tar_port;
			printf("%u\t%s", ntohs(tar_port), "<DST>");
			printf("\n%u\n",ntohs(packet->header.tcp.DstPort));
		}
		else if (opt == JIMMY_SRC) {
			packet->header.tcp.SrcPort = tar_port;
			printf("<SRC>");
		}
		printf("@");
		WinDivertHelperCalcChecksums((PVOID)packet, sizeof(PACKET), &windivt_addr, 0);
		WinDivertSend(handel, packet, sizeof(PACKET), &windivt_addr, NULL);
		printf("-");

		//control = false;
	}



	/*
	while (true) {
		if (opt == JIMMY_DST)
			if (!WinDivertRecv(handleDst, packetDst, sizeof(packetDst), &addrDvtDst, &packetDstLen))
				printf("\t ERROR: %i", GetLastError());
		if (opt == JIMMY_SRC)
			if (!WinDivertRecv(handleSrc, packetSrc, sizeof(packetSrc), &addrDvtSrc, &packetSrcLen))
				printf("\t ERROR: %i", GetLastError());

		printf("\n! Recv\n");

		// Modify packetDst.
		if (opt == JIMMY_DST)
			WinDivertHelperParsePacket(packetDst, packetDstLen, &ip_headerDst, NULL, NULL, NULL, &tcp_headerDst, NULL, NULL, NULL);
		if (opt == JIMMY_SRC)
			WinDivertHelperParsePacket(packetSrc, packetSrcLen, &ip_headerSrc, NULL, NULL, NULL, &tcp_headerSrc, NULL, NULL, NULL);

		if (opt == JIMMY_DST) {
			//printf("%u-%u", ntohs(tcp_headerDst->SrcPort), ntohs(tcp_headerDst->DstPort));
			printf("\nDst\n");
			packetDst_->header.ip = *ip_headerDst;
			packetDst_->header.tcp = *tcp_headerDst;
			
			packetDst_->header.tcp.DstPort = tar_port;
			//tcp_headerDst->DstPort = tar_port;
		}
		if (opt == JIMMY_SRC) {
			//printf("%u-%u", ntohs(tcp_headerSrc->SrcPort), ntohs(tcp_headerSrc->DstPort));
			printf("\nSrc\n");
			memcpy(packetSrc_, packetSrc, sizeof(packetSrc));
			packetSrc_->header.tcp.SrcPort = tar_port;
			//tcp_headerSrc->DstPort = tar_port;
		}

		printf("\n! Great\n");


		if (opt == JIMMY_DST) {
			//WinDivertHelperCalcChecksums(packetDst, packetDstLen, &addrDvtDst, 0);
			if (!WinDivertSend(handleDst, packetDst_, packetDstLen, &addrDvtDst, NULL))
				printf("\t ERROR: %i", GetLastError());
		}
		if (opt == JIMMY_SRC) {
			//WinDivertHelperCalcChecksums(packetSrc, packetSrcLen, &addrDvtSrc, 0);
		if (!WinDivertSend(handleSrc, packetSrc_, packetSrcLen, &addrDvtSrc, NULL))
				printf("\t ERROR: %i", GetLastError());

		}
	}
	*/
}
```

**Comment by TechnikEmpire** [comment]
- 1) Why are you malloc'ing a buffer at all? Pass your `packetRecv` buffer as the parameter. Also FYI you're mallocing in a loop and never freeing it, how is this program not crashing by exhausting resources like ultra fast?

- 2) Why are you sending `sizeof(DATAPACKET)` when you ought to be sending the size you received from `WinDivertRecv`? In your code example you use `packet_len` when you should be using `packetRecv_len` and throwing away both `packet` and `packet_len` variables. So, with that correction, you should be passing `packetRecv_len` to `WinDivertSend`, not anything else like `sizeof(X)`.

Please look over the examples again.

**Comment by PantherJohn** [comment]
@TechnikEmpire So reconstruction of packets is still necessary? as mentioned:
> No idea what a DATAPACKET is but I see absolutely no call to the WinDivertHelperParsePacket. You can't just initialize the raw array into a struct. I wish it were that simple but it's not.

**Comment by TechnikEmpire** [comment]
@PantherJohn Yes. WinDivert does a lot of complex calculations behind the scene to properly parse out packets and set all of the headers ((IP Layer - IPV4, IPV6) (Proto Layer - TCP, UDP, ICMP) (Packet Payload)) so that you can access and modify that data properly. Think of the packets as onion layers. WinDivert has to check and see how "deep" each layer is, then set your pointers-to-pointers to the proper offsets and such, so and so forth.

Absolutely you must either call `WinDivertHelperParsePacket` or write your own packet parsing algorithm from scratch. You cannot simply dereference the pointer and cast the pointer type.

**Comment by PantherJohn** [comment]
@TechnikEmpire Hahah, thanks anyway. This is initially expected....

**Comment by TechnikEmpire** [comment]
@PantherJohn I hope we're talking about the same thing. You need to parse them. You're not reconstructing/building new packets. You're parsing the contiguous memory that you've asked WinDivert to copy the raw packet into and setting the `X_HEADER` pointers to the right offsets within that memory. You should not need to call malloc/new a single time in your application.

**Comment by PantherJohn** [comment]
@TechnikEmpire I used
```
PVOID pPacket;
```
What should the `pPacket` type be in order for the WinDivert to parse packets properly?
From the example:
```
typedef struct
{
    WINDIVERT_IPHDR  ip;
    WINDIVERT_TCPHDR tcp;
} PACKET, *PPACKET;

typedef struct 
{
    PACKET header;
    UINT8 data[];
} DATAPACKET, *PDATAPACKET;
```

**Comment by TechnikEmpire** [comment]
@PantherJohn It's `PVOID` in the parameter list, what it really wants is a `char buff[65536 or MAXBUF]`, where you can pass the pointer `&buff` to the `PVOID` buffer parameter.

Here's me using WinDivert to pipe HTTP/S traffic to a filtering proxy in C++ land:
https://github.com/TechnikEmpire/HttpFilteringEngine/blob/master/src/te/httpengine/mitm/diversion/impl/win/WinDiverter.cpp#L184

**Comment by PantherJohn** [comment]
@TechnikEmpire 
```
	while (TRUE)
	{
		if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
		{
			// Handle recv error
			continue;
		}

		// Modify packet.
		WinDivertHelperParsePacket(packet, packetLen, &ip_header, NULL, NULL, NULL, NULL, &udp_header, NULL, NULL);

		udp_header->DstPort = dst_port;

		WinDivertHelperCalcChecksums(packet, packetLen, &addr, 0);
		if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
		{
			// Handle send error
			continue;
		}
	}
```
This my original implementation on redirecting UDP ports.
and I see this line:
```
tcpHeader->DstPort = (tcpHeader->DstPort == StandardHttpPort) ? m_httpListenerPort : m_httpsListenerPort;
```
meaning
`WinDivertRecv(...)->WinDivertHelperParsePacket(...)->WinDivertSend(...)`

**Comment by TechnikEmpire** [comment]
@PantherJohn So that code snippet you show at the top there certainly does look much better. What problems does that snippet give you?

**Comment by TechnikEmpire** [comment]
Also note that I've already run `htnol(...)` on things like `m_httpListenerPort` in my code. Remember, big-endian values.

**Comment by PantherJohn** [comment]
@TechnikEmpire The problem was resolved...Thanks
See here https://github.com/PantherJohn/Jimmy
The reason why handshake failed is because of the ports.

**Comment by TechnikEmpire** [comment]
Glad its sorted. :)

**Comment by basil00** [comment]
> when redirecting TCP ports you need to switch ports in both directions, inbound and outbound.,

This trips up a lot of people.  Anyway, glad it got sorted out.

**Comment by PantherJohn** [comment]
Exactly 😂
