### ISSUE TITLE
[Question] Bandwith Throttling

### ISSUE THREAD

**Issue by kelvinomolumo** [basil00/Divert#141]
For some time now I have been thinking of implementing of bandwith throttling feature in my app but I really don’t know how to go about it as WinDivert can’t indefinitely keep packets in a Queue. So I am wondering if it’s possible...If yes how can it be done. I just need a rough idea on how to implement this. E.g: Let’s say I want some particular packets to not exceed 100Kb/secs

**Comment by basil00** [comment]
As @TechnikEmpire says, the normal way to do this is to implement your own user-space packet queue rather than rely on the internal WinDivert queue.

The internal queue has limits (time/space/length), and also consumes "non paged" memory which is a limited kernel resource.
