### ISSUE TITLE
WSARecvEx with IOCP

### ISSUE THREAD

**Issue by yanrk** [basil00/Divert#144]
if WSARecvEx return false and errno is io_pending, 
GetQueuedCompletionStatus will notify it in another thread when recv data really？

what I want to ask is:
if WSARecvEx return true, 
GetQueuedCompletionStatus would still notify it in another thread？

**Comment by basil00** [comment]
I assume you meant `WinDivertRecvEx`.

> GetQueuedCompletionStatus will notify it in another thread when recv data really？

I am not sure, but I guess it is possible to call `GetQueuedCompletionStatus` from a different thread.

> GetQueuedCompletionStatus would still notify it in another thread？

If `TRUE` is returned then the request is never queued, so I don't think it notifies.  But I am really not sure; this does not depend on WinDivert, and I am not an expert on this part of the WinAPI.
