### ISSUE TITLE
Performance degradation on 64-bit

### ISSUE THREAD

**Issue by gv2870** [basil00/Divert#146]
Hi,

We were checking the windivert project and its related samples on Windows 10 64-bit systems and we observed a huge loss of through put on windows 8 and windows 10 64-bit systems.

For example, with the passthru sample running, downloading a 400MB sample (using http and wget), we get a through put of 2.57M/s

passthru cmd:
passthru "( tcp.PayloadLength > 0 ) and ( tcp.DstPort=80 or tcp.SrcPort=80 )" 64

And on a clean machine, we get a through put of 6.19M/s

This doesn't happen on 32-bit systems.

What could be the issue?

GR

**Comment by basil00** [comment]
> passthru "( tcp.PayloadLength > 0 ) and ( tcp.DstPort=80 or tcp.SrcPort=80 )" 64

64 threads is a large number.  How many cores does your machine have?

**Comment by gv2870** [comment]
Number of processor cores: 2
Number of logical processors: 4

But, it wouldn't matter.  Even if the threads is reduced to 4 or 8, there is not much change - meaning the loss of thru-put is very high.
And it is easily replicated - only on Win 10 x64 or Win 8 x64.
The loss is not seen in Sniff mode - and, as mentioned earlier, on 32-bit systems.

**Comment by gv2870** [comment]
Yes, i understand with the no loss in sniff mode where packets are not dropped and re-injected. 
Its native machine and not VM.

**Comment by basil00** [comment]
I have run some new benchmarks on native Windows 10 x64, average of 5 runs:

    Native:   98.62Mb/s down 87.86Mb/s up
    passthru: 90.58Mb/s down 82.28Mb/s up

This was with the `true` filter and 3 threads (4 core machine).  Using your filter seemed to improve the results slightly (less packets diverted).

The test was run over wifi, but nevertheless the results are not inconsistent with previous WinDivert benchmarks.  So I am unsure of the reason for your drop in bandwidth, but it is unlikely that it is an issue with WinDivert directly.  It might be an bad interaction with WinDivert and other drivers, network conditions, the application, etc., but this would not be possible for me to diagnose remotely.

**Comment by kelvinomolumo** [comment]
Try adding !impostor in the filter it might help. I have noticed that on some machine some packets are being reinjected by some other drivers which might cause some conflits. Just give it a try
