### ISSUE TITLE
Program hang on WinDivertRecv() function call

### ISSUE THREAD

**Issue by izhlidan** [basil00/Divert#148]
When I test the example code (https://reqrypt.org/windivert-doc.html) and I found my 'test' program hang on WinDivertRecv() function call.

But the program is continue running after I press CTRL + C.
My environment:
Windows 10 (x64);
WinDivert-1.4.3 pre-build driver;

The code:
#define MAXBUF 65535
#define FILTER "tcp.DstPort == 443"

int main(int argc, char** argv) {
	HANDLE handle;          // WinDivert handle
	WINDIVERT_ADDRESS addr; // Packet address
	char packet[MAXBUF];    // Packet buffer
	UINT packetLen;

	handle = WinDivertOpen(FILTER, WINDIVERT_LAYER_NETWORK, 0, 0);   // Open some filter
	if (handle == INVALID_HANDLE_VALUE)
	{
		// Handle error
		exit(1);
	}

	// Main capture-modify-inject loop:
	while (TRUE)
	{
		if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
		{
			// Handle recv error
			continue;
		}

		// Modify packet.
		printf("Packet length = %d\n", packetLen);

		//WinDivertHelperCalcChecksums(packet, packetLen, &addr, 0);
		if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
		{
			// Handle send error
			continue;
		}
	}
}

**Comment by TechnikEmpire** [comment]
Use the Ex function with a low timeout to avoid any such temporary deadlocking. Try the main loop of the streamdump example and modify it, it uses the Ex receive function.

**Comment by izhlidan** [comment]
It's not temporary deadlocking. It worked well at the beginning of running the example, but it suddenly blocked (about 2 minutes), and a lot of network packets not processed.

When I press CTRL+C to terminate the test program, it continue to process the remained packets rather then be terminated.

And I guess that the WinDivert.sys did not notify the WinDivert.dll to read the packets after the filtered packets is ready.

**Comment by basil00** [comment]
> and a lot of network packets not processed.

The program is calling `printf` on every diverted packet.  So my best guess is that the program is overwhelming the console with `printf`s, and the I/O delay is also causing packets to be dropped.  After ctl+c, the stdout backlog continues to be printed even after the program has been terminated.  That's the only thing I can think of.

What about the WinDivert sample programs, do they work as expected?

**Comment by izhlidan** [comment]
Nope!
I run the netdump.c example on my WIN10 and it is also blocked until I press ctrl+c.

And another bug, I think,  when I print tcp.SeqNum and tcp.AckNum to stdout using printf, these two value is invalid.  The code is:
```
printf("TCP SP:%u ==> DP:%u SEQ:%u ACK:%u\n",
	ntohs(tcphdr->SrcPort), ntohs(tcphdr->DstPort),
	ntohl(tcphdr->SeqNum), ntohl(tcphdr->AckNum)
);
```
The example netdump.c has the same invalid value too.
```
TCP [SrcPort=54460 DstPort=80 SeqNum=2767947280 AckNum=2618293951 HdrLength=5 Reserved1=0 Reserved2=
0 Urg=0 Ack=1 Psh=0 Rst=0 Syn=0 Fin=0 Window=64240 Checksum=0x7F32 UrgPtr=0]
```

**Comment by basil00** [comment]
> I run the netdump.c example on my WIN10 and it is also blocked until I press ctrl+c.

Did you use the `netdump.exe` binary that was included in the WinDivert distribution?
I tried it myself but the program behaved as expected, i.e., dumps packets until ctl+c.  The program quickly terminates after ctl+c is pressed.

> these two value is invalid.

They seem OK.  The seq/ack numbers are random in modern TCP implementations.

**Comment by izhlidan** [comment]
I did not test the `netdump.exe` binary.
It seems that I have done something wrong with the example code, and I will continue to try it again. 

Yes, the TCP seq/ack is OK.
I started more than one application and generated more than one TCP flows, so the value is mistaken for invalid.

Thanks for your answers, you are so kind!

**Comment by basil00** [comment]
OK I guess this was resolved.
