### ISSUE TITLE
How to implement timeout in Receive API

### ISSUE THREAD

**Issue by wreighsantos** [basil00/Divert#150]
I'm using WinDivert in C# and seems that the `Receive` API will continue to wait until something's receive. But how should I implement a timeout for the Receive?

Right now I'm implementing the Receive inside a Thread and I'm aborting the thread once the timeout is reached. Will that suffice? I mean, does aborting the Thread containing the `Receive` API call do indeed stop the receiving?

If no, then how should I do it? Maybe there's a parameter or feature already available for tweaking.

Thank you!

**Comment by TechnikEmpire** [comment]
https://github.com/basil00/Divert/blob/e82552153b6f9a01257357f2ed1a335703790d36/examples/streamdump/streamdump.c#L230

**Comment by wreighsantos** [comment]
Got it! Thank you sir :)
Sorry for the inconvenience.
