### ISSUE TITLE
Why is msvc-build.bat removed?

### ISSUE THREAD

**Issue by rolfrennemo** [basil00/Divert#152]

**Comment by rolfrennemo** [comment]
found the comments in git. 

Retire MSVC-2012 and (non-driver) WDDK builds.
The new MINGW build should be compatible with all
major compilers, including Visual Studio 201X.

guess I'm moving to MINGW

**Comment by rolfrennemo** [comment]
Are you saying that I can build something like netfilter just using VS along with the binary windivertnn.sys?

**Comment by basil00** [comment]
Yes, the WinDivert distribution includes all the files you need.  All you need to do is copy/include the files into your project.  There is no need to build any WinDivert file yourself.

The important files are:
 
* `x86/WinDivert32.sys` and `x86_64/WinDivert64.sys` driver files
* `x86/WinDivert.dll` and `x86_64/WinDivert.dll` DLL files
* `x86/WinDivert.lib` and `x86_64/WinDivert.lib` import library files (for Visual Studio linking)
* `include/windivert.h` header file

Also see [here](https://github.com/basil00/Divert/wiki/WinDivert-Documentation#installing).

**Comment by rolfrennemo** [comment]
A couple of Q's. I'm not an expert in setting up VS.

Should I use VS2017 or VS2012?
I know how to add the include and library files, by configuring the solution properties. Modify the VC++ directories and Additional Dependencies for the Linker.

But not where to place the dlls and drivers and any settings.

Appreciate a tip on this.

**Comment by basil00** [comment]
> Should I use VS2017 or VS2012?

VS2017 I guess.

> But not where to place the dlls and drivers and any settings.

I almost never use VS so I do not know.
