### ISSUE TITLE
With Out Sln It's Not Working

### ISSUE THREAD

**Issue by AkshayUsha** [basil00/Divert#155]
i want to windivert in visual studio 2017 for windows 10 with vxproj file and sln file ....i hope u provide me this code for driver create in visual studio 2017

**Comment by basil00** [comment]
If you want to build WinDivert applications, then just link against the pre-compiled `.lib` available [here](https://github.com/basil00/Divert/releases).

If you want to build WinDivert itself from source, then currently the only way to do it is using WDK7 (for the driver) and MinGW cross-compilation from Linux (for everything else).  See the documentation [here](https://github.com/basil00/Divert/wiki/WinDivert-Documentation#building).
