### ISSUE TITLE
streamdump.exe latency

### ISSUE THREAD

**Issue by Valerio69** [basil00/Divert#158]
Hello,

I wanted to try the streamdump.exe example, so I decided to proxy all the connections of a game.
The traffic was redirected correctly and everything was working fine, but I noticed a 40ms delay in Windows Resource Monitor.

![latency](https://user-images.githubusercontent.com/8821449/46852124-2ae57900-cdfa-11e8-84d6-09b7a4d98be9.png)

I was expecting 0-1 latency since the redirection and everything else is inside the same Machine.
What's causing this 40ms latency?  Is it adding 40ms at every redirection?

**Comment by basil00** [comment]
Possibly.  The `streamdump.exe` sample prints to console before forwarding the stream, which adds a lot of latency at least when I try on a virtual machine.  There may be other sources of latency, such as TCP's send coalescing, but I am not sure if these are significant.
