### ISSUE TITLE
Modifying packet?

### ISSUE THREAD

**Issue by jpippy** [basil00/Divert#16]
Hi there, just wan't to begin and say great project. I am sorry to post this into your issue tracker, but I wasn't sure where else to post it. How can I modify a packets sender information, such as mac and Ip address?

I want to listen for a certain outbound packet my application sends and then intercept the packet before it is sent out and change the source ip and mac and reinject it. I havent seen any details on how to modify a packet like this. Can you help me out with that?

**Comment by daxionga** [comment]
[https://www.youtube.com/watch?v=yPcVddpBqzY](test)
