### ISSUE TITLE
I've developed a captive portal solution using WinDivert

### ISSUE THREAD

**Issue by lumogate** [basil00/Divert#163]
Hi @basil00,  

![lumogate4](https://user-images.githubusercontent.com/5679033/48934988-f4714280-eefd-11e8-89bd-b93893d9e2e9.PNG)

![lumogate3](https://user-images.githubusercontent.com/5679033/48934986-f3d8ac00-eefd-11e8-833f-01c3daea326f.PNG)

. I've used your library (WinDivert) into my project. It is a work in progress with a lot of features to be added. For anyone interested to try it, it's available on both Github & Sourceforge

https://github.com/lumogate/LumoGate/

https://sourceforge.net/projects/lumogate/

Please review if possible

Thank you, again.

**Comment by lumogate** [comment]
closing this as its not an issue

**Comment by basil00** [comment]
Not open source?

Also, best not to open issues for things like this.  I got your email, but I only check every 1-3 days so there can be a delay.

**Comment by lumogate** [comment]
Really sorry then @basil00. Thanks for your reply. Not open source.
