### ISSUE TITLE
Zeroing wrong memory

### ISSUE THREAD

**Issue by dhaavi** [basil00/Divert#168]
While checking out your code, I noticed a possible bug:

When calling `RtlZeroMemory(&addr, 16);`, you take the address of a `UINT8 *`, effectively passing `RtlZeroMemory` a `UINT8 **`, which expects a `void *`.

Nothing happens because `addr8` is a  local stack variable, but the desired effect of zero-ing the IP is not reached.

https://github.com/basil00/Divert/blob/e306d0058bc0b4ad625351c5cfdeba940d66b6d0/sys/windivert.c#L3416-L3421

**Comment by basil00** [comment]
Thanks, well spotted.  This bug could corrupt the stack and/or leak kernel memory contents, so needs to be fixed.  Unfortunately it means the drivers will need to be signed again.

**Comment by basil00** [comment]
Signed drivers that include the fix are now available:

* [WinDivert-2.0.0-rc-signed.zip](https://reqrypt.org/temp/WinDivert-2.0.0-rc-signed.zip)

**Comment by dhaavi** [comment]
Great!
