### ISSUE TITLE
Is support for windows2008-2012-2016?

### ISSUE THREAD

**Issue by muse117** [basil00/Divert#170]
hi, basil00:

Is support for windows2008-2012-2016?

**Comment by basil00** [comment]
Yes.  But for Windows 2016 you must have secure boot disabled else the driver signature will not be accepted.

**Comment by jjxtra** [comment]
Why is it necessary to disable secure boot? Is there no work-around?

**Comment by basil00** [comment]
Maybe it is not required.  It was advice based on the Microsoft documentation of the day, but it seems that the documentation was [incorrect](https://github.com/MicrosoftDocs/windows-driver-docs/issues/1068).

Can anyone test if the current drivers load on Windows 2016 with secure boot on?

Quick background: the current drivers use *attestation signing*.  The alternative is to go through the HLK/HCK testing process, which is a significant burden (requires setting up a separate test machine, etc.).  According to previous versions of the docs, HLK was required for Windows 2016 with secure boot ON, but maybe that is not true.
