### ISSUE TITLE
[Feature Request] Lightweight filtering

### ISSUE THREAD

**Issue by jjxtra** [basil00/Divert#173]
Right now in order to do any kind of filtering, reading and re-writing of the entire packet is required. It would be great for optimization to have a way to filter based just on the address portion of the data, ignoring the actual packet data in the user code.

I realize this would require some rework of the APIs or maybe new APIs. The kernel driver ought to be able to map some sort of id to addresses and keep the packet data in memory mapped to these ids. When some variant of SendEx is called with just addresses and these special identifiers, the system would know to send those packets on, without having to have sent the actual packet data to the user mode code.

Let me know if this is already possible.

**Comment by TechnikEmpire** [comment]
It seems like you're asking for the headers but not the payload. Not possible AFAIK. But for your first paragraph, look at the filter string documentation. You can totally tell the driver to only grab packets based on the contents of the packet (header data, etc)

**Comment by muse117** [comment]
> Right now in order to do any kind of filtering, reading and re-writing of the entire packet is required. It would be great for optimization to have a way to filter based just on the address portion of the data, ignoring the actual packet data in the user code.
> 
> I realize this would require some rework of the APIs or maybe new APIs. The kernel driver ought to be able to map some sort of id to addresses and keep the packet data in memory mapped to these ids. When some variant of SendEx is called with just addresses and these special identifiers, the system would know to send those packets on, without having to have sent the actual packet data to the user mode code.
> 
> Let me know if this is already possible.

You can read about NDIS LWF, I also hope to increase NDIS driver feature.

**Comment by jjxtra** [comment]
Well scratch that, it looks like socket layer can only be re-opened in read-only mode??? Why is that? I want to be able to call send to send socket events back to allow an accept operation based on the ip address. I can't specify thousands of ip addresses in the filter string, and they change regularly.

**Comment by jjxtra** [comment]
Something like this would be ideal, but of course can't call send here and any socket in the filter is auto-blocked.

```csharp
while (!Disposed)
{
        uint tmp = 0;
	if (WinDivert.WinDivertRecv(winDivertHandle, IntPtr.Zero, ref tmp, addressPtr))
	{
		WINDIVERT_DATA_SOCKET* socket = (WINDIVERT_DATA_SOCKET*)address.AdditionalData;
		Marshal.Copy(new IntPtr(socket->RemoteAddr), ipBytes, 0, 16);
		IPAddress ip = new IPAddress(ipBytes);
		if (!IsIPAddressBlocked(ip.ToString(), socket->LocalPort))
		{
			if (!WinDivert.WinDivertSend(winDivertHandle, IntPtr.Zero, 0, addressPtr, ref tmp))
			{
				// error
			}
		}
	}
	else
	{
		// error
	}
}
```

**Comment by basil00** [comment]
@jjxtra 

> id to addresses and keep the packet data in memory mapped to these ids.

Currently the driver is stateless, so something like this would be a somewhat radical change.  You'd also need to consider what happens if the user application hangs and the "verdict" for each packet never arrives.

Incidentally, this is how Linux's `netfilterqueue` works (closet thing to WinDivert on Linux).  It optimizes some use cases as you say, but makes doing even some simple things impossible (e.g., split a single packet into two).  Divert sockets (MacOSX and BSD) are way more flexible but slower in some use cases.

> Well scratch that, it looks like socket layer can only be re-opened in read-only mode??? Why is that?

Because you can't do stateless filtering at these layers.  The driver needs to pend the classify operation which is represented by a handle.  That handle needs to be threaded through the user application somehow.  Then it is the same problem as before, since the user application may be unreliable.

That said, it **may** be supported in future, but more research needs to be done.  This and other features were not included in 2.0 else the release would have been further delayed.

@TechnikEmpire 
> It seems like you're asking for the headers but not the payload. Not possible AFAIK.

If you just want the headers, then pass a truncated buffer to `WinDivertRecv` and treat `ERROR_INSUFFICIENT_BUFFER` as success.

**Comment by TechnikEmpire** [comment]
@basil nice, I didn't know this. Thanks for letting me know. Say if I truncate the buffer just enough to get headers and manipulate them, ignoring the payload and leaving it in kernel space. Will that work?

**Comment by jjxtra** [comment]
Can you give more info on headers only? Sounds very promising. Maybe point to a code sample?

**Comment by TechnikEmpire** [comment]
@jjxtra, if he gives an affirmative to my question then it would be as simple as keeping he buffer to the size of TCP+ip/UDP+IP.

**Comment by jjxtra** [comment]
So you could pass a buffer that is something like 32 * (sizeof(tcpheader) + sizeof(ipheader))? It would know not to put payloads in?

**Comment by basil00** [comment]
It is probably not what you want.  If you only read the headers the rest of the packet (e.g., the payload) is discarded.

**Comment by TechnikEmpire** [comment]
Rip. Oh well.

**Comment by basil00** [comment]
> Something like this would be ideal, but of course can't call send here and any socket in the filter is auto-blocked.

Note that if you only interested in TCP connections, then the usual way is to only filter `tcp.Syn` packets at the `NETWORK` layer.

**Comment by jjxtra** [comment]
What is the different from passing tcp vs tcp.Syn?

**Comment by jjxtra** [comment]
I am seeing the udp bit set in my address structure. Does that mean I have some offsets wrong? I am using C# so there could be a marshal issue, but the struct seems to match. My filter has tcp only.

```csharp
/// <summary>
        /// The WinDivertAddress structure represents the "address" of a captured or injected packet. The
        /// address includes the packet's timestamp, network interfaces, direction and other information.
        /// </summary>
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1, Size = 80)]
        public unsafe struct WinDivertAddress
        {
            /// <summary>
            /// Gets or sets the timestamp.
            /// </summary>
            /// <remarks>
            /// The Timestamp indicates when the packet was first captured by WinDivert. It uses the same
            /// clock as QueryPerformanceCounter(). The Timestamp value is ignored by <seealso cref="WinDivert.WinDivertSend(System.IntPtr, System.IntPtr, uint, WinDivertAddress*, ref uint)" />.
            /// </remarks>
            public ulong Timestamp;

            /// <summary>
            /// Layer
            /// </summary>
            public byte Layer;

            /// <summary>
            /// Event
            /// </summary>
            public byte Event;

            /// <summary>
            /// Flags
            /// </summary>
            public byte Flags;

            /// <summary>
            /// Reserved
            /// </summary>
            public fixed byte Reserved[5];

            /// <summary>
            /// Additional info, cast to appropriate struct pointer
            /// </summary>
            public fixed byte AdditionalData[64];

            /// <summary>
            /// Sniffed flag
            /// </summary>
            public bool Sniffed
            {
                get { return (Flags & 1) == 1; }
                set { SetFlag(value, 1); }
            }

            /// <summary>
            /// Outbound flag
            /// </summary>
            public bool Outbound
            {
                get { return (Flags & 2) == 2; }
                set { SetFlag(value, 2); }
            }

            /// <summary>
            /// Loopback flag
            /// </summary>
            public bool Loopback
            {
                get { return (Flags & 4) == 4; }
                set { SetFlag(value, 4); }
            }

            /// <summary>
            /// Imposter flag
            /// </summary>
            public bool Impostor
            {
                get { return (Flags & 8) == 8; }
                set { SetFlag(value, 8); }
            }

            /// <summary>
            /// IPV6 flag
            /// </summary>
            public bool IPv6
            {
                get { return (Flags & 16) == 16; }
                set { SetFlag(value, 16); }
            }

            /// <summary>
            /// IP checksum flag
            /// </summary>
            public bool IPChecksum
            {
                get { return (Flags & 32) == 32; }
                set { SetFlag(value, 32); }
            }

            /// <summary>
            /// TCP checksum flag
            /// </summary>
            public bool TCPChecksum
            {
                get { return (Flags & 64) == 64; }
                set { SetFlag(value, 64); }
            }

            /// <summary>
            /// UDP checksum flag
            /// </summary>
            public bool UDPChecksum
            {
                get { return (Flags & 128) == 128; }
                set { SetFlag(value, 128); }
            }

            /// <summary>
            /// Reset all fields to default
            /// </summary>
            public void Reset()
            {
                Timestamp = 0;
                Layer = 0;
                Event = 0;
                Flags = 0;
            }

            private void SetFlag(bool flagValue, int bitValue)
            {
                if (flagValue)
                {
                    Flags |= (byte)bitValue;
                }
                else
                {
                    Flags = (byte)(Flags & (~bitValue));
                }
            }
        }
```

**Comment by jjxtra** [comment]
Same error in visual C++, looks like it may be a .dll problem. I will log a new issue.
