### ISSUE TITLE
WinDivert2.0 ## WinDivertOpen fails with error code 2 on win10.0.17134

### ISSUE THREAD

**Issue by muse117** [basil00/Divert#175]
OS: win10.0.17134
VS: 2017
windivert: 2.0（error），1.4.3（good）
exmaple: netfilter.exe

![微信截图_20190409172004](https://user-images.githubusercontent.com/9733486/55789822-a5632d00-5aed-11e9-8d1e-4fa87ba8891c.png)

![微信截图_20190409172904](https://user-images.githubusercontent.com/9733486/55789479-02121800-5aed-11e9-9f01-62d31b503705.png)

![微信截图_20190409172832](https://user-images.githubusercontent.com/9733486/55789496-09392600-5aed-11e9-991f-f8f23fbce3f4.png)

**Comment by TechnikEmpire** [comment]
Error 2 is file not found. You're missing a .sys file for your platform. For example, when running a 32 bit user space program linking windivert, you should have both the 32 and 64 bit SYS with it just in case you're running on a 64 bit machine. 64 bit drivers get loaded in such a case regardless of the fact that your user space program is 32 bit.

**Comment by TechnikEmpire** [comment]
Well obviously windows doesn't see the driver file for whatever reason.

**Comment by basil00** [comment]
There was a bug in the release script, which meant a copy of `WinDivert64.sys` was not included in the `x86` directory.  You just need to copy it yourself to fix the error.

> This is working directory, The v1.4.3 is good, but, v2.0 is error.

You probably need to run `sc stop windivert` or reboot, then try again.

**Comment by muse117** [comment]
I have copyed WinDivert64.sys to the x86 directory and reboot. but, This error still exists.

![微信截图_20190410091737](https://user-images.githubusercontent.com/9733486/55844809-b6ee1880-5b71-11e9-8a69-7920eccecbab.png)

**Comment by muse117** [comment]
> There was a bug in the release script, which meant a copy of `WinDivert64.sys` was not included in the `x86` directory. You just need to copy it yourself to fix the error.
> 
> > This is working directory, The v1.4.3 is good, but, v2.0 is error.
> 
> You probably need to run `sc stop windivert` or reboot, then try again.

I have copyed WinDivert64.sys to the x86 directory and reboot. but, This error still exists.

![微信截图_20190410091737](https://user-images.githubusercontent.com/9733486/55853701-db0f2100-5b94-11e9-9936-b6b498021dae.png)

**Comment by muse117** [comment]
> > There was a bug in the release script, which meant a copy of `WinDivert64.sys` was not included in the `x86` directory. You just need to copy it yourself to fix the error.
> > > This is working directory, The v1.4.3 is good, but, v2.0 is error.
> > 
> > 
> > You probably need to run `sc stop windivert` or reboot, then try again.
> 
> I have copyed WinDivert64.sys to the x86 directory and reboot. but, This error still exists.
> 
> ![微信截图_20190410091737](https://user-images.githubusercontent.com/9733486/55853701-db0f2100-5b94-11e9-9936-b6b498021dae.png)
>

**Comment by ILoveCoding22** [comment]
can anyone help me?, i have a error at my code in c#, i try to run windivert drop program, here is my code: 



 var device = new WinDivertDevice();
             //WINDIVERT_FLAG_DROP will cause the original packet to be dropped
            // you can inject it back (after modifications) using `device.SendPacket()`
            device.Flags = WINDIVERT_FLAG_DROP;
            device.Open();
            // You can use any Libpcap example as reference for receiving);




and i have windivert.dll, windivert32.sys, windivert64.sys and windivert.lib in my dir and i run it as an admin, if i run it i get this error: 0x8007000B 

can anyone help?
