### ISSUE TITLE
Address has udp checksum bit instead of tcp checksum bit

### ISSUE THREAD

**Issue by jjxtra** [basil00/Divert#176]
Using pass through example on Windows 10 x64 latest Windows updates. Filter is "inbound and tcp". Windivert 2.0 latest binaries.

Breakpoint on line 183 of passthru.c. The address pointer ('addr') has the udp checksum bit set but not the other checksum bits. For a tcp packet with a valid checksum I would expect the tcp checksum bit to be set, not the udp one.

Unless I am missing something here.

**Comment by basil00** [comment]
The `addr.UDPChecksum` bit is only meaningful if the packet contains a UDP header.  If not it can be 1 or 0.

**Comment by jjxtra** [comment]
Should the tcp checksum be one in this case? It is a 0...

**Comment by basil00** [comment]
If it is a 0 then it just means the TCP header does not have a valid checksum.

**Comment by jjxtra** [comment]
That is odd, I am just pulling out packets and addresses from traffic without modifying. Is it common to have every packet with an invalid checksum?

**Comment by basil00** [comment]
Yes, it is normal with TCP checksum offloading enabled (it is usually enabled by default).

**Comment by jjxtra** [comment]
Great thanks very much. How would I contact you for discussion of paying for a custom feature inside of WinDivert?

**Comment by basil00** [comment]
You can contact me via email, see [here](https://reqrypt.org/windivert.html) for my address.
