### ISSUE TITLE
WinDivert2.0 ## WinDivertOpen fails with error code 2 on 【win10.0.17134】

### ISSUE THREAD

**Issue by muse117** [basil00/Divert#177]
> > There was a bug in the release script, which meant a copy of `WinDivert64.sys` was not included in the `x86` directory. You just need to copy it yourself to fix the error.
> > > This is working directory, The v1.4.3 is good, but, v2.0 is error.
> > 
> > 
> > You probably need to run `sc stop windivert` or reboot, then try again.
> 
> I have copyed WinDivert64.sys to the x86 directory and reboot. but, This error still exists.
> 
> ![微信截图_20190410091737](https://user-images.githubusercontent.com/9733486/55853701-db0f2100-5b94-11e9-9936-b6b498021dae.png)
> 

I test with using the lower version win10 system, runs normally, but, the high version test is abnormal, whether has the relation with the system version

![微信截图_20190410161312](https://user-images.githubusercontent.com/9733486/55863270-cb033b80-5bac-11e9-81ac-fc5b4449059e.png)

![微信截图_20190410161012](https://user-images.githubusercontent.com/9733486/55863286-d0f91c80-5bac-11e9-98c6-c7cf244375e0.png)

_Originally posted by @muse117 in https://github.com/basil00/Divert/issues/175#issuecomment-481547604_

**Comment by basil00** [comment]
I went through all the steps and failed to reproduce the problem.  When I copied `WinDivert64.sys` to the directory, the (2) error went away and `netfilter true` worked normally.  This is for `10.0.17134.648`.

The only thing I can think of is that your WinDivert service is somehow in a corrupted state.  Try:

    windivertctl.exe uninstall

Then try again.

**Comment by muse117** [comment]
> I went through all the steps and failed to reproduce the problem. When I copied `WinDivert64.sys` to the directory, the (2) error went away and `netfilter true` worked normally. This is for `10.0.17134.648`.
> 
> The only thing I can think of is that your WinDivert service is somehow in a corrupted state. Try:
> 
> ```
> windivertctl.exe uninstall
> ```
> Then try again.

I execute windivert.exe uninstall, but the problem is still the same. I use win10.0.17134 on my colleague's computer is ok. It's really weird!!! Why does my system have it?

![微信截图_20190411092251](https://user-images.githubusercontent.com/9733486/55924269-bae66d00-5c3b-11e9-9c62-a45c86c5cef6.png)

**Comment by TechnikEmpire** [comment]
Does this happen across reboots? Sc stop windivert1.4, 2.0 etc make sure they're all stopped, reboot and try again.

**Comment by basil00** [comment]
The `windivertctl.exe uninstall` command should print `UNINSTALL WinDivert` or an error message.

Your registry might be corrupted.  Check the entry `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert`.  I'm not sure if manually deleting the entry is good advice, but something like that might be necessary.

**Comment by muse117** [comment]
> The `windivertctl.exe uninstall` command should print `UNINSTALL WinDivert` or an error message.
> 
> Your registry might be corrupted. Check the entry `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert`. I'm not sure if manually deleting the entry is good advice, but something like that might be necessary.

Great! I  delete the entry and reboot. It is good!
