### ISSUE TITLE
windivert 2.0 ## failed to open the WinDivert device (577) on win2008 R2(x64)

### ISSUE THREAD

**Issue by muse117** [basil00/Divert#178]
This error appears in the V2.0，The V1.4.3 is ok on win2008 R2

![微信截图_20190412153811](https://user-images.githubusercontent.com/9733486/56020166-1c403600-5d39-11e9-9e25-a64dbd0804a7.png)

**Comment by basil00** [comment]
That error code is `ERROR_INVALID_IMAGE_HASH`.  This error occurs in out-of-date versions Windows 2008 that only accept SHA1 signatures.  The `A` variant uses a SHA256 signature.

The `C` variant includes a SHA1 signature so may work, but I cannot be sure.

**Comment by muse117** [comment]
> That error code is `ERROR_INVALID_IMAGE_HASH`. This error occurs in out-of-date versions Windows 2008 that only accept SHA1 signatures. The `A` variant uses a SHA256 signature.
> 
> The `C` variant includes a SHA1 signature so may work, but I cannot be sure.

The B and C variant is also error, The 'A' is good on the win2008(no-R2), but, on the win2008 R2 is error. Whether can have general signature?
 
![微信截图_20190413201629](https://user-images.githubusercontent.com/9733486/56079581-64d71c80-5e29-11e9-8d59-13879322ff51.png)

**Comment by basil00** [comment]
Don't forget to run `sc stop windivert` between tests.

The C-variant has a SHA1 signature so in theory should work on all Windows, including unpatched Windows 7, 2008, etc.  I have not tested it though, since patched Windows should accept SHA2 signatures.

You really ought to run windows update else the entire system is vulnerable anyway.  If not, then you at least need to install KB4039648.

**Comment by muse117** [comment]
> Don't forget to run `sc stop windivert` between tests.
> 
> The C-variant has a SHA1 signature so in theory should work on all Windows, including unpatched Windows 7, 2008, etc. I have not tested it though, since patched Windows should accept SHA2 signatures.
> 
> You really ought to run windows update else the entire system is vulnerable anyway. If not, then you at least need to install KB4039648.

I patch KB4474419 to win2008-R2, The B-variant is good, Is it SHA-2? but, The C-variant is still error.

**Comment by basil00** [comment]
Perhaps the SHA1 signature is invalid.  I might remove it in future releases, and just rely on Windows 7/2008 users installing the correct patches.  Support for these older versions of Windows will be dropped soon anyway.

**Comment by muse117** [comment]
> Perhaps the SHA1 signature is invalid. I might remove it in future releases, and just rely on Windows 7/2008 users installing the correct patches. Support for these older versions of Windows will be dropped soon anyway.

The win7/2008 is not support for sha256 signatrue? So, Don't use the A-variant?

**Comment by basil00** [comment]
All of A/B/C use SHA2.  The C also has an additional SHA1.  Win7/2008 don't support SHA2 unless patched.

**Comment by Shuchang1993** [comment]
I encountered the same problem (windows7), installed KB, but A / B / C could not open windivert，I want to ask how to solve it？thanks

**Comment by basil00** [comment]
> I encountered the same problem (windows7), installed KB, but A / B / C could not open windivert，I want to ask how to solve it？thanks

Try this version: https://reqrypt.org/download/WinDivert-2.2.0-D.zip

**Comment by Shuchang1993** [comment]
> > I encountered the same problem (windows7), installed KB, but A / B / C could not open windivert，I want to ask how to solve it？thanks
> 
> Try this version: https://reqrypt.org/download/WinDivert-2.2.0-D.zip

I tried the new version and still had the same problem. I guess this is not compatible with windows7, can you tell me the version of win7 you tested?

**Comment by basil00** [comment]
You should retry after reboot.  WinDivert is compatible with Windows 7, but only if it is up-to-date.

**Comment by pol4bear** [comment]
I'm having same problem in Windows 10 version 1903 with WinDivert 2.2.0. I first cloned from github and build myself but WinDivertOpen were keep failing with error 577. Andthan I downloaded WinDivert-2.2.0-A, WinDivert-2.2.0-B, WinDivert-2.2.0-C but it won't work neither. I did everything I can but I couldn't fix. I tried with version 1.4.3 it's working well. Maybe Version > 2.0 has some flaws.

**Comment by basil00** [comment]
If you built your own driver then you need to sign it else it will fail with error 577 (`ERROR_INVALID_IMAGE_HASH`).  This is to be expected.

To fix the error, it is necessary to delete the old WinDivert service, else it will try to reuse the old service with the driver with the invalid signature.  The solution is already in the posts above: reboot and try again, or issue `sc stop windivert` from a command prompt.
