### ISSUE TITLE
unclear doc about "out-of-order" packets

### ISSUE THREAD

**Issue by TehRick** [basil00/Divert#180]
Hi, In the docs "passthru.exe" is used as an example of use that could make packets out-of-order.
It is understandable as the overlapped I/O ops don't provide guarantee of order. So the doc leaves me wondering about whether or not packets can appear out-of-order in other use cases such as non-"Ex-" functions and fence'd "Ex-" functions (calling again only after completion) ?
If the answer is yes, are batches subject to the same issue and are timestamps of any help ?

**Comment by basil00** [comment]
I think for single-threaded and non-overlapped i/o the order might be preserved.  I don't think batching affects the order either.  I'm not 100% sure as this would require analyzing the code.

The timestamp records when the packet was first seen by WinDivert, so could be of help.  Although, it is possible for several different packets to get the same timestamp.
