### ISSUE TITLE
build error in x86 Free Build Environment

### ISSUE THREAD

**Issue by Bo3o2S** [basil00/Divert#181]
when i build x86 windivert with wddk-build.bat, build error in x86 Free Build Environment.(WDK 7.1.0). first time i think it caused by OS version. but another OS also get same error.

x64 works fine. i don't know why it is happen. please help me!

TEST Environment
OS : Windows 10 64bit, Windows 10 32bit, Windows 7 32bit
WDK : 7.1.0
Build Target : x86

![image](https://user-images.githubusercontent.com/14229134/56705380-99ad7280-674b-11e9-8df4-905ec093cfef.png)

**Comment by basil00** [comment]
I was unable to reproduce this issue and it compiled fine for me (wdk7.1 x86 free win10).  What are the errors exactly?

**Comment by basil00** [comment]
No response so closed.
