### ISSUE TITLE
Doesn't work for WiFi hotspot

### ISSUE THREAD

**Issue by viccon** [basil00/Divert#182]
1. Run WinDivert on Windows 10, and enable WiFi hotspot
2. Connect your mobile phone to that WiFi hotspot
3. All the traffic sent to your mobile phone doesn't seem to be changed by the WinDivert rules

**Comment by basil00** [comment]
For this you need to use the `NETWORK_FORWARD` layer.  Basically, the `NETWORK` layer only captures packets to/from the local machine, and the `NETWORK_FORWARD` layer is for packets passing through the local machine that is acting as a router.
