### ISSUE TITLE
[doc] please add the int number in the document for WINDIVERT_PARAM_VERSION_MAJOR

### ISSUE THREAD

**Issue by bronze1man** [basil00/Divert#185]
Please add the int number in the document for WINDIVERT_PARAM_VERSION_MAJOR or other const int 
I just use golang to call the function in the dll of Divert directly.
Put the int number in the document can make me write code faster.(So I do not need to read the .h file again and again)

**Comment by basil00** [comment]
You mean the value of the `WINDIVERT_PARAM_VERSION_MAJOR` macro itself, or the value returned by the `WinDivertGetParam`?  For the latter, it depends on the version of the driver that happens to be running.  Currently, this can only be version 2, but later this may change.

**Comment by bronze1man** [comment]
I mean the value of the WINDIVERT_PARAM_VERSION_MAJOR macro itself.

**Comment by basil00** [comment]
For the constant values you really ought to use the header file.  Although probably unlikely, the values of these constants could change in future versions.
