### ISSUE TITLE
How do I know the exact version or git commit from my binary file of winDivert.dll/winDivert32.sys? 

### ISSUE THREAD

**Issue by bronze1man** [basil00/Divert#186]
I have three sets winDivert32.dll/winDivert32.sys/winDivert64.dll/winDivert64.sys in my application source file, but I do not know the exact version.
From the caller code of winDivert.dll, it is not the version 1.4.3 or version 2.0.0rc, I can find some abi that is not match.

I also have one win7 machine, can only use those old version of winDivert, new version will get:
```
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
```

We also have some users can not use the win7 working old version of winDivert, So looks like we need support both version and try and switch at runtime.

**Comment by basil00** [comment]
There is no official support for applications wanting to use multiple versions of WinDivert.  You could do it by putting the different versions in different directories, then use `SetCurrentDirectory` before `WinDivertOpen`.

**Comment by bronze1man** [comment]
> You could do it by putting the different versions in different directories

I already did that, LoadLibraryW is working when I pass in the full path of the dll file.And put xxx.sys in the same directories with the dll.
But I can not find the exact document/.h file of every my exist/working dll file. I think I may miss using some of it, i need to check it with the document.
After I dig something, i find the dll file have a timestamp, and I can redownload all your binary files and check the md5sum of the file to find the exact version of it.

**Comment by bronze1man** [comment]
md5 of all pre-built winDivert dll sys exe from https://reqrypt.org/download/ right now:
https://gist.github.com/bronze1man/b4a1cbcc22ad20b799437c296018e8c9

**Comment by basil00** [comment]
I'm not sure of the problem.  Can't you just get the header files for each version here?
 https://github.com/basil00/Divert/releases
