### ISSUE TITLE
[doc] please add information about which version Introduce ABI break compatible in CHANGELOG

### ISSUE THREAD

**Issue by bronze1man** [basil00/Divert#187]
I found that I need support WinDivert version 1.1.8 and version 1.4.0-rc and version 1.4.3 in my program, and switch them in the runtime.
I notice that version 1.1.8 and  version 1.4.3 have one ABI break compatible:
```
version 1.1
==============

typedef struct
{
    UINT32 IfIdx;
    UINT32 SubIfIdx;
    UINT8  Direction;
} WINDIVERT_ADDRESS, *PWINDIVERT_ADDRESS;


version 1.4
===============

typedef struct
{
    INT64  Timestamp;
    UINT32 IfIdx;
    UINT32 SubIfIdx;
    UINT8  Direction:1;
    UINT8  Loopback:1;
    UINT8  Impostor:1;
    UINT8  PseudoIPChecksum:1;
    UINT8  PseudoTCPChecksum:1;
    UINT8  PseudoUDPChecksum:1;
} WINDIVERT_ADDRESS, *PWINDIVERT_ADDRESS;
```
I read the CHANGELOG, looks like the WINDIVERT_ADDRESS change is the only one ABI break compatible in Introduce in 1.4.0-rc.
Please document all of the ABI break compatible between those version and confirm that.
I do not need to support 2.0.0-rc right now, I notice there is a lot ABI break compatible duration 2.0.0-rc and 1.4.3.

I can not skip the WinDivert version 1.1.8, because it is the version that works on my windows7 machine. other newer version do not work.Those newer version always get error:
```
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
```

I also have tried to buy a certification and sign the .sys file myself, and I will get the same error again.(The .sys file works on newer win10 machine).
It looks like Microsoft do not allow me to sign the .sys file to works on that old windows7 machine any more.

**Comment by basil00** [comment]
The newer drivers use SHA2 signatures, whereas older versions of Windows 7 only use SHA1.  If you update Windows 7 the newer SHA2 signatures should be supported.

You really ought not to be using version 1.4.1 or older.  These older versions have known bugs.

As for API breaks, basically every minor version breaks the API, so 1.1, 1.2, 1.3, 1.4, 2.0 are all incompatible.  For 1.X most changes are minor, but 2.0 is a major update.  I can't remember the exact changes, but the intention was that only a single copy of the library would be used by the application.  Really the only way to be sure is to study the documentation for each version.  Moving forward, I hope that future versions of WinDivert are more compatible with each other.

**Comment by IAOTW** [comment]
https://www.microsoft.com/zh-CN/download/confirmation.aspx?id=46148
you can update the KB3033929 to fix it
