### ISSUE TITLE
Please document winDivert2.0 WINDIVERT_DATA_FLOW.LocalAddr binary format.

### ISSUE THREAD

**Issue by bronze1man** [basil00/Divert#189]
I do not understand the exact format of WINDIVERT_DATA_FLOW.LocalAddr. Some example of ip encode will be better.
After try and guess, I find the correct function to parse it into golang net.IP , it may help others.
```go
func parseAddressIp(addr []uint32) net.IP{
	ip:=make(net.IP,16)
	for i:=0;i<4;i++{
		b:=addr[3-i]
		binary.BigEndian.PutUint32([]byte(ip[4*i:]),b)
	}
	return ip
}
```

**Comment by basil00** [comment]
It's just the IPv6 address in host-byte ordering, as are all fields in the `addr` structure.  This is the same as network byte ordering, except with the order of the 16 bytes reversed.  You can use `WinDivertHelperHtonIpv6Address` to convert an IPv6 address to network byte ordering.

Traditionally IPv6 addresses are *always* stored in network byte ordering.  However, this made the WinDivert API inconsistent so it was decided to ignore that rule.
