### ISSUE TITLE
support for SCTP capture

### ISSUE THREAD

**Issue by sgf** [basil00/Divert#190]
support for SCTP (Stream Control Transmission Protocol) capture

i want to send and receive sctp packet
is there any way to do that directly,without capture the IP packet on lower Layer ?

**Comment by basil00** [comment]
Currently WinDivert can only capture packets at the IP layer, including SCTP.

**Comment by sgf** [comment]
thank you,it seems only capture SCTP with IPPacket

**Comment by sgf** [comment]
> Currently WinDivert can only capture packets at the IP layer, including SCTP.

If possible, in the future, still hope to be able to add SCTP-Header filtering support in Filter-Language. This allows we to pass through the SCTP. DestPort filtering to avoid sending all the same IP packets to the user problem from Driver Layer.
