### ISSUE TITLE
Odd behaviour with fragments.

### ISSUE THREAD

**Issue by majibow** [basil00/Divert#191]
The following relates to 1.4.3 on Windows 10. I haven't tested other combinations.   
 
1. Is it expected that WinDivert capture fragments and then also capture the reassembled packet?

This is very easy to test just use ping and set a size bigger than the mtu e.g. 1600. This should be executed from another machine so fragments are generated as WinDivert will just capture a single large packet on the local host.  

2. Also very odd the netdump.exe example also captures the fragements twice before capturing the reassembled packet. Perhaps something to do with sniff mode?

3. Also the maximum packet buffer size for IPv6 is 65535+40, while for IPv4 is just 65535. Which puts some of the example programs at risk such as netdump.exe and passthru.exe if capturing reassembled packets.

Anyway the reason I am reporting this is I just find it weird... two passes are made over the same packet essentially (first is just cut into pieces and second is assembled for you but why would anyone want both?). However in the outgoing direction we only see the fully assembled large packet (same as on local host). Perhaps WinDivert should only show assembled packets or fragments? Yes I know you can filter IPv4 fragments with "ip.MF=0 and ip.FragOff=0", but what about IPv6? The best I've got for that is "ipv6.NextHdr!=44" but it doesn't work if there are multiple extension headers and something comes before fragment.

What I'm suggesting is WinDivert capture only either fragments if present or only non fragments either is fine but both is weird. I vote for the latter, what would anyone do with only a faction of a packet?

**Comment by basil00** [comment]
> Is it expected that WinDivert capture fragments and then also capture the reassembled packet?

This is the default WFP behavior which WinDivert inherits.

In fact, I haven't thought that much about it.  Perhaps only one of the fragment(s) or the reassembled packet should be captured?  It could be determined by the `FWP_CONDITION_FLAG_IS_FRAGMENT` flag.

> Also the maximum packet buffer size for IPv6 is 65535+40, while for IPv4 is just 65535.

This bug was fixed in version 2.0.0.

**Comment by majibow** [comment]
Yep we are thinking on the same lines. User selectable behaviour is best but I would settle for one type if its too much effort.

In relation to point (2) see https://social.msdn.microsoft.com/Forums/vstudio/en-US/75d14b9e-9550-4e2c-9113-847b193d9e3a/receiving-fragments-twice?forum=wfp
I'm not sure exactly if that will help. 

In relation to point (3): fixed? how so? 
Looking at the master branch for netdump.exe MAXBUFF is only 65535 (needs 40 more) and hence netdump.exe fails to capture the packet for ping -6 -l 65488 google.com... but 65547 is fine.  
When I tried "passthru.exe true 1 255" it also fails on the same boundary condition 65547-65548 pinging the local machine externally.

**Comment by basil00** [comment]
> In relation to point (3): fixed? how so?

It was fixed in the driver which previously enforced a 65535 limit.  It seems the sample programs were not fixed, so this will need to be updated later.

**Comment by basil00** [comment]
This issue is fixed using the new `WINDIVERT_FLAG_FRAGMENTS` flag.  If set, the handle will capture inbound IP fragments, but not inbound reassembled IP packets.  Otherwise, if not set (the default), the handle will capture inbound reassembled IP packets, but not inbound IP fragments.

This flag only affects inbound packets at the `WINDIVERT_LAYER_NETWORK` layer.  Outbound and forward IP fragments are captured as before.

> Also very odd the netdump.exe example also captures the fragements twice before capturing the reassembled packet.

It turns out this is the default WFP behaviour.  The inbound fragment is captured once as (1) a raw IP packet, (2) as an IP fragment, and (3) as part of the reassembled packet.  The difference between (1) and (2) is that the latter has been verified as a valid fragment.  For technical reasons, if `WINDIVERT_FLAG_FRAGMENTS` is set, WinDivert only captures (1) but never (2).
