### ISSUE TITLE
binary packages (version 2.0) don't work on win 10

### ISSUE THREAD

**Issue by pablozzz** [basil00/Divert#194]
Hi, basil00, great thanks for your job!

I've download binaries (2.0 A & B & C), but unfortunately, all examples show error on my win10x64:

"error: failed to open the WinDivert device (2)" when I execute it (test.exe, netdump.exe, etc).

I saw your manual for this error: "The driver files WinDivert32.sys or WinDivert64.sys were not found." But both requirement files there are.

On another side version, 1.4.3 works fine on that machine

**Comment by basil00** [comment]
Probably the same issue as #177.  Try deleting the service from the registry and rebooting.

**Comment by pablozzz** [comment]
> Probably the same issue as #177. Try deleting the service from the registry and rebooting.

OMG It helped. Thanks a lot and I'm sorry that I re-initiated the same issue again.
