### ISSUE TITLE
WinDiver Split VPN connection issue

### ISSUE THREAD

**Issue by pablozzz** [basil00/Divert#195]
Hi @basil00, I need your help with one question

I've used WinDivert for VPN connection splitting:

I have one application on my Win10 machine which works with my remote server 
and I would like to connect it bypass VPN connection

My main idea is 
1. Use WinDivert to receive packages my machine <-> remote server filtered by IP.
2. If package is outbound change ip_header->SrcAddr to my local network adaper IP instead VPN adapter(for example if ip_header->SrcAddr == 10.0.0.1 I set ip_header->SrcAddr to 192.168.1.3)
3. If package is inbound change ip_header->DstAddr to my local network adaper IP instead VPN adapter(for example if ip_header->DstAddr == 10.0.0.1 I set ip_header->DstAddt to 192.168.1.3)
4. Then re-inject packages to network with changed addresses

All these steps work fine without any errors with WinDiver 2.0
If I use WinDiver v 1.4.3 and add flag "WINDIVERT_FLAG_DEBUG" I got the error (1168) on re-injection step.

BUT in both cases, my application doesn't work with a remote server. When I look in Wireshark to debugging I see that my PC doesn't send outbound packages for some reason.

I see only these packages:

11139    69.786465    86.xxx.xxx.155    192.168.1.3    TCP    54    [TCP Retransmission] 8080 → 6255 [FIN, ACK] Seq=3846 Ack=1682 Win=33664 Len=0

Where 86.xxx.xxx.155 - is my server IP

So how do think what could be the reason of issue? 
And is it possible to using  WinDiver to bypass VPN connection by target IP or my idea is wrong?

**Comment by basil00** [comment]
First try debugging using `netdump` to see if the injected packets are visible to WinDivert.

**Comment by basil00** [comment]
No reply so closed.
