### ISSUE TITLE
Transport Layer Packet Injection

### ISSUE THREAD

**Issue by 2yangk23** [basil00/Divert#197]
Hi, I am curious whether there is any plan to add support for packet injection at the transport layer. I have been doing some research about how it would work at the network layer, and there seems to be a lot of variables that would need to be handled.

I am trying to inject packets into an existing TCP connection without disruption. The connection should continue even after the packet is injected. Since the transport layer would be unaware of this new data, my understanding is that I would need to handle the following:
- Modifying seq/ack numbers to account for the additional data injected
- Handling retransmission of injected data
- Reordering packets

This work could all be abstracted if injection could be done at a higher level. Thanks!

**Comment by basil00** [comment]
Injecting into a TCP stream at the network layer is very difficult, so it is generally better to redirect the stream to a local proxy to do the modifications.  The `streamdump` sample does something like this. (Although it currently does not do modification, it could be modified to do so).

A future WinDivert 3.0 release may support a direct stream injection layer.  This is something I want but It depends on the feasibility of the implementation.

**Comment by cnlh** [comment]
@basil00 is there plan to 3.0？
