### ISSUE TITLE
[Feature request] Provide an installer

### ISSUE THREAD

**Issue by gpotter2** [basil00/Divert#198]
Hi,

Would it be possible to have an Installer for Windivert ? Something similar to what `Winpcap` used to do (and now what `Npcap` does), or what `UsbPcap` do (among other famous Windows adapters).

Those other installers copy the binaries to a path (`C:/Windows/system32/Npcap` or `C:\Program Files\USBPcap`) where it's easy for other programs to import it.

This avoids duplication of the same tool in different versions among different software, but also allows us not to pack the binaries ourselves, and rather link to a potential install page provided by Windivert.

**Comment by basil00** [comment]
The problem is that there are many incompatible versions of WinDivert and the API is still in a high state of flux.  Maybe things will eventually settle down making this model viable.

The WinDivert binaries are very small meaning the duplication overhead is mitigated anyway.

**Comment by gpotter2** [comment]
Thanks for the info
