### ISSUE TITLE
add tcp payload

### ISSUE THREAD

**Issue by honor2030** [basil00/Divert#199]
i'm trying to add tcp payload.

WinDivertRecv, WinDivertHelperParsePacket working well,

but when i add some payload infront of  ppData(original data) field from WinDivertHelperParsePacket, it was added, but back of original data was cut, amount of added data.
i tried to modify data length, and packet length which is get from WinDivertHelperParsePacket, but it is always same.

somebody tell me how can i add payload to original tcp payload?

**Comment by basil00** [comment]
> somebody tell me how can i add payload to original tcp payload?

It is not practical to do this at the packet level.  You need to redirect the flow to a proxy and modify the stream from there, e.g., using something like the `streamdump.exe` sample program.
