### ISSUE TITLE
Syntax Errors and NMAKE Fatal Error U1073 on x86 Free Build Environment

### ISSUE THREAD

**Issue by kfreezen** [basil00/Divert#200]
I'm experiencing the same issue as #181 on Windows 10.

Not sure what's going on, but x64 compiles perfectly, while x86 spews syntax errors and an NMAKE error. Following is snipped from attached log
```
1>e:\code\windivert\sys\windivert.c(359) : error C2061: syntax error : identifier 'windivert_decrement_ttl'
1>e:\code\windivert\sys\windivert.c(359) : error C2059: syntax error : ';'
1>e:\code\windivert\sys\windivert.c(359) : error C2059: syntax error : ';'
1>e:\code\windivert\sys\windivert.c(359) : error C2059: syntax error : 'type'
1>e:\code\windivert\sys\windivert.c(359) : error C2059: syntax error : 'type'
1>e:\code\windivert\sys\windivert.c(362) : error C2061: syntax error : identifier 'windivert_filter'
1>e:\code\windivert\sys\windivert.c(362) : error C2061: syntax error : identifier 'windivert_filter'
1>e:\code\windivert\sys\windivert.c(362) : fatal error C1003: error count exceeds 100; stopping compilation
1>e:\code\windivert\sys\windivert.c(362) : error C1003: error count exceeds 100; stopping compilation
1>NMAKE : fatal error U1073: don't know how to make 'c:\winddk\7600.16385.1\lib\wxp\i386\fwpkclnt.lib'
1>NMAKE : fatal error U1073: don't know how to make 'c:\winddk\7600.16385.1\lib\wxp\i386\fwpkclnt.lib'
1>Stop.
1>nmake.exe /nologo BUILDMSG=Stop. -i BUILD_PASS=PASS2 LINKONLY=1 NOPASS0=1 MAKEDIR_RELATIVE_TO_BASEDIR= failed - rc = 2
```

If I edit the `sys/sources` file to set `_NT_TARGET_VERSION` to `$(_NT_TARGET_VERSION_WIN7)`, the syntax errors go away, but the NMAKE error remains.

Do you have any ideas about why I'm getting this error when building the driver?

OS: Windows 10
WDK Ver: 7.1
Env: x86 Free Build Environment

This error occurs on the `v1.4.3` tag.

Thanks in advance for your help.

[buildfre_wxp_x86.log](https://github.com/basil00/Divert/files/3432111/buildfre_wxp_x86.log)

**Comment by basil00** [comment]
The only thing I can think of is if the WDK installation is somehow incomplete (maybe possible for "custom" installations?).

Otherwise, as per #181, the x86 build works fine for me, at least the last time I tried it.

Also, WinDivert 1.4.3 is out-of-date and the build system has now switched to Visual Studio.  The old build system is no longer "officially" supported.
