### ISSUE TITLE
How to drop an ACK Packet in TCP connection 

### ISSUE THREAD

**Issue by helloTkk** [basil00/Divert#204]
Hi,
I'm doing a project on Retransmission Steganography. I need to drop a captured ACK packet to let the sender retransmit. I write the code. but can't understand why this is not working. I made the connection and capturing packet with SharpPcap(c#) and use WinDivert for packet dropping(visual c++).now i find the problem is that my dropcode enters to an invalid handle exception.i use GetLastError() to know why this is happening. but doesn't show anything.program stops here.so i actualy don't understand what's the problem. should i need to pass some parameters to the code?

Here is my code:

capture packet code:
static void device_OnPaketArrival(object sender, CaptureEventArgs e)
{
Packet packet = Packet.ParsePacket(e.Packet.LinkLayerType, e.Packet.Data);
var tcpPacket = TcpPacket.GetEncapsulated(packet);
if (tcpPacket != null)
{
String SPort = tcpPacket.SourcePort.ToString();
var DPort = tcpPacket.DestinationPort.ToString();
var Data = Encoding.Unicode.GetString(tcpPacket.PayloadData); //Encoding.ASCII.GetString(tcpPacket.PayloadData).ToString();
var ack = tcpPacket.Ack.ToString();
if (OptionTCP.UnsafeCompareByte(tcpPacket.PayloadData, KeyWord))
{ 
try
{
System.Diagnostics.Process proc = new System.Diagnostics.Process();
proc.StartInfo.FileName = "\"F:\\c#project\\serversteg\\Debug\\dropTcpPacket.exe\"";
proc.Start();
}
catch (Exception exp)
{
Console.WriteLine("errro .. {0}", exp.ToString());
}
}
else
{
Console.WriteLine("nnnnnnnnoo: {0}", Encoding.Unicode.GetString(KeyWord));

Console.WriteLine("Sport: {0}, DPort: {1}, Ack:{2} Data: {3}", SPort, DPort, ack, Data);
Console.WriteLine("==========================================================");
}

} 
 
DropTcpPacket code:
#include "stdafx.h"
#include <winsock2.h>
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "windivert.h"

#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "WinDivert.lib")

#define MAXBUF 0xFFFF 
#define BUFSTEG 13

typedef struct
{
WINDIVERT_IPHDR ip;
WINDIVERT_TCPHDR tcp;
} TCPPACKET, *PTCPPACKET;

int _tmain(int argc, _TCHAR* argv[]){

HANDLE handle; 
WINDIVERT_ADDRESS addr; 
char packet[MAXBUF]; 
UINT packetLen; 
int countCapture = 0;
PWINDIVERT_TCPHDR tcp_header;

//int countCapture = srand(time(NULL)) % 4;
srand(time(NULL));
countCapture = rand()%4;

if (argv[0] == NULL){
printf("no prb");
fprintf(stderr, "get parametrs..\n"); 
exit(2);
}

handle = WinDivertOpen("tcp.SrcPort==1786", 0 , 0, 0); \\1786 is the port from where the connection made.

if (handle == INVALID_HANDLE_VALUE)
{
printf("%s\n",GetLastError());\\The program aborts here.
exit(1);
}
while (countCapture != 0)
{
if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
{
printf("%s\n",GetLastError());
continue;
}
else {
WinDivertHelperParsePacket(packet, packetLen, NULL,NULL, NULL, NULL, &tcp_header,NULL, NULL, NULL);
printf("SrcPort = %u\t DstPort = %u\t AckNum = %u\t \n ================================================\n ",
ntohs(tcp_header->SrcPort), ntohs(tcp_header->DstPort), ntohl(tcp_header->AckNum));
// printf("%s\n", );
countCapture -= 1;
}

}

}

 thanks in advance

**Comment by helloTkk** [comment]
Should i pass the ip address as input parameters in the dropcode?

**Comment by basil00** [comment]
> .i use GetLastError() to know why this is happening. but doesn't show anything.

That's because you are trying to use `%s` to print an integer, try `%d`.

**Comment by helloTkk** [comment]
> > .i use GetLastError() to know why this is happening. but doesn't show anything.
> 
> That's because you are trying to use `%s` to print an integer, try `%d`.
Ok, thank U, but i still have a problem that should i pass the ip address as input parameters in the dropcode? if need,how to do?

**Comment by basil00** [comment]
Sorry for the late reply.
The filter just determines what traffic is sent to `WinDivertRecv`.  So if you only want to see packets to a specific ip address then you can include it in the filter sting, else you do not.

Also, glancing at your code, it is unclear what it intends to do.  Currently it seems to just capture *all* packets with source port 1786, not just ACKs.  Since the packets are captured, printed, and never reinjected meaning they are effectively dropped.  If you just want to drop specific ACKs, then this can be easily done with WinDivert directly, without the need for the PCAP component.
