### ISSUE TITLE
I find trojan horse 

### ISSUE THREAD

**Issue by lsalamon** [basil00/Divert#205]
In link "https://reqrypt.org/download/WinDivert-2.1.0-A.zip" McAfee find "Artemis!04A5C6B43ACA" trojan horse at zip.

what is going on?

**Comment by basil00** [comment]
I am not sure.  I've double checked and the link and server show the correct version for `WinDivert-2.1.0-A.zip`:

* `MD5 6095abecc386f202bc06e5a0e9fcfc17`
* `SHA256 313648e87c4e87386a287f9bf46c4fbe4eec4c00cae152acd160f73258783a39`

Possibly your anti-virus is misclassifying the WinDivert as malware/trojan? You need to contact them to complain about a misclassification.

Unfortunately some lazy/incompetent AV products do misclassify WinDivert.
