### ISSUE TITLE
Is it possible implement NAT function like Linux netfilter?

### ISSUE THREAD

**Issue by jack2007** [basil00/Divert#207]
Hi sir,
Windivert is great after I try it to implement a NAT function. And I notice that for changing some attributes of packets, I need capture the packet to userspace and reinject it after modify packet. 
Is it possible to implement it as Linux netfilter that we send some rules to kernel and kernel modify the packet without passing the packets to userland and back again. This may save a lot CPU work.
Best wishes.

**Comment by basil00** [comment]
Thanks for your feature request.  Perhaps one day something like this can be added, this is unlikely to happen in the near term.  Adding some kind of in-kernel packet to WinDivert would require a big design rethink.
