### ISSUE TITLE
"failed to parse packet (0)" errors while using streamdump.exe

### ISSUE THREAD

**Issue by vincenthawke** [basil00/Divert#209]
I tested the already compiled streamdump.exe program to redirect traffic to local proxy.
I suspected it could be an issue of it not handling HTTPS but if I visited http website, I didn't see any new console output messages. Command line was launched with administrative privileges. The timing of these messages seems off as well, as they don't pop consistently while browsing websites.  OS: Windows 10, WinDivert version: 2.1.

**Comment by basil00** [comment]
I tested the latest version (2.2 source) and did not notice any error.  It is possible that the issue has been fixed since the packet parser has been rewritten.

**Comment by vincenthawke** [comment]
Looking forward testing it. When do you think 2.2 it will be uploaded?

**Comment by basil00** [comment]
It should be ready soonish, depending on when/if I can get the drivers signed.

**Comment by vincenthawke** [comment]
I noticed you updated the changelog to WinDivert 2.2.0, but the pre-built files on the website are still marked as "WinDivert-2.1.0-A.zip". Could you please upload the 2.2.0 build as well? Many thanks!

**Comment by basil00** [comment]
Version 2.2 is complete pending testing, which should be complete in a day or two.  Hopefully I can wrap it up and release soon, depending on when/if we can get the new drivers signed.

**Comment by mynuolr** [comment]
I use Golang to bind DLL. I think there's something wrong with WinDivertHelperParsePacket
![PN)E2O%_6ZF1EV OL4GDI](https://user-images.githubusercontent.com/3831242/66841714-b5782f80-ef9c-11e9-9294-75fd74ad082f.png)

**Comment by basil00** [comment]
> I think there's something wrong with WinDivertHelperParsePacket

Versions 2.1 and 2.2 both parse your packet as follows:

    IPv4 [Version=4 HdrLength=5 TOS=0 Length=40 Id=0x78B2 Reserved=0 DF=1 MF=0 FragOff=0 TTL=128 Protocol=6 Checksum=0x0000 SrcAddr=192.168.1.153 DstAddr=149.129.118.207]
    TCP [SrcPort=9655 DstPort=56 SeqNum=1849313315 AckNum=1509779343 HdrLength=5 Reserved1=0 Reserved2=0 Urg=0 Ack=1 Psh=0 Rst=0 Syn=0 Fin=0 Window=1026 Checksum=0x3F67 UrgPtr=0]

Is this incorrect?

**Comment by mynuolr** [comment]
> > I think there's something wrong with WinDivertHelperParsePacket
> 
> Versions 2.1 and 2.2 both parse your packet as follows:
> 
> ```
> IPv4 [Version=4 HdrLength=5 TOS=0 Length=40 Id=0x78B2 Reserved=0 DF=1 MF=0 FragOff=0 TTL=128 Protocol=6 Checksum=0x0000 SrcAddr=192.168.1.153 DstAddr=149.129.118.207]
> TCP [SrcPort=9655 DstPort=56 SeqNum=1849313315 AckNum=1509779343 HdrLength=5 Reserved1=0 Reserved2=0 Urg=0 Ack=1 Psh=0 Rst=0 Syn=0 Fin=0 Window=1026 Checksum=0x3F67 UrgPtr=0]
> ```
> 
> Is this incorrect?

Maybe it's my problem

**Comment by basil00** [comment]
WinDivert version 2.2.0 is finally available: https://github.com/basil00/Divert/releases/tag/v2.2.0
