### ISSUE TITLE
ProcessId at NETWORK layer

### ISSUE THREAD

**Issue by hzsoft312** [basil00/Divert#212]
Great work you'v done! So many thanks.

I wonder if I can build a map of ProcessID to 5-tuple(protocal, source ip, source port, dest ip, dest port) with a open Windivert handle at SOCKET layer and use this map with another open Windivert handle at NETWORK layer to filter/block/reject packets. 

Is that possible? I can think of 2 potential problems:
1. I have to open 2 Windivert handles of different layers in the same user application.
2. for one specified socket, which layer will receive the events first? Cause I need to build the map first and use it in NETWORK layer.

Thanks. 

Also on StackOverflow: https://stackoverflow.com/questions/58449491/windivert-processid-at-network-layer

**Comment by basil00** [comment]
I posted an answer on StackOverflow here: https://stackoverflow.com/a/58469373/1041139

In summary, (1) yes you need two WinDivert handles (`SOCKET` and `NETWORK`), and (2) no you cannot know which event will arrive first.  For (2) the user application can internally queue events until both arrive before taking action.  This is what [Tallow](https://github.com/basil00/TorWall) does to solve this issue.
