### ISSUE TITLE
Shouldn't EVENT_SOCKET_CONNECT in LAYER_SOCKET be correspond to ‘connect()’ on a socket?

### ISSUE THREAD

**Issue by xyzkljl1** [basil00/Divert#213]
ver2.2.0.
I'm using winsock2 in c++.I notice that 'WINDIVERT_EVENT_SOCKET_CONNECT' on 'WINDIVERT_LAYER_SOCKET' would be received when a tcp socket using ‘connect()’ or a udp socket using 'sendto()' to a new address first time.Maybe it's because that ‘AUTH_CONNECT’ in ALE layer contains both tcp's connect and udp's first send.(According to 'https://docs.microsoft.com/zh-cn/windows/win32/fwp/ale-layers#auth_connect' )

This is very convenient, but maybe a little ambiguous.A udp socket DOES have a ‘connect()’ funtion though it's not neccessary and not often used.'https://reqrypt.org/windivert-doc.html#divert_events' chapter 5.2 also says 'WINDIVERT_EVENT_SOCKET_CONNECT' means 'A connect() operation'.
When i call ‘CONNECT’ on a  'SOCKET'，i may receive a 'SOCKET_CONNECT' event in 'SOCKET' layer ,or not.When i call 'sendto',i still may receive ‘SOCKET_CONNECT’,or not.That's a little confusing.

Do you consider ‘a socket_connect event actually means a ale layer connect event’ as a bug, or a feature?

**Comment by basil00** [comment]
Perhaps the documentation can be improved.  The `CONNECT` event corresponds to not only explicit `connect()` operations but also "implicit" connect operations such as the first packet of a UDP stream (or anything else that Windows indicates at the `AUTH_CONNECT` ALE layer).  This is similarly true for the `BIND`, `ACCEPT` and even `CLOSE` events I believe.

So the `SOCKET` layer is more low-level than the WinSock2 API.  It will indicate "implicit" events that do not correspond to an actual WinSock2 API call.
