### ISSUE TITLE
Cannot remove this program off my computer

### ISSUE THREAD

**Issue by pighog** [basil00/Divert#214]
This file ended up on my computer and there is no way to remove it. how do i get it off my computer

**Comment by basil00** [comment]
You mean the WinDivert driver files?  Windows will not let you delete them if they are being used some program.

To find you which program, you can try running [WinDivertTool](https://github.com/basil00/WinDivertTool) which can be downloaded from [here](https://github.com/basil00/WinDivertTool/releases).

You can also use WinDivertTool to forcibly uninstall the WinDivert driver by running the following from a command prompt:

    WinDivertTool.exe uninstall

This will terminate all programs using WinDivert and unload the WinDivert driver from Windows.  This will not delete the files which you still need to do yourself.

**Comment by pighog** [comment]
The WinDivertTool did not detect usage, yet the file still cannot be
deleted.
How do I run the WinDivertTool.exe uninstall on command prompt
I dont really know how this file got on my computer in the first place.
Thank you

**Comment by basil00** [comment]
> How do I run the WinDivertTool.exe uninstall on command prompt

Under _Run_ type `cmd` + _Enter_.  Then `cd` to the directory with `WinDivertTool.exe`, then run with the `uninstall` argument as shown above.  After that, try deleting the file.

If that does not work, try _Run_, `cmd` then right click for _Run as Administrator_.  Then `cd` to the relevant directory try deleting the WinDivert files using the `del` command.

> I dont really know how this file got on my computer in the first place.

I do not know either, a lot of projects use WinDivert.

**Comment by pighog** [comment]
I'm sorry but that is really advanced.
My windivert is on my hard drive, but my cmd is on my ssd drive

**Comment by basil00** [comment]
> I'm sorry but that is really advanced.

The instructions above should work.  Otherwise I cannot help.

The WinDivert files are just ordinary files.  The only reason why they cannot be deleted is if they are in use (locked by Windows), or the is some permission problem (requires Administrator).
