### ISSUE TITLE
build Error divert-2.2.0\sys\windivert.rc(38) : error RC1015: cannot open include file 'windivert_log.rc'.

### ISSUE THREAD

**Issue by luodaoyi** [basil00/Divert#215]
os:    windows10 x64 4903
SDK: wdk 7.1
vs:    visual studio 2019

But Not Found `windivert_log.rc` or `'windivert_log.h` in source code !

this is All logs:

```
BUILD: Compile and Link for x86
BUILD: Start time: Thu Oct 31 21:05:55 2019
BUILD: Examining c:\users\xxx\source\driver_develop\divert-2.2.0 directory tree for files to compile.
BUILD: Compiling c:\users\xxx\source\driver_develop\divert-2.2.0\sys directory
Configuring OACR for 'root:x86fre' - <OACR on>
_NT_TARGET_VERSION SET TO WINXP
Compiling resources - sys\windivert.rc
1>errors in directory c:\users\xxx\source\driver_develop\divert-2.2.0\sys
1>c:\users\xxx\source\driver_develop\divert-2.2.0\sys\windivert.rc(38) : error RC1015: cannot open include file 'windivert_log.rc'.
Compiling - sys\windivert.c
1>c:\users\xxx\source\driver_develop\divert-2.2.0\sys\windivert.c(46) : error C1083: Cannot open include file: 'windivert_log.h': No such file or directory
BUILD: Linking for c:\users\xxx\source\driver_develop\divert-2.2.0\sys directory
_NT_TARGET_VERSION SET TO WINXP
Compiling resources - sys\windivert.rc
1>c:\users\xxx\source\driver_develop\divert-2.2.0\sys\windivert.rc(38) : error RC1015: cannot open include file 'windivert_log.rc'.
Compiling - sys\windivert.c
1>c:\users\xxx\source\driver_develop\divert-2.2.0\sys\windivert.c(46) : error C1083: Cannot open include file: 'windivert_log.h': No such file or directory
1>NMAKE : fatal error U1073: don't know how to make 'c:\winddk\7600.16385.1\lib\wxp\i386\fwpkclnt.lib'
1>nmake.exe /nologo BUILDMSG=Stop. -i BUILD_PASS=PASS2 LINKONLY=1 NOPASS0=1 MAKEDIR_RELATIVE_TO_BASEDIR= failed - rc = 2

BUILD: Finish time: Thu Oct 31 21:05:55 2019
BUILD: Done

    8 files compiled - 4 Warnings - 6 Errors
```

**Comment by luodaoyi** [comment]
It's Windows10 x64 1903 !

**Comment by basil00** [comment]
Are you building using the `msvc-build.bat` script?  Also, I have not tried with VS2019.  The build system has only been tested with VS2015, although perhaps it should still work.

**Comment by luodaoyi** [comment]
msvc-build.bat also faild

**Comment by basil00** [comment]
Not sure what the problem is.  Is Windows Driver Kit installed?

The `windivert_log.rc` and `windivert_log.h` files should be automatically built from the `windivert_log.mc` file.  However, it appears this step is not working.  Perhaps the project files are not compatible with VS2019.

**Comment by luodaoyi** [comment]
I think the project files are not compatible with VS2019.

**Comment by kirubaKaranT** [comment]
anyone find the solution for it??

**Comment by kirubaKaranT** [comment]
<b>hello</b>

**Comment by kirubaKaranT** [comment]
<script>alert("hello");</script>

**Comment by Tenzor3** [comment]
> anyone find the solution for it??

Yep. I have successfully performed build using the latest SDK/WDK versions using Visual Studio 2019, not .bat file. Be sure that you have installed WDK and spectr migration. If you still have a problem please describe it more verbosely.

**Comment by kirubaKaranT** [comment]
i also  build the driver with vs2019 it will generate the .sys file  but i don't know how to generate lib file 
(i need it for user mode application ) if don't mind please help me

**Comment by xchangfeng** [comment]
The buliding process report an error:"But Not Found windivert_log.rc or 'windivert_log.h in source code !"

Since the Owner said:"The windivert_log.rc and windivert_log.h files should be automatically built from the windivert_log.mc file."

So I check the compile files and find in the sys/sources, it didn't include  windivert_log.mc file. That why this error shows.

Solution: Add windivert_log.mc to line 23 SOURCES.

change
```
SOURCES=windivert.rc windivert.c
```

to 

change
```
SOURCES=windivert_log.mc windivert.rc windivert.c
```

And it works.

**Comment by GrigLog** [comment]
> The buliding process report an error:"But Not Found windivert_log.rc or 'windivert_log.h in source code !"
> 
> Since the Owner said:"The windivert_log.rc and windivert_log.h files should be automatically built from the windivert_log.mc file."
> 
> So I check the compile files and find in the sys/sources, it didn't include windivert_log.mc file. That why this error shows.
> 
> Solution: Add windivert_log.mc to line 23 of file sys\SOURCES.
> 
> change
> 
> ```
> SOURCES=windivert.rc windivert.c
> ```
> 
> to
> 
> ```
> SOURCES=windivert_log.mc windivert.rc windivert.c
> ```
> 
> And it works.

I added windivert_log.mc to the SOURCES and, as I thought, the compilation crashes because of syntax errors (.mc files are not valid .c files)
