### ISSUE TITLE
Failed to open the WinDivert device (2) in Windows container

### ISSUE THREAD

**Issue by senweiliang** [basil00/Divert#217]
Hi, basil00, great thanks for your job!
I can't use Windivert in Windows container.
Things I have done:
1.Compile C code using dev-c++ into an .exe file on host.
2.`docker pull mcr.microsoft.com/windows:1903`
3.Run a Windows container
4.Use "docker cp" command to copy the executable file in step 1,WinDivert.dll(x64) and WinDivert64.sys into the container.
5.Enter in the container and run the C-program.This program just use WinDivertOpen() API and nothing else.But the handle is invalid and GetLastError() return error code(2).According to the manual,the program can't find WinDivert64.sys file.Why?
All files are in the same directory.The host and container are both x64-based.I also notice the issue #177.I enter the HKCU directory and can't find anything like `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert`.
I've tried Windivert 1.4,2.2 and the error still exists.

**Comment by basil00** [comment]
I am not if docker supports low-level drivers such as WinDivert.  What happens if you attempt to start WinDivert manually?

    sc create WinDivert binPath="WinDivert64.sys" type=kernel
    sc start WinDivert

**Comment by senweiliang** [comment]
Thanks for your reply!
After several attempts,I found that there are many factors influence the state of WinDivert service.If i run servercore:1903 as containter with `--isolation=process`,the result seems to be the best.The command and result are as follows:
`C:\Users\ABC>docker run -it --rm --isolation=process --name=server servercore:1903  cmd
Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.
(copy files intto container)
C:\>cd proxy_1.4

C:\proxy_1.4>dir
 Volume in drive C has no label.
 Volume Serial Number is B6F4-8052

 Directory of C:\proxy_1.4

11/13/2019  10:11 AM    <DIR>          .
11/13/2019  10:11 AM    <DIR>          ..
11/13/2019  10:10 AM               333 proxy.cpp
11/13/2019  10:11 AM         1,113,054 proxy.exe
07/03/2018  09:34 AM            23,552 WinDivert.dll
11/11/2019  03:01 PM            12,717 windivert.h
07/03/2018  09:34 AM            50,592 WinDivert64.sys
               5 File(s)      1,200,248 bytes
               2 Dir(s)  21,263,736,832 bytes free

C:\proxy_1.4>sc query WinDivert
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.


C:\proxy_1.4>proxy.exe
error open WinDivert device.(2)

C:\proxy_1.4>sc query WinDivert
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.


C:\proxy_1.4>sc create WinDivert binPath="WinDivert64.sys" type=kernel
[SC] CreateService SUCCESS

C:\proxy_1.4>sc start WinDivert
[SC] StartService FAILED 1056:

An instance of the service is already running.


C:\proxy_1.4>sc query WinDivert

SERVICE_NAME: WinDivert
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\proxy_1.4>proxy.exe
error open WinDivert device.(1058)`
The error code is different and it means:`The service cannot be started, either because it is disabled or because it has no enabled devices associated with it`.Does it has something to do with network interface？
`C:\>ipconfig

Windows IP Configuration

Ethernet adapter vEthernet (Ethernet) 3:
.........(MAC and address info)`
I also found somthing strange if i change the order of command:
`C:\Users\Cathy>docker run -it --rm --isolation=process --name=server2 servercore:1903  cmd
Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\>cd proxy_1.4

C:\proxy_1.4>sc create WinDivert binPath="WinDivert64.sys" type=kernel
[SC] CreateService SUCCESS

C:\proxy_1.4>sc start WinDivert
[SC] StartService FAILED 1056:

An instance of the service is already running.


C:\proxy_1.4>proxy.exe
error open WinDivert device.(2)

C:\proxy_1.4>sc create WinDivert binPath="WinDivert64.sys" type=kernel
[SC] CreateService FAILED 1073:

The specified service already exists.


C:\proxy_1.4>proxy.exe//if the previous command is failed,why the result is different?
error open WinDivert device.(1058)`
Look forward to your reply!

**Comment by basil00** [comment]
You should first run the following before each test.

    sc stop WinDivert
    sc delete WinDivert

This will clean up any zombie service that may prevent a new instance from being started.

That said, my guess is that docker is incompatible with WinDivert.   It is already known that WinDivert is incompatible with some virtualization environments that do not support device drivers.  But usually this manifests as a `ERROR_DRIVER_BLOCKED` (1275) error.  I don't know very much about the internals of docker so I can't say for sure.

**Comment by senweiliang** [comment]
Maybe I should try other ways to solves this problem.Thank you very much.😀

**Comment by basil00** [comment]
No problem.
