### ISSUE TITLE
WinDiver sending issue

### ISSUE THREAD

**Issue by abdullahdd** [basil00/Divert#219]
Hi,

First of all we thank you for the wonderful library that has provided us with the way to do intercept/re-inject packets which we were looking for a long time.

We have a 3 stage architecture in which first stage just dumps incoming packets into db. Second load balances traffic by routing packets to third stage which is also responsible for sending out tcp acks. All of three stages run on the same machine and are written in .NET and this library is implemented using p/invoke of TechnikEmpire.

This model works great except when we restart second stage then third stage won't receive any packet unless its also restarted.

We tried passing debug flag to WinDivertSendEx method to find out why its unable to send packet and we got error 592 in case of tcp and 122 on udp.

Digging further we found out that 592 corresponds to ERROR_DATA_NOT_ACCEPTED which as per windivert faq comes when the packet is malformed. This clue doesn't make sense as the application before restart works fine.

We are unable to resolve this issue after spending a lot of time on it thus we need your help. If you want we can provide isolated code that demonstrates this problem.

Regards,
Abdullah Atta

**Comment by basil00** [comment]
The error codes suggest that Windows is rejecting your injected packets for some reason (older versions of WinDivert will not generate these error codes directly).  As for the reason, I am not sure. Some (minimal) sample code that demonstrates the problem may help.

**Comment by abdullahdd** [comment]
We were finally able to make it work by passing different "priority" value to WinDivertOpen method. Earlier we were passing the same priority value(100) to WinDivertOpen method of all 3 stages(that ran on the same machine). This may have caused issue with restart of stages.

Anyways, the issue seems to be fixed and we aren't experiencing it anymore.

Thanks for your answer and library, without it we may not have been able to achieve what we wanted.

**Comment by basil00** [comment]
If multiple handles are opened at the same priority, then it is undefined which order the handles will receive the packets (higher internal priority).  However, in the current implementation, it is more likely that the handle that is opened first will have the higher priority.

Anyway, this issue appears resolved.
