### ISSUE TITLE
ERROR_ACCESS_DENIED	

### ISSUE THREAD

**Issue by NewStarTuit** [basil00/Divert#220]
how can I call without Administrator privileges.
<requestedExecutionLevel level="asInvoker" uiAccess="false" />

**Comment by NewStarTuit** [comment]
I want to call WinDivert.dll by C#.
I have an error: ERROR_ACCESS_DENIED.
<requestedExecutionLevel level="asInvoker" uiAccess="false" />
I have called like this

 [DllImport("WinDivert.dll", EntryPoint = "WinDivertOpen", CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
public static extern IntPtr WinDivertOpen([In()] [MarshalAs(UnmanagedType.LPStr)] string filter, WinDivertLayer layer, short priority, ulong flags);

**Comment by basil00** [comment]
Normally you need to embed a _manifest file_ into your executable with the following:

    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
            </requestedPrivileges>
        </security>
    </trustInfo>

I am not sure how it works for C# so you'll need to google how to do it.

When the application is run, a UAC prompt will appear.  If the user accepts the application will run with Administrator privileges and WinDivert can be used.
