### ISSUE TITLE
WinDivertSend params issue

### ISSUE THREAD

**Issue by pharra** [basil00/Divert#221]
```c
BOOL WinDivertSend(     
  __in HANDLE handle,    
  __in const VOID *pPacket,    
  __in UINT packetLen,     
  __out_opt UINT *pSendLen,     
  __in const WINDIVERT_ADDRESS *pAddr 
);
```

Can pAddr be NULL in this func?
Or there is another method to get it except WinDivertRecv func?

**Comment by basil00** [comment]
The `pAddr` parameter cannot be NULL.

A program can manually construct a `WINDIVERT_ADDRESS` and pass it to `WinDivertSend()`.  The main complication is getting a valid value for the `IfIdx` field.  This should be possible using the [IP Helper API](https://docs.microsoft.com/en-us/windows/win32/iphlp/about-ip-helper).
