### ISSUE TITLE
driver load with out catalog file

### ISSUE THREAD

**Issue by honor2030** [basil00/Divert#223]
hi basil,
sorry for many questions.
i'm woried about situation can't use windivert.
i just wonder how can we load windivert driver without catalog file in windows.
as i know, without catalog file(WHQL), driver can't be loaded.(only it can be tested test mode until i know)
do you have any idea or solution about it?

**Comment by basil00** [comment]
WinDivert uses [attestation signing](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/attestation-signing-a-kernel-driver-for-public-release) which is sufficient for public release.  There was some confusion as to whether WHQL is required for Windows Server, but it turns out that it does not.

**Comment by honor2030** [comment]
then the driver can downloaded from windivert home page is sufficient for public release?
our developer tested on Windows 10.and it can't be loaded.
i search about "attestation signing" which you linked. and our developer told me it's process of WHQL.
i'm really sorry to bother you but i need answer.
my question is

 1. how can we release Windivert as public use?
 2. the windivert working on windows 8, 8.1,10?

**Comment by basil00** [comment]
> then the driver can downloaded from windivert home page is sufficient for public release?

Yes, it is supposed to work.  If it does not, then you should retry after reboot.  If it still does not work, then retry one of the other variants (A/B/C/D) which have different signatures (again after reboot).   If it still does not work then report back.

If you want to sign your own version, this is possible and WHQL is not required.  The process is complicated so I cannot summarize it here and you'll need to follow the guides (see the link), but it can be done.
