### ISSUE TITLE
how to contruct WINDIVERT_ADDRESS?

### ISSUE THREAD

**Issue by abeljinming** [basil00/Divert#226]
Hi, 
I contruct a ip packet directly, then use WinDivertSend to inject, but there is a parameter WINDIVERT_ADDRESS,  could you please tell how to contruct this parameter? (I do not use WinDivertRecv so no addr returned)

**Comment by abeljinming** [comment]
I saw the descriptions in doc:

1. The Network.* fields are only valid at the WINDIVERT_LAYER_NETWORK and WINDIVERT_LAYER_NETWORK_FORWARD layers. The Network.IfIdx/Network.SubIfIdx indicate the packet's network adapter (a.k.a. interface) index. These values are ignored for outbound packets.

2. Most address fields are ignored by WinDivertSend(). The exceptions are Outbound (for WINDIVERT_LAYER_NETWORK only), Impostor, IPChecksum, TCPChecksum, UDPChecksum, Network.IfIdx and Network.SubIfIdx.

so I wrote codes like this:

	PWINDIVERT_IPHDR ip_header;
	PWINDIVERT_TCPHDR tcp_header;
	PWINDIVERT_UDPHDR udp_header;
	PWINDIVERT_ICMPHDR icmp_header;
	PVOID packet_data;
	UINT data_len;

	WinDivertHelperParsePacket(packet, packet_len, &ip_header, NULL, NULL, &icmp_header, NULL, &tcp_header, &udp_header, &packet_data, &data_len, NULL, NULL);

	if (ip_header != NULL)
	{
		if (tcp_header != NULL)
		{
			ip_header->SrcAddr = WinDivertHelperHtonl(serverIP);
			tcp_header->SrcPort = WinDivertHelperHtons(serverPort);

			WINDIVERT_ADDRESS addr;
			memset(&addr, 0, sizeof(addr));
			addr.Outbound = 1;
			addr.IPChecksum = 1;
			addr.TCPChecksum = 1;

			WinDivertHelperCalcChecksums(packet + pos, len, &addr, 0);
			WinDivertSend(hWinDivert, packet + pos, len, NULL, &addr); **// Is this right?**
		}
	}

**Comment by basil00** [comment]
> Are the codes above right?

Something like that.  You can use wireshark to see if the packet was sent or not.

For inbound you also need the `IfIdx`/`SubIfIdx` which is more difficult to extract.

**Comment by abeljinming** [comment]
solved. many thanks!
