### ISSUE TITLE
WinDivert and Virtual Machines

### ISSUE THREAD

**Issue by pbix** [basil00/Divert#227]
I have an interesting WinDIvert application using VirtualBox I am working on but I need some help.

For the most part WinDivert does great at intercepting traffic on the virtual network connection from the guest to the host.  But if the host is providing the gateway function for the guest it seems that WinDIvert cannot see those packets.  It's interesting to me that Wireshark can see these packets without issue.  Other packets directed directly at the host work great so its a mystery to me. 
I have never before seen a case where Wireshark could capture a packet the WinDivert could not.

In the below image I show simple example, a ping to an address on a different subnet from the guest.  The default route in the guest routes the packet properly as  Wireshark sees the ICMP packets but the netdump.exe utility does not.

Any hints would be greatly appreciated.

![WinDivert](https://user-images.githubusercontent.com/289729/77270894-95534780-6c83-11ea-9c0a-ef651db92fcc.jpg)

**Comment by pbix** [comment]
This issues seems related to 
https://github.com/basil00/Divert/issues/34

I recompiled netdump to use WINDIVERT_LAYER_NETWORK_FORWARD as a test but there still was no output.

So I am confused and to how WireShark can see these but WinDivert cannot see traffic with DestAddress that does not match the adapter.  

I am trying to write an application that does the NAT itself so the gateway function is intended to be my application.

**Comment by basil00** [comment]
> So I am confused as to how WireShark can see these but WinDivert cannot see traffic with DestAddress that does not match the adapter.

WireShark works at a more low-level layer (layer 2) where there is no distinction between packets to/from the machine, and packets passing through the machine.  WinDivert works at the network layer (layer 3) where Windows already makes the distinction between forward and non-forward traffic.

The main gotcha with the FORWARD layer is the interaction with the NAT if it is enabled.  I am not sure how this works with VirtualBox and your setup, but that is the obvious thing to check.

**Comment by pbix** [comment]
Hi basli00 and thanks for your response.

This is a windows 10 desktop computer.  I have not found any references that indicate that it has NAT or is even capable of NAT.  Can you suggest any so I can do more research?  ICS is disabled on this machine by our network administrator.

It appears to me that without NAT Windows just drops packets who's address does not match the adapter.  Maybe if installed some type of NAT on this machine it would not?

**Comment by basil00** [comment]
> ICS is disabled on this machine by our network administrator.

I thought ICS had to be enabled for the FORWARD layer to even work?

> It appears to me that without NAT Windows just drops packets who's address does not match the adapter.

Right, there is no "promiscuous mode" for WinDivert, since this is not supported in layer 3.  This is one major difference with the pcap family.  Even the FORWARD layer is for limited case when Windows is configured as a router.

So probably that might explain why you are not seeing anything.

**Comment by pbix** [comment]
I never saw any output from the FORWARD layer so maybe that explains why.  It makes me think that if I could get ICS on then the WinDivert solution could be made to work.  You might add a note about the relationship between the FORWARD function and ICS in your documentation.  The WinDivertOpen() call returned without error.  If this could be made to check ICS is on and report it could save some confusion and a lot of wasted effort,

For others that might be reading this I have used NPCAP in combination with WinDivert to solve this dilemma.  Packets destined for the machine use WinDivert and packets using the machine as a gateway are processed through NPCAP.  This works because Windows is otherwise dropping these FORWARD packets which leaves my application the ability to forward them.

Thanks again basil000 for this very nice software tool WinDivert.  Well documented, supported and elegant.  It's a gem.
