### ISSUE TITLE
Does WinDivert support A Hyper-V Switcher?

### ISSUE THREAD

**Issue by pharra** [basil00/Divert#230]
It seems that the filter cannot capture packages from Hypver vm with nat network, but applys to the virtualbox nat network.

**Comment by basil00** [comment]
Perhaps try using the `NETWORK_FORWARD` layer?  Otherwise, it is possible the packets are being injected at layer-2, and thus might be invisible to WinDivert (layer-3).

**Comment by pharra** [comment]
The NETWORK_FORWARD layer doesnt work too.
Windows provides an in-box filtering [extension](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/overview-of-the-hyper-v-extensible-switch) (Wfplwfs.sys) for Hyper-v Switch.
Maybe It works with normal WFP filters or callout drivers.

**Comment by basil00** [comment]
> Windows provides an in-box filtering extension (Wfplwfs.sys) for Hyper-v Switch.

By the filename, that is a "lightweight filter" driver, which is more low-level than WinDivert.  So, I think perhaps my theory is correct.
