### ISSUE TITLE
"warning: failed to reinject packet (1232) " on WinDivertOpen

### ISSUE THREAD

**Issue by gergul** [basil00/Divert#232]
>passthru.exe
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)
warning: failed to reinject packet (1232)

OS: Windows10 x64

Thank you.

**Comment by basil00** [comment]
This problem is documented [here](https://reqrypt.org/windivert-doc.html#divert_send) and [here](https://reqrypt.org/windivert-doc.html#known_issues).  Basically, there is some other driver on your system that is causing packets to enter into an infinite loop.
