### ISSUE TITLE
can filter against HTTP content

### ISSUE THREAD

**Issue by muse117** [basil00/Divert#233]
Hi，
I am considering making a WAF, and I want to know whether windivert can Filter the HTTP content. I have investigated the IIS plug-in ISAPI Filter, and I would like to know which is more suitable for WAF technology.

**Comment by basil00** [comment]
You can use WinDivert to filter HTTP.  But most traffic is HTTPS these days so the packets will be encrypted.

**Comment by muse117** [comment]
> You can use WinDivert to filter HTTP. But most traffic is HTTPS these days so the packets will be encrypted.

Windivert is for port filtering, so you need to know the port of every HTTP service to filter? I see HttpFilteringEngine, but , No Longer Maintained

**Comment by basil00** [comment]
It depends on exactly what you want to do.  Do you want to filter based on the contents to HTTP/S requests, or filter based on the application/program that sent the HTTP/S requests?  The former is difficult because of encryption, and the latter might be feasible using at the WinDivert `SOCKET` layer.

**Comment by muse117** [comment]
> It depends on exactly what you want to do. Do you want to filter based on the contents to HTTP/S requests, or filter based on the application/program that sent the HTTP/S requests? The former is difficult because of encryption, and the latter might be feasible using at the WinDivert `SOCKET` layer.

I want to filter based on the contents to HTTP/S requests, Similar to Web Application Firewall(WAF). I know this feature is mostly an plugin-in the nginx、apache or iis. I wonder if a windivert can do the same.If so, what is the impact on performance, and is it more expensive than the plug-in

**Comment by basil00** [comment]
In that case - no you cannot do it, or at least not without great difficulty.  Essentially, you'd need to implement a MITM infrastructure which is what HttpFilteringEngine does.

**Comment by muse117** [comment]
> In that case - no you cannot do it, or at least not without great difficulty. Essentially, you'd need to implement a MITM infrastructure which is what HttpFilteringEngine does.

I see, thank you！

**Comment by basil00** [comment]
> Also, will you continue to maintain windivert?

Yes definitely.

There is a new version with layer 2 filtering in the pipeline.  However, there are some bugs that are unsolved, but hopefully I'll have time to fix over the next few months.  Unfortunately my time has been very limited recently.

**Comment by muse117** [comment]
> > Also, will you continue to maintain windivert?
> 
> Yes definitely.
> 
> There is a new version with layer 2 filtering in the pipeline. However, there are some bugs that are unsolved, but hopefully I'll have time to fix over the next few months. Unfortunately my time has been very limited recently.

so great!
