### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by kouzhudong** [basil00/Divert#238]
1>------ 已启动生成: 项目: WinDivert, 配置: Release x64 ------
1>Building 'WinDivert' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
1>MC: Compiling windivert_log.mc
1>windivert.c
1>F:\git\network\Divert\sys\windivert.c(5585,43): warning C4189: “total_len”: 局部变量已初始化但不引用
1>F:\git\network\Divert\sys\windivert.c(6323): warning C4701: 使用了可能未初始化的局部变量“pid_size”
1>windivert.rc(48): warning RC4005: 'VER_PRODUCTVERSION' : redefinition
1>
1>windivert.rc(49): warning RC4005: 'VER_PRODUCTVERSION_STR' : redefinition
1>
1>windivert.rc(50): warning RC4005: 'VER_COMPANYNAME_STR' : redefinition
1>
1>windivert.rc(56): warning RC4005: 'VER_PRODUCTNAME_STR' : redefinition
1>
1>windivert.vcxproj -> F:\git\network\Divert\sys\x64\Release\WinDivert.sys
1>Done Adding Additional Store
1>Successfully signed: F:\git\network\Divert\sys\x64\Release\WinDivert.sys
1>
1>已完成生成项目“windivert.vcxproj”的操作。
========== 生成: 成功 1 个，失败 0 个，最新 0 个，跳过 0 个 ==========

**Comment by basil00** [comment]
I think I remember similar warnings, but they are probably harmless and will likely be fixed in the next release.
