### ISSUE TITLE
Trouble passing HLK test

### ISSUE THREAD

**Issue by tony2100** [basil00/Divert#239]
Hi,

Thank you for creating such a great WFP library that made the life a lot easier. We are signing the driver with our own certificate, but ran into some problems when testing on HLK, it reported two failures in WindowFilterPlatform_Tests:

1. Filter.Driver.WindowsFilteringPlatform.ArchitecturalDesign-NetworkDiagnosticsFramework-HelperClass: Meaning that WinDivert does not have a NDF Helper class.
2. Filter.Driver.WindowsFilteringPlatform.ArchitecturalDesign-FwpmProviders-MaintainIdentifying: Meaning that WinDivert does not have an identifying Provider.

We checked the code and indeed did not find code relating to Helper class and Provider, but the releasd drivers must have passed the test, so we wonder where are the mistakes.

Here is WFPLogo.Info we set on HLK
[Run By:                                                test] 
[Company Name:                                          Basil] 
[Product Name:                                          WinDivert] 
[Driver Name:                                           C:\Windows\System32\Drivers\WinDivert.sys] 
[Enable Driver Verifier:                                TRUE] 
[Use Answer File:                                       TRUE] 
[Has a callout driver:                                  TRUE] 
[Is a firewall:                                         TRUE] 
[Layered on Microsoft Windows Firewall:                 FALSE] 
[Does MAC Filtering:                                    FALSE] 
[Does Virtual Switch Filtering:                         FALSE] 
[Does Packet Injection:                                 TRUE] 
[Does Stream Injection:                                 FALSE] 
[Does Proxying:                                         TRUE] 
[Supports Modern Applications:                          TRUE] 
[Uninstalls cleanly:                                    TRUE] 
[Proxies without deadlocking:                           TRUE] 
[Has an identifying Provider:                           TRUE] 
[Associates Provider with all objects:                  TRUE] 
[Has at least 1 filter:                                 TRUE] 
[Uses only built-in or their own private SubLayer:      TRUE] 
[Has an NDF Helper Class:                               TRUE] 
[Does not AV:                                           TRUE] 
[Does not alter other's WFP Objects:                    TRUE] 
[Injects without deadlocking:                           TRUE] 
[Injects at STREAM without starvation:                  TRUE] 
[Supports Power Managed States:                         TRUE] 
[ACLs objects so other's can enum them:                 TRUE] 
[Uses latest WinSock specifications:                    TRUE] 
[Properly disabled Windows Firewall:                    TRUE] 
[Uses granular filtering:                               TRUE] 
[Can filter by 5 tuples:                                TRUE] 
[Can filter by application name:                        TRUE] 
[Can filter by Physical Addresses:                      TRUE] 
[Uses WFP for filtering and packet maniplulation:       TRUE] 
[Supports IPv4 Address Resolution - ARP:                TRUE] 
[Supports IPv6 Address Resolution - Neighbor Discovery: TRUE] 
[Supports Dynamic IP Addressing:                        TRUE] 
[Supports IPv4:                                         TRUE] 
[Supports IPv6:                                         TRUE] 
[Supports Name Resolution:                              TRUE] 
[Supports 6TO4:                                         TRUE] 
[Supports Automatic Updates:                            TRUE] 
[Supports Basic Website Browsing:                       TRUE] 
[Supports File and Printer Sharing:                     TRUE] 
[Supports ICMP Error Messages:                          TRUE] 
[Supports Internet Streaming:                           TRUE] 
[Supports Media Extender Streaming:                     TRUE] 
[Supports MobileBroadband:                              TRUE] 
[Supports Peer Name Resolution Protocol:                TRUE] 
[Supports Remote Assistance:                            TRUE] 
[Supports Remote Desktop:                               TRUE] 
[Supports Teredo:                                       TRUE] 
[Supports Virtual Private Networking:                   TRUE] 
[Interops with other Virtual Switch Extensions:         TRUE] 
[Does not modify at Egress:                             TRUE] 
[Supports Live Migration:                               TRUE] 
[Supports Removal of Virtual Switch Extensions:         TRUE] 
[Supports Reordering of Virtual Switch Extension:       TRUE] 
[Performed interop testing with the WFPSampler          TRUE]

Test Server is Windows Server 2016, and Test Client is Windows 10 1809.

Appreciate it if you could provide some help!

**Comment by basil00** [comment]
I think you are the first to attempt WinDivert with HLK, so it is good there are only two issues.

> Filter.Driver.WindowsFilteringPlatform.ArchitecturalDesign-NetworkDiagnosticsFramework-HelperClass: Meaning that WinDivert does not have a NDF Helper class.

I wasn't aware that NDF even existed.  I will need to study the documentation some more, but at a glance it might be useful as another way of making WinDivert more visible to the end-user.

> Filter.Driver.WindowsFilteringPlatform.ArchitecturalDesign-FwpmProviders-MaintainIdentifying: Meaning that WinDivert does not have an identifying Provider.

This one I do not really understand, and has something to do with a `WFPLogo.Info` file?

> We checked the code and indeed did not find code relating to Helper class and Provider, but the releasd drivers must have passed the test, so we wonder where are the mistakes.

For the NDF class, you'd probably need to write one yourself until I have time to study/implement a more permanent solution.

**Comment by tony2100** [comment]
We have now managed to pass theses two failures, by simply installing a provider in DriverEntry, and remove it on unload. All tests have passed.

We will later submit a pull request about this issue.

**Comment by basil00** [comment]
Sure, please do.

**Comment by cnlh** [comment]
> Hi,
> 
> Thank you for creating such a great WFP library that made the life a lot easier. We are signing the driver with our own certificate, but ran into some problems when testing on HLK, it reported two failures in WindowFilterPlatform_Tests:
> 
> 1. Filter.Driver.WindowsFilteringPlatform.ArchitecturalDesign-NetworkDiagnosticsFramework-HelperClass: Meaning that WinDivert does not have a NDF Helper class.
> 2. Filter.Driver.WindowsFilteringPlatform.ArchitecturalDesign-FwpmProviders-MaintainIdentifying: Meaning that WinDivert does not have an identifying Provider.
> 
> We checked the code and indeed did not find code relating to Helper class and Provider, but the releasd drivers must have passed the test, so we wonder where are the mistakes.
> 
> Here is WFPLogo.Info we set on HLK
> [Run By: test]
> [Company Name: Basil]
> [Product Name: WinDivert]
> [Driver Name: C:\Windows\System32\Drivers\WinDivert.sys]
> [Enable Driver Verifier: TRUE]
> [Use Answer File: TRUE]
> [Has a callout driver: TRUE]
> [Is a firewall: TRUE]
> [Layered on Microsoft Windows Firewall: FALSE]
> [Does MAC Filtering: FALSE]
> [Does Virtual Switch Filtering: FALSE]
> [Does Packet Injection: TRUE]
> [Does Stream Injection: FALSE]
> [Does Proxying: TRUE]
> [Supports Modern Applications: TRUE]
> [Uninstalls cleanly: TRUE]
> [Proxies without deadlocking: TRUE]
> [Has an identifying Provider: TRUE]
> [Associates Provider with all objects: TRUE]
> [Has at least 1 filter: TRUE]
> [Uses only built-in or their own private SubLayer: TRUE]
> [Has an NDF Helper Class: TRUE]
> [Does not AV: TRUE]
> [Does not alter other's WFP Objects: TRUE]
> [Injects without deadlocking: TRUE]
> [Injects at STREAM without starvation: TRUE]
> [Supports Power Managed States: TRUE]
> [ACLs objects so other's can enum them: TRUE]
> [Uses latest WinSock specifications: TRUE]
> [Properly disabled Windows Firewall: TRUE]
> [Uses granular filtering: TRUE]
> [Can filter by 5 tuples: TRUE]
> [Can filter by application name: TRUE]
> [Can filter by Physical Addresses: TRUE]
> [Uses WFP for filtering and packet maniplulation: TRUE]
> [Supports IPv4 Address Resolution - ARP: TRUE]
> [Supports IPv6 Address Resolution - Neighbor Discovery: TRUE]
> [Supports Dynamic IP Addressing: TRUE]
> [Supports IPv4: TRUE]
> [Supports IPv6: TRUE]
> [Supports Name Resolution: TRUE]
> [Supports 6TO4: TRUE]
> [Supports Automatic Updates: TRUE]
> [Supports Basic Website Browsing: TRUE]
> [Supports File and Printer Sharing: TRUE]
> [Supports ICMP Error Messages: TRUE]
> [Supports Internet Streaming: TRUE]
> [Supports Media Extender Streaming: TRUE]
> [Supports MobileBroadband: TRUE]
> [Supports Peer Name Resolution Protocol: TRUE]
> [Supports Remote Assistance: TRUE]
> [Supports Remote Desktop: TRUE]
> [Supports Teredo: TRUE]
> [Supports Virtual Private Networking: TRUE]
> [Interops with other Virtual Switch Extensions: TRUE]
> [Does not modify at Egress: TRUE]
> [Supports Live Migration: TRUE]
> [Supports Removal of Virtual Switch Extensions: TRUE]
> [Supports Reordering of Virtual Switch Extension: TRUE]
> [Performed interop testing with the WFPSampler TRUE]
> 
> Test Server is Windows Server 2016, and Test Client is Windows 10 1809.
> 
> Appreciate it if you could provide some help!

I am also doing hlk test recently. In addition to the same error as you, I also encountered more errors. Can you provide some help?

I see that WINDIVERT_PROVIDER_DESC in the pr you submitted is WIndivert, but the Company Name in the WFPLogo.Info above is Basil.

According to Microsoft's regulations, this seems to be wrong. Can you provide the WFPLogo.Info content that passed the test?

Or can you provide some other help, thank you very much!

**Comment by Fplyth0ner-Combie** [comment]
> We have now managed to pass theses two failures, by simply installing a provider in DriverEntry, and remove it on unload. All tests have passed.
> 
> We will later submit a pull request about this issue.
> 

@tony2100 
Thank you very much for starting this topic two years ago. 

Can you provide more information on what to pay attention to during testing (HLK/HCK for windivert)?

I've been worrying about it lately.

@basil00 
I suggest activating the issue for a while to see how many people want it.
