### ISSUE TITLE
A request to port 80 is detected as port 20480

### ISSUE THREAD

**Issue by toarek** [basil00/Divert#240]
Hello!
I am currently doing a project based on WinDivert.

At the beginning I will say that I read this [thread](https://github.com/basil00/Divert/issues/32).

I detect all outgoing traffic from my computer and when I start the website using ip (for example I use: [http://46.101.248.126/](http://46.101.248.126/)) then the detected destination port traffic points to port 20480 instead of port 80, which is used by default by HTTP.
I have no idea how to fix this so that the port is valid. I scanned the network using WireShark and he showed this port as 80.

I'm using WinDivertSharp, but this shouldn't make much difference.

To open WinDivert I use filter 'outbound', layer 0, priority 0 and flags 0.
And then it reads all the data I need with 'WinDivertRecv', because except that port everything seems to be correct.

I hope that the problem can be resolved quickly.
Best regards :)

**Comment by basil00** [comment]
Remember that all network packet fields, including the port numbers, are in *network byte order* (big endian), whereas your machine uses the reverse byte ordering (little endian).  For example:

    0x0050 = 80
    0x5000 = 20480

You need to use the `ntohs()` or `WinDivertHelperNtohs()` to swap the byte order.
