### ISSUE TITLE
Add Layer 2 Filtering as in new WFP

### ISSUE THREAD

**Issue by NULL0B** [basil00/Divert#242]
Hello as this Microsoft article says L2 is now available in WFP https://docs.microsoft.com/en-us/windows/win32/fwp/what-s-new-in-windows-filtering-platform. Could you add support for it?

**Comment by basil00** [comment]
It already exists as a branch here: https://github.com/basil00/Divert/tree/eth_layer

Unfortunately, it suffers from a bug where it can stop networking working for the entire machine, and this can only be fixed on reboot or by disabling+enabling the network adapter.  This occurs when a user apps is stopped/started too many times.  I have not been able to figure it out, hence the branch is in limbo.
