### ISSUE TITLE
Can't change packet payload

### ISSUE THREAD

**Issue by daimiaopeng** [basil00/Divert#243]
```cpp
class A{
.....................
void setPayload(char *newPayload, int len) {
        cout << "Payload len: " << payload_len << endl;
        memcpy(payload, newPayload, len);
        buffLen = buffLen - payload_len + len;
    }
    UINT send(){
        UINT sendLen;
        WinDivertHelperCalcChecksums(buff, buffLen, &addr, 0);
        if (!WinDivertSend(handle, buff, buffLen, &sendLen, &addr)) {
            cout<<"failed to send packet "<<GetLastError()<<endl;
        }
        return sendLen;
    };
}
  
```
If the changed data is less than or equal to the source length, it can work, otherwise failed to send packet 122

**Comment by basil00** [comment]
You didn't update the `Length` field hence you get an 122 error (`ERROR_INSUFFICIENT_BUFFER`).

**Comment by daimiaopeng** [comment]
> You didn't update the `Length` field hence you get an 122 error (`ERROR_INSUFFICIENT_BUFFER`).

payload len?

**Comment by basil00** [comment]
The length fields in the IP header, for example.  You might need to correct other headers as well.

But generally, `WinDivertSend` expects a valid IP packet.  If you do not pass a valid packet, it may fail with an error message, which seems to be the case here.

**Comment by daimiaopeng** [comment]
I updata  ip_header->Length ,but It appeared tcp spurious retransmission
```cpp
 ip_header->Length = htons(ntohs(ip_header->Length) - payload_len + len);
```
![image](https://user-images.githubusercontent.com/32475719/86867787-0705b300-c106-11ea-87c2-07ca5bdac6f2.png)

**Comment by basil00** [comment]
If you change the length of a TCP packet, then you'd need to correct the syn/ack numbers for the rest of the stream.  This is very complicated, and requires sufficient knowledge of the TCP protocol.  It is much easier to redirect to a proxy and edit the stream there.  See the `streamdump.exe` sample for how to redirect to a local proxy server.
