### ISSUE TITLE
How to redirect tcp and udp packet to socks5 server 

### ISSUE THREAD

**Issue by tanweizlf** [basil00/Divert#245]
Thank you for your project.it's very good.  
I have a question,how to  redirect tcp and udp packet to socks5 server?

thank you very much.

**Comment by basil00** [comment]
Redirecting TCP/DNS to a SOCKS4a proxy has been implemented in Tallow: https://github.com/basil00/TorWall/blob/master/redirect.c
The implementation is somewhat complicated though, and I am not aware of anything similar for SOCKS5.
