### ISSUE TITLE
[Doubt] Reissuing Packet

### ISSUE THREAD

**Issue by ImRoKi** [basil00/Divert#246]
Hello,
so I was wondering if it's possible to send the same packet twice, and if yes, am I supposed to edit it before sending it again?

Thanks!

**Comment by basil00** [comment]
It is possible, just call `WinDivertSend` with the same parameters twice.

**Comment by ImRoKi** [comment]
> It is possible, just call `WinDivertSend` with the same parameters twice.

Uhm the client won't accept it tho... But when I just send the udp datagram again to the client normally (via the server) it gets accepted... so maybe the client detects that it's a duplicate. Is there a way to inject it as a brand new packet with just the same udp data? thx.

**Comment by ImRoKi** [comment]
@basil00 Because i think the client detects it's a duplicate, so my wonder is, can I make a new packet from an old one and inject it? So the client won't detect that it has already been sent/it's old?
