### ISSUE TITLE
Can not capture the SYN reply from server.

### ISSUE THREAD

**Issue by zhayan** [basil00/Divert#247]
Hi!

I am trying to redirect the TCP traffic. 

I send an injected SYN packet to the server, and I do get a reply. 
![image](https://user-images.githubusercontent.com/37605518/89727361-7e589a80-da56-11ea-9ad1-3ad16baa1a02.png)

But this packet can't be captured by WinDivert when I use _netdump.exe "tcp.Syn and ip.DstAddr==10.150.128.2"_.
And if the TCP handshake success, this packet can be captured.

I am curious if this is a mechanism of Windows or a limitation with Divert.

Thank you.

**Comment by basil00** [comment]
You a getting a retransmission on the SYNACK which probably means the original is being blocked or mishandled by something, such as your WinDivert app.  There should be no Windows or WinDivert mechanism that prevents the packet from being captured.

**Comment by zhayan** [comment]
I get a retransmission because the first SYNACK is not correctly captured and redirected to the real client.
Actually, there is no app running on this interface. I just capture all the traffic and send it to another interface.

**Comment by zhayan** [comment]
It is my fault. It is impossible to capture the SYNACK without creating a running program listening on the port.
I just create a fake TCP socket to connect with the server, then it works fine.
