### ISSUE TITLE
How to modify TCP header  option field by WinDivert?

### ISSUE THREAD

**Issue by SaberZhhhh** [basil00/Divert#248]
hello!  I want to ask some questions about WinDivert, Thanks a lot.

I want to use  WinDivert  to modify TCP packet. The function WinDivertHelperParsePacket can parse TCP packet ，The struct  WINDIVERT_TCPHDR contains information about TCP header ，

But, I want to  modify the tcp option field,  the struct  WINDIVERT_TCPHDR do not contains  tcp option field，I can not modify tcp option field. 

Can you tell me how to do it?  Thank you very much!

**Comment by basil00** [comment]
There is no built-in TCP option parsing in WinDivert, but it is possible to parse the options manually.  The TCP options appear immediately after the `TCPHDR` and before the TCP payload.  So you can get a pointer to the TCP options by calculating (`tcp_header+1`).
