### ISSUE TITLE
netdump wrong byte length IPv6

### ISSUE THREAD

**Issue by JohannesDeml** [basil00/Divert#249]
When sniffing packages with netdump the definitions for ipv4 and ipv6 length are different (ipv4 includes itself in the length, whereas ipv6 does not).

## Setup
* Version: 2.2.0-A
* OS: Windows 10 Pro 2004
* Command: `.\netdump.exe "outbound and udp.DstPort == 3333"`
* UDP payload: 100 bytes with 0xFF

## ipv4
```
Packet [Timestamp=7.2293147, Direction=outbound IfIdx=1 SubIfIdx=0 Loopback=1 Hash=0x4478BFE71DE3F414]
IPv4 [Version=4 HdrLength=5 TOS=0 Length=128 Id=0x8C46 Reserved=0 DF=0 MF=0 FragOff=0 TTL=128 Protocol=17 Checksum=0x0000 SrcAddr=127.0.0.1 DstAddr=127.0.0.1]
UDP [SrcPort=60786 DstPort=3333 Length=108 Checksum=0x069C]

        450000808C460000801100007F0000017F000001
        ED720D05006C069CFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFF
        E....F...............r...l..............
        ........................................
        ........................................
        ........
```

## ipv6
```
Packet [Timestamp=3.4583626, Direction=outbound IfIdx=1 SubIfIdx=0 Loopback=1 Hash=0xEE482ACDF8C6DD16]
IPv6 [Version=6 TrafficClass=0 FlowLabel=3132229888 Length=108 NextHdr=17 HopLimit=128 SrcAddr=::1 DstAddr=::1]
UDP [SrcPort=53850 DstPort=3333 Length=108 Checksum=0x1FB5]

        6009BAB2006C1180000000000000000000000000
        0000000100000000000000000000000000000001
        D25A0D05006C1FB5FFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFF
        `....l..................................
        .Z...l..................................
        ........................................
        ............................
```

Now the thing that irritates me, is that for IPv4 it prints `Length=128` (so it includes to IP protocol bytes), whereas in IPv6 it prints `Length=108` (it does not include the IP protocol bytes).

I would expect to get 148 bytes as an output for IPv6 length.
Am I missing something here?

**Comment by basil00** [comment]
It is printing the length field of the IPv6 header, which does not include the 40-byte IPv6 header (as per the IPv6 protocol).  So the output is correct.

**Comment by JohannesDeml** [comment]
Ah, sorry, you're totally right. This is a difference in IPv4 vs. IPv6

[IPv4 protocol](https://tools.ietf.org/html/rfc791#section-3.1): Total Length of the datagram
[IPv6 protocol](https://tools.ietf.org/html/rfc2460#section-3): Payload length (everything after the header)

Thanks for the clarification!
