### ISSUE TITLE
How to capture ethernet header? Dst and Src MAC?

### ISSUE THREAD

**Issue by soybeanmeal** [basil00/Divert#25]
When it's a loopback packet, e.g. from 127.0.0.1 (Mac 0x2) to 127.0.0.1(Mac 0x1) ,it's inbound, but addr.Direction is always outbound. That's why I wanna to check the Dst and Src MAC.

I can see the mac via Commview.

It's useful when using client and server on the same machine.

**Comment by Zensey** [comment]
@basil00 
is it possible to patch the library  in such a way, so that Ethernet header is also captured ?
