### ISSUE TITLE
Filter language ip range rule support

### ISSUE THREAD

**Issue by muse117** [basil00/Divert#250]
hi,
Can IP range rules be supported, such as, 1.1.1.1-1.1.1.100, 1.1.1.0/24

**Comment by basil00** [comment]
It is possible but uses a non-traditional syntax, e.g.:

        ip.DstAddr >= 1.1.1.1 && ip.DstAddr <= 1.1.1.100

**Comment by muse117** [comment]
Another question, The IP checksum of the reset packet is zero in the netFilter example. 
` WinDivertHelperCalcChecksums((PVOID)reset, sizeof(TCPPACKET), &send_addr, 0);`
![微信截图_20201126134730](https://user-images.githubusercontent.com/9733486/100312709-fa6af400-2fed-11eb-8335-273c4e2e6180.png)

**Comment by basil00** [comment]
I am not sure if this is a problem.  What checksum does `WinDivertHelperCalcChecksums` set?  Is the packet dropped?

**Comment by muse117** [comment]
> I am not sure if this is a problem. What checksum does `WinDivertHelperCalcChecksums` set? Is the packet dropped?

I can be received normally this packet and reset the connection. I wonder why Wireshark shows 0000, Have you tested the netfilter example with Wireshark?

**Comment by basil00** [comment]
I would not be concerned about it unless there is a problem, such as packets being rejected for invalid checksums.

**Comment by muse117** [comment]
Modify the payload data, but the payload length remains the same. Do you need to recalibrate the TCP checksum?

**Comment by basil00** [comment]
Yes since the tcp checksum covers the tcp payload.
