### ISSUE TITLE
No ICMP packet received after blocking UDP packet

### ISSUE THREAD

**Issue by mindaugasveblauskas** [basil00/Divert#252]
Hi, 

I'm trying to block windows DNS queries by blocking outbound UDP 53 port:

`netfilter.exe "outbound and udp.DstPort == 53"`

But Wireshark does not capture any ICMP packet which is successfully sent by netfilter.exe and the packet is not blocked by WFP (checked event viewer logs). And windows DNS client keeps retrying to resolve it until eventually fails after 10 seconds.
So if Wireshark does not capture the packet, most likely windows dns client is not receiving it as well.

Am I doing something wrong here? I want to prevent a 10-second timeout by sending ICMP network unreachable 3 with code 13 (admin prohibid).

**Comment by basil00** [comment]
WinDivert will process outbound packets before Wireshark, so the latter should not capture the original packet nor the generated ICMP packet which will be inbound.  Also, WFP will not log dropped packets.

However, it should be possible to use the `netdump` sample to capture both the original and generated ICMP.  You need to set the priority to be higher that that for `netfilter`.

Finally, I am not sure how Windows treats the ICMP message.  For many, it will just ignore.
