### ISSUE TITLE
WinDivert not working on Windows 10 20H2

### ISSUE THREAD

**Issue by Plecharts** [basil00/Divert#253]
Hi,
WinDivert 2.2.0 stopped working after updating my OS to Windows 10 20H2. The exact same build of my app worked on build 19041.630 (2004), but is now throwing ERROR_FILE_NOT_FOUND on 19042.630 (20H2). Also tried running on other older builds (1909) with no issues there, so it seems like this is somehow related to the newest Windows 10 updates.

I can also confirm the issue is happening with all three variants (A/B/C) of binaries when trying to launch some of the packaged examples:
`C:\WinDivert-2.2.0-A\x64>test
error: failed to open WinDivert handle (err = 2)`

`C:\WinDivert-2.2.0-A\x64>netfilter true
error: failed to open the WinDivert device (2)`

EDIT 2020-11-18: It seems that the error is only present on WinDivert 2.2.0, the binaries for 1.4.3 are working fine. Going back through the releases, first not working one is 2.0.0 RC.

**Comment by basil00** [comment]
This is likely just the same problem as #177.  You can try manually deleting the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert` registry entry and reboot.

**Comment by Plecharts** [comment]
Thanks for the answer, indeed that did help with resolving the issue.

**Comment by VarunVk** [comment]
Worked for me too :) Thanks @basil00
