### ISSUE TITLE
Microsoft kernel mode certificate deprecation

### ISSUE THREAD

**Issue by mySYSMON** [basil00/Divert#255]
I believe windivert uses a kernel mode certificate.  Do you anticipate any issues related to this?
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates

I am working on some modifications to the your passthru sample code.  Windivert performance is amazing in sniff mode with 4 threads.  Thanks for creating windivert!  Once I saw suricata uses it I knew it was high quality.

**Comment by basil00** [comment]
Microsoft change their policies from time-to-time, but this only affects the ability to sign new software, and does not affect software that is already signed.  So the old WinDivert drivers should continue to work forever.
