### ISSUE TITLE
UDP packet modify size?

### ISSUE THREAD

**Issue by mp662002** [basil00/Divert#259]
Windows10 20H2(OS 19042.685)
I ran it with administrator privileges.

I want to increase the UDP packet length.
So I modified "udp_header->Length" and increased packet_len.
I created and experimented with a UDP server/client in Python.
But Send succeeded, but it doesn't work. Fixed length has been fixed well.

Main source code
` handle = WinDivertOpen(
        "(inbound or outbound) and "
        "(udp.DstPort == 6112 or udp.SrcPort == 6112)", WINDIVERT_LAYER_NETWORK, priority, 0);

 while (TRUE)
    {

        if (!WinDivertRecv(handle, packet, sizeof(packet), &packet_len, &addr))
        {
            fprintf(stderr, "warning: failed to read packet (%d)\n", GetLastError());
            continue;
        }

        WinDivertHelperParsePacket(packet, packet_len, &ip_header, &ipv6_header, NULL, &icmp_header, &icmpv6_header, &tcp_header, &udp_header, (LPVOID*)&payload, &payload_len, NULL, NULL);

        if (addr.Outbound) {
            printf("OUT");
       
            udp_header->Length = _byteswap_ushort(_byteswap_ushort(udp_header->Length) + 1);
            packet_len++;
            payload[0] = 'Z';
            payload[5] = 'A';
        }
        else {
            printf("IN");
        }
        WinDivertHelperCalcChecksums(packet, packet_len, &addr, 0);
        WinDivertSend(handle, packet, packet_len, NULL, &addr);
}
`
When I try to capture packets with WireShark, "packet_len" doesn't seem to be reflected.
The reason for doing "_byteswap_ushort" is to change big-endian to little-endian.
How can I fix it?
![이미지 034](https://user-images.githubusercontent.com/22292374/102098784-f0a91380-3e6a-11eb-9e41-4f308be4f275.png)
![이미지 035](https://user-images.githubusercontent.com/22292374/102098945-19c9a400-3e6b-11eb-97b7-f2689d120056.png)

**Comment by jjxtra** [comment]
Since the length is just an int, I would assume WinDivert does the right thing as you pass the packet data to the send call.

**Comment by mp662002** [comment]
I tried using outbound and inbound respectively and got the same result.
How do I get a regular packet or modify the overall length (or payload)?

**Comment by mp662002** [comment]
> Since the length is just an int, I would assume WinDivert does the right thing as you pass the packet data to the send call. Also, `inbound and outbound` is redundant and can be left off I believe.

I tried using outbound and inbound respectively and got the same result.
How do I get a regular packet or modify the overall length (or payload)?

**Comment by basil00** [comment]
>    udp_header->Length = _byteswap_ushort(_byteswap_ushort(udp_header->Length) + 1);

This only updates the UDP payload length field, you also need to update the total length field in the IP header.
