### ISSUE TITLE
I can not run WinDivert on my HyperV Windows 10 x64 

### ISSUE THREAD

**Issue by trudyhood** [basil00/Divert#261]
I have a HyperV Windows 10 x64, but can not run test.exe with run as admin
error: failed to open WinDivert handle (err = 5)

Note: I can run it on Windows 10 BuiltIn sandbox
WinDivert version: 2.2.0

Any idea?

**Comment by basil00** [comment]
It is not possible to run WinDivert on some types of virtual machine.  

I am not sure if HyperV is affected.  The error is `ERROR_ACCESS_DENIED`, which should not occur if running as admin.

**Comment by trudyhood** [comment]
Thanks for letting me know. I thought as far as Windows Firewall works, WinDivert would work too!
However, I am wondering why I can run "netdump" on "WinDivert-1.4.3-A"? Maybe there is a problem in WinDivert 2.2.0.

To make sure, I tested again both in a same command line that was executed as admin.

**Comment by basil00** [comment]
It is unclear what the problem is.  It could be a registry problem, which would explain why the older version still worked.  Perhaps try manually deleting the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert` registry entry and reboot.

**Comment by trudyhood** [comment]
Thank you! It solves the problem. Now WinDivert works on my Hyper-V Windows
10 x64
The ImagePath in the key was pointed to the wrong location. It was fixed
after deleting and restarting.
I hope it doesn't happen in production on users' computers. I wish
windivert could detect and fix this issue automatically.

Best,
Trudy
