### ISSUE TITLE
Is "redirect.c" in "torwall" working?

### ISSUE THREAD

**Issue by kamille73** [basil00/Divert#262]
Is "redirect.c" in "torwall" working?
No packets are sent.

    riphdr->SrcAddr   = iphdr->DstAddr;
    riphdr->DstAddr   = iphdr->SrcAddr;

    memset(rudphdr, 0, sizeof(WINDIVERT_UDPHDR));
    rudphdr->SrcPort  = htons(53);          // DNS
    rudphdr->DstPort  = udphdr->SrcPort;
    rudphdr->Length   = htons(len - sizeof(WINDIVERT_IPHDR));

When the source is changed, it has been confirmed that packets are generated.

    riphdr->DstAddr   = inet_addr("10.1.1.1");

It doesn't seem to be receiving locally.

**Comment by basil00** [comment]
It works as far as I am aware.  Perhaps check what value `iphdr->SrcAddr` versus `10.1.1.1`.
