### ISSUE TITLE
Filter complexity

### ISSUE THREAD

**Issue by vkrasnov** [basil00/Divert#263]
Hi,

It seems there is some limit to how complex a filter can be?

I am getting an InvalidInput error when the filter becomes too complex. I think it is otherwise valid.

**Comment by basil00** [comment]
Yes, the filter can be no more than 256 tests.  This limit exists so that filtering is not too slow inside the driver.  If your filter is too complex (e.g., IP blocklist), it can be better to just do the filtering in the user app.
