### ISSUE TITLE
Driver certificate has expired

### ISSUE THREAD

**Issue by anti-matter** [basil00/Divert#266]
The [distributed ](https://github.com/basil00/Divert/releases/tag/v2.2.0)driver has an expired certificate. This is causing a failure to load the driver on some client devices.

![image](https://user-images.githubusercontent.com/6510597/105068055-4e65e800-5a35-11eb-8653-391281b075c9.png)

**Comment by Get-MEOW** [comment]
Microsoft seems to be locking down the certificate process in 2021 more.  So many cool projects use windivert.  I would hate to see suricata stop working on windows due to certificate issues.   Any updates on this?  I believe windivert has another cert, but I forget when it expires.

**Comment by basil00** [comment]
I checked and the driver loads fine on my test system.  The expiry date of the certificate only affects when the certificate can be used to sign a new driver, and does not affect the validity of the signature itself.  So basically, the signature will remain valid even after the certificate expires.

As for why the signature is sometimes rejected by some systems (& not others), this is a problem previously noticed and reported.  I cannot rememberl the exact reason, but I recall it was previously discussed so I'll need to go back and check.  In the meantime, switching to a [different driver variant (A/B/C)](https://github.com/basil00/Divert/releases/tag/v2.2.0) seems to resolve the problem for most users.

**Comment by basil00** [comment]
I assume this issue is resolved so closing.
