### ISSUE TITLE
Does WinDivert support capture outbound ARP packets?

### ISSUE THREAD

**Issue by BruceMok** [basil00/Divert#269]
Does WinDivert support capture outbound ARP packets? If yes, how to implement capture.

**Comment by basil00** [comment]
Apparently this is [not supported](https://social.msdn.microsoft.com/Forums/en-US/082bc374-9fc0-4024-857b-07472e5e84f4/can-wfp-inspect-arp-packets-?forum=wfp).

**Comment by nigriMSFT** [comment]
That forum post is rather old. WFP has supported L2 layer inspection since Windows 8
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/using-layer-2-filtering

**Comment by basil00** [comment]
WinDivert only implements a subset of WFP, and the current release does not support L2.

There is a branch for adding L2 support into WinDivert: https://github.com/basil00/Divert/tree/eth_layer
However, there were some bugs that we never fixed, so the branch is dormant.
