### ISSUE TITLE
Strange characters in the service image path

### ISSUE THREAD

**Issue by oriolarcas** [basil00/Divert#270]
I noticed that when Ioad the driver, the corresponding WinDivert service has some weird characters at the beginning of the image path.

Steps to reproduce:

1. Download the vanilla 2.2 binaries from the web.
2. Start the driver, for instance with `.\windivertctl.exe watch`.
3. Check the ImagePath property with `sc.exe qc WinDivert`:

In my case it shows the following: `BINARY_PATH_NAME   : \??\C:\...\WinDivert-2.2.0-A\x64\WinDivert64.sys`

Note the `\??\` characters. I verified this on two different machines, and I did not find any other services using such prefix (I have an app of my own that also creates a service and does not have this behavior).

Can anybody reproduce this? Does not seem to harm, but it is weird anyway.

**Comment by basil00** [comment]
This is some Windows internal weirdness and not a problem with WinDivert.  If you Google for it you can find other examples of `\??\` pathnames.
