### ISSUE TITLE
CONNECT REDIRECT Support in WinDivert

### ISSUE THREAD

**Issue by anatekar** [basil00/Divert#271]
Is the WFP Connect redirect functionality supported in WinDivert
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/using-bind-or-connect-redirection

I want to use this to redirect outgoing TCP connections to a Proxy Service that runs as a separate application. The proxy service can query the original destination details using the SIO_QUERY_WFP_CONNECTION_REDIRECT_RECORDS for TCP or using IP_WFP_REDIRECT_RECORDS for udp.

Is this something that is currently supported?

**Comment by basil00** [comment]
Sorry for late reply.

Basically, these kinds of extensions would be a lot of work to implement, and might require a major API redesign, so not likely to be supported anytime soon.  One issue is that the WinDivert API design is stateless, meaning that the driver forgets about each packet it sends to userspace, which significantly simplifies the design.  For connection oriented extensions, usually this means the driver must remember state across API calls, and must handle all cases where the usemode application misbehaves/crashes/etc.  Basically, a lot more complexity.
