### ISSUE TITLE
An equivalent of WinDivertSend for socket layer

### ISSUE THREAD

**Issue by T-640** [basil00/Divert#272]
Hello!

As far as I understand, socket layer and network layer work in different ways, please correct me if I understand it wrong:

For the network layer, a handle is opened, WinDivertRecv is called, user code does something with data and dispatches it via WinDivertSend. In between these recv and send calls OS “patiently waits” for the user code to finish working with data, and continues delivering packet where it is supposed to go afterwards.

For the socket layer, a handle is opened with two mandatory flags WINDIVERT_FLAG_RECV_ONLY and WINDIVERT_FLAG_SNIFF  (otherwise socket event is blocked), WinDivertRecv is called, user code does something with data. It appears that unlike the network layer, here user code can do nothing to stop or otherwise delay the socket event due to WinDivertSend not being applicable in this case. So what to do with socket event can be decided only during the WinDivertOpen call.

On its own this does not seem like a problem. However, a certain thing worries me when trying to limit traffic capture only to packets that belong to a certain process. I do it this way:

1) Collect process ID;
2) Open handle for socket layer and supply the process id to it;
3) When socket layer event arrives collect IP address and port from it;
4) Given the collected address and port open handle for network layer.

This works, but I can’t help it but think that I might lose a couple of first packets coming from or to the monitored process. Because once socket event happens there is no way for me to delay it due to WinDivertSend not working at this layer. That means that while my program frantically tries to open the handle for the network layer, the process being monitored continues its execution as if nothing happened. That means that process can potentially get to the point of sending or receiving packets before my code opens the handle for network layer. And thus some of the first packets could be missed.

Would that be possible to make WinDivertSend to work with socket layer?

If this worked, I could capture the socket event, prepare the handle for network layer, and once its done call WinDivertSend for the socket layer. The monitored process would resume its network operations and my code is already prepared to handle the incoming packets.

**Comment by basil00** [comment]
> In between these recv and send calls OS “patiently waits” for the user code to finish working with data

This is not quite accurate.  After `WinDivertRecv()`, the kernel essentially has forgotten the packet ever existed.  If the user application re-injects it, then it is treated as a new packet.

Essentially, WinDivert uses a stateless design, which helps keep it (relatively) simple.

> And thus some of the first packets could be missed.

Yes, there is a race condition under this design, in that some packets could be sent before your application opens the handle.  However, this problem might be solvable with a bit of engineering.  For example, to block/allow TCP connections based on processID, you can:

1. Open handles on the `SOCKET` (for `CONNECT`) and `NETWORK` (for TCP syn) layers.
2. Wait until *both* the `CONNECT` and syn are received by user application.  (Note they can arrive in any order, so one needs to be stored while waiting for the other).
3. If the processID is allowed, then resend the syn.  Else if not allowed, reset the connection.

See [the Tallow source code](https://github.com/basil00/TorWall/blob/master/redirect.c) for similar ideas (see `pend_syn`/`pend_connect`).

> Would that be possible to make WinDivertSend to work with socket layer?

It is "possible" but not likely anytime soon.  It would require WinDivert to track state (pending connection and waiting for a verdict from the user app), which adds a lot of complexity.

**Comment by T-640** [comment]
What about UDP, is there any possible workaround for it too?

**Comment by basil00** [comment]
It is the same basic process, except with UDP there is no general way to filter the first packet in a flow, unlike TCP with syn packets.

This can be handled by capturing all UDP packets and checking for new flows, although this is not that efficient.

**Comment by T-640** [comment]
That is what I was worried about, having to listen to all the traffic. I suppose each time a new flow is discovered I could reopen this handle that captures all UDP packets, adding another “localAddr != x.x.x.x and localPort != yyy” to the filter string. That way I could avoid lots of redundant user/kernel mode context switching, making this method more efficient, right? I would end up with a very long filter though, with lots of expressions like that. Would that incur a significant performance impact (network-flow-wise and CPU-wise)?
