### ISSUE TITLE
Is windivert detetctable?

### ISSUE THREAD

**Issue by abusalaa7** [basil00/Divert#274]
I'm trying to use the netdump example to analyze traffic of a program on my computer. I modified it a little bit to print only the address and port instead of the full packet. The program seems to have added some anti-sniffing counter measures and now it crashes if the netdump program is running.

I modified the program to use the WINDIVERT_FLAG_RECV_ONLY mode but that didn't help.
1) in the sniffing mode (WINDIVERT_FLAG_SNIFF), is the copied/injected packet modified in any way?
2) in the receive only mode, is there a way to detect that windivert is running? Does it turn on a win32 api flag for example that is accessible to other programs?

Thanks in advance.

**Comment by basil00** [comment]
Yes, WinDivert can be easily detected.  In fact, the 2.X.Y versions allow other programs to query the WinDivert driver to see what other programs are using WinDivert and what the filters are.  But even for older versions, it is possible to detect what programs are using WinDivert by other means, see [WinDivertTool](https://github.com/basil00/WinDivertTool).

I am aware of some anti-cheat systems that refuse to run the game if WinDivert is detected.

> in the sniffing mode (WINDIVERT_FLAG_SNIFF), is the copied/injected packet modified in any way?

No, the original packet is allowed to continue without any modification.  However, WinDivert can still be detected.

> in the receive only mode, is there a way to detect that windivert is running?

Same as above, WinDivert can still be detected.
