### ISSUE TITLE
How to obtain subinterface index?

### ISSUE THREAD

**Issue by T-640** [basil00/Divert#275]
The documentation tells to consult the IP Helper API to get the interface and subinterface indexes. This is definitely true for the interface index, even multiple ways to do that. As for the subinterface index, I am not so sure. It would seem there is not a single function there that is supposed to deliver it. Subinterface is barely mentioned in the Microsoft documentation, there are some enumerations and functions that take this index as an input argument, and most are related to Windows Filtering Platform drivers anyway, not the IP Helper API, and that’s pretty much all there is. Is it even supposed to be obtained via the user mode API?

I realise that WinDivertRecv delivers it when some packet arrives, but I need to work without its assistance.

**Comment by basil00** [comment]
WinDivert passes the sub-interface index because it is required by the underlying WFP functions, but I am not sure how/where to get it. This question is probably best asked to a Windows programming forum rather than here.

**Comment by T-640** [comment]
It has been awhile now since I had asked about this on Windows forum and StackOverflow, no answer. It appears that whatever this **sub**interface index is, it belongs to Windows Filtering Platform exclusively. Considering that it is mostly kernel mode API, I am out of options for my user mode code.

Getting it from WindivertRecv() call helps only if the task is to modify existing packet. But construction of a completely new packet becomes extremely difficult and unreliable.

Is there anything you can do from your side? Like adding something similar to this:
```c
DWORD GetSubInterfaceIndex (DWORD interface_index);
DWORD GetSubInterfaceIndex (char* ip_address);
```
