### ISSUE TITLE
Win10 Driver digital signing error

### ISSUE THREAD

**Issue by jagt** [basil00/Divert#276]
Hi!

I'm updating [clumsy 0.3](https://github.com/jagt/clumsy) to WinDivert 2.2. There's reporting of driver verification error which I can not reproduce, nor have any clue how to work around that :(

See: <https://github.com/jagt/clumsy/issues/84>

Have you guys run into these before? Thanks in advance!

**Comment by basil00** [comment]
Sorry for the late reply.  Yes, this is a known problem and it seems that switching to one of the other versions of the signed driver will fix the issue for most users.  See the A/B/C variants here: https://github.com/basil00/Divert/releases/tag/v2.2.0

**Comment by jagt** [comment]
Hi. I figured that I can ship multiple builds of it so that if one's having problem, just let them switch to the other.
Is that correct?

Also thanks a lot for the info !

**Comment by basil00** [comment]
Yes you can do that.  What is unclear to me is how widespread the problem is, as I have never been able to reproduce the problem.
