### ISSUE TITLE
WinDivertRecvEx packet delimeter

### ISSUE THREAD

**Issue by kayoub5** [basil00/Divert#282]
I am trying to use the `WinDivertRecvEx` API in batch mode, and it states that
> The received packets are packed contiguously (i.e., no gaps) into the pPacket buffer

That sound good, question is how do I tell where does each packet end/start in the pPacket ?

**Comment by basil00** [comment]
Basically, you parse the first packet to get the first packet's length, which gives you the offset to the second packet.  Then you parse the second packet to get the second packet's length, and so forth.

You can also use [`WinDivertHelperParsePacket`](https://github.com/basil00/Divert/wiki/WinDivert-Documentation#divert_helper_parse_packet) to automate this process.  Specifically, you can iterate over all of the packets in the buffer using the following loop:

    while (WinDivertHelperParsePacket(pPacket, packetLen, ..., &pPacket, &packetLen))
    {
        ...
    }
