### ISSUE TITLE
How To Get HTML Body of Parsed Packet?

### ISSUE THREAD

**Issue by titus-shoats** [basil00/Divert#287]
Hello im trying to get the HTTP/HTML Body of a  parsed packet request using webfilter.exe. Is there any way to achieve this. Inside BlackListPayloadMatch(PBLACKLIST blacklist, char* data, UINT16 len), I see theres a pointer to data.  Is there a way to parse the packet, and get the html contents. When I printf the data char pointer, I see the following, and unreadable characters that are also showing. This is a http site (example.com)
    static BOOL BlackListPayloadMatch(PBLACKLIST blacklist, char* data, UINT16 len)
   {
    static const char get_str[] = "GET /";
    static const char post_str[] = "POST /";
    static const char http_host_str[] = " HTTP/1.1\r\nHost: ";
    char domain[MAXURL];
    char uri[MAXURL];
    URL url = { domain, uri };
    UINT16 i = 0, j;
    BOOL result;
    HANDLE console;

    printf("DATA %s:  ", data);
    .......
   }

![Capture](https://user-images.githubusercontent.com/12973004/135355558-0e861bc5-bfa0-4091-893a-498ee23807b5.PNG)

Host: www.example.com
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
If-None-Match: "3147526947+ident+gzip"
If-Modified-Since: Thu, 17 Oct 2019 07:18:26 GMT

**Comment by basil00** [comment]
It is not easy to get the HTTP body at the network layer as the data will be split over multiple packets.  It would be necessary to reconstruct it by stitching individual packets together.  The same problem exists even for HTTP headers, but the `webfilter.exe` sample program simply assumes the header is within a single packet, which is true most of the time.

A better way would be to use something like `streamdump.exe` to redirect the HTTP stream to a socket, then parse it from there.

Also, raw HTTP is very rare these days.  Almost all web traffic is HTTPS.
