### ISSUE TITLE
Simulating IPv6 Network

### ISSUE THREAD

**Issue by trudyhood** [basil00/Divert#289]
I know it may not relate to WinDivert, but I am using WinDivert instead of a virtual adapter to create a VPN. Everything works great and was handy till I tried to tunnel IPv6 packet over IPv4. unfortunately, I had no success for tunneling IPv6 packet by WinDivert. Actually, WinDivert does the job if the user is already connected to an IPv6 network but the problem is that Windows doesn't try to send Pv6 packets when a user doesn't have already connected to an IPv6 network even if an IPv6 is already configured on the local machine.
It looks like it requires a configuration for windows or some network discovery protocol looking for an active IPv6 router that is beyond my knowledge. 

In android, the built-in VpnService does all the jobs and I can capture all packets and tunnel them even when a user is not connected to any IPv6 network, so they can access IPv6 sites over IPv4.

I am wondering is it possible to add an extra feature to WinDivert to simulate an IPv6 network so I can capture the IPv6 packets and establish the tunnel?

**Comment by basil00** [comment]
If I understand the problem correctly, it would be necessary to create a new adapter with IPv6 enabled?  This would be beyond the scope of WinDivert as it would require a different type of driver (Miniport or NDIS filter driver I think).  "Traditional" VPN implementations do use this type of driver (TUN) and do install a new interface/adapter, so can probably support IPv6 over IPv4.

So I am not sure much can be done about it other than not supporting IPv6 if Windows is not configured to use it.
