### ISSUE TITLE
WinDivert fails to respond on Nautix hypervisor

### ISSUE THREAD

**Issue by romanblachman** [basil00/Divert#290]
It appears that WinDivert fails to open (function doesn't return and hangs indefinitely, hard reboot required) when running on Nautix hypervisors. We tested the WinDivert tools from the command line, and they are just hanging indefinitely and hard reboot is required.

WinDivert driver reports as RUNNING.

Linux: centos 6.2
Kernel: nutanix ahv 5.15.1
VM: windows 2016

Wondering if there is anything we can collect from the VM to help figure this out.

**Comment by basil00** [comment]
You probably need to do something like this to get a crash dump: https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/how-to-force-a-diagnostic-memory-dump-when-a-computer-hangs/ba-p/257809

**Comment by romanblachman** [comment]
Turns out this is working on another customer with Nautix which tells me it has to do with configuration / version. Will reopen if reproducts.
