### ISSUE TITLE
Support subnet of IP networks in filter #54

### ISSUE THREAD

**Issue by zvibazak** [basil00/Divert#291]
Can we add support to support IP subnets on filter?

For example:
`HANDLE handle = WinDivertOpen("outbound and ip.DstAddr = 8.8.8.0/24");` - mean that the destination address is in the subnet `8.8.8.0/24`.

Thanks

**Comment by basil00** [comment]
It is possible to implement the desired filter as follows:

        outbound and ip.DstAddr >= 8.8.8.0 and ip.DstAddr <= 8.8.8.255

It would be nice to support the standard subnet/slash syntax, but this is not implement yet.

**Comment by zvibazak** [comment]
Thanks a lot!
For me it's satisfying, so i'm closing the issue.
