### ISSUE TITLE
Key from Access Server points to the public IP

### ISSUE THREAD

**Issue by bizzbyster** [basil00/Divert#295]
![image](https://user-images.githubusercontent.com/4001792/153272777-933de6c1-dc52-4ff0-b8c8-7fc626ed6ef1.png)

When I create an access key and add it to my VpnHood client, my client tries to connect using the public IP address. How do I configure the client to use the private IP?

Thanks!

**Comment by basil00** [comment]
Please report the issue here: https://github.com/vpnhood/VpnHood
