### ISSUE TITLE
error: failed to open WinDivert handle (err = 2)

### ISSUE THREAD

**Issue by timegoer** [basil00/Divert#303]
WinDivert FAQ said this error wa due to Either one of the WinDivert32.sys or WinDivert64.sys files were not found. But it does not give a solution.How can I solve this problem? I downloaded the latest zip from the official website WinDivert including WinDivert64.sys.

**Comment by basil00** [comment]
The driver files need to be in the same directory as the application/dll.

If they **are** already in the same directory, then try manually deleting the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert` registry entry and reboot.

If that still does not work, then I'm not sure, and I'll need more details.
