### ISSUE TITLE
WinDivert recognised as cheat by Warzone

### ISSUE THREAD

**Issue by idan1109** [basil00/Divert#304]
Hello basil00. First of all thank you for your beautiful work. I'm writing a python app for a firewall project but with some games i noticed that every time the firewall is up the game is crashing (for example on Warzone).
So what i did i thought that i could change the service name so that it isn't recognised anymore by the anti-cheat. I've edited your lib and recompiled the 1.3 version however i cannot manage to make it work.  Do you have any idea? i edited WINDIVERT_DRIVER_NAME but no luck.....

**Comment by basil00** [comment]
I cannot help with anything related to bypassing WinDivert detection, unfortunately.  WinDivert is intended to be detectable.

Depending on how the anticheat works, it is also possible that it detects any WFP callout driver regardless of the name.
