### ISSUE TITLE
Can WinDivert read ARP responses?

### ISSUE THREAD

**Issue by tobias-tengler** [basil00/Divert#306]
I'm trying to send ARP requests and capture the result using WinDivert. But I don't seem to have any luck. It captures ICMP packets just fine, but I can't seem to access ARP responses, even though I can see them with Wireshark.

is there a limitation I am unaware of?

**Comment by basil00** [comment]
No, it is not supported by the underlying WFP framework on which WinDivert is built.  See #269.
