### ISSUE TITLE
When passthru is running, Windows Defender firewall works improperly.

### ISSUE THREAD

**Issue by xiaolei20190417** [basil00/Divert#307]
hi basil00:

When passthru is running, Windows Defender firewall works improperly.
windows server 2016
divert version: WinDivert-2.2.0-A

1. Add firewall inbound Rules: block all tcp port except 3389;   (1-3388,3390-65535)
2. Add firewall outbound Rules: block all tcp port;
3. start Windows Defender firewall;

When passthru is not running, mstsc.exe can connect to Server 2016; 
When passthru is running, mstsc.exe can not connect to Server 2016 anymore;
I'm sure Windows firewall block the connecttion and block logs is in the firewall logs;
Maybe the re-inject parkets mechanism is incompatible with Windows Defender firewall.

Is this a bug?

**Comment by basil00** [comment]
> I'm sure Windows firewall block the connecttion and block logs is in the firewall logs

To clarify, is it confirmed that Windows Defender is actually blocking the re-injected traffic?  If so, what do the logs say?

**Comment by basil00** [comment]
No further information, so closed for now.
