### ISSUE TITLE
Why socketdump.exe cannot block mstsc.exe?

### ISSUE THREAD

**Issue by davidcao2000** [basil00/Divert#308]
I want to block some applicatons' network activity by WinDivert.  So I try such a command line: 
socketdump --block processId==1234
where 1234 is process ID of mstsc.exe (Windows remote desktop client). But nothing happened. mstsc is still working as usual.  
Why? socketdump.exe can block firefox, FileZilla(an FTP client), but cannot  have an effect on mstsc. 
My WinDivert version is 2.2
Thanks a lot.

**Comment by basil00** [comment]
The `socketdump.exe --block` mode will block *new* socket events.  So my guess is that the socket it already open, meaning that there are no new events, so it is not blocked.
