### ISSUE TITLE
Inbound/all receiving packets

### ISSUE THREAD

**Issue by NewbieXV** [basil00/Divert#311]
Hello Basil00, I have been using a application built from Windivert also known as clumsy. I was wondering why doesnt inbound work whenever I build it from source? Some people have said you’d need to add the preset manually into the coding but I tried everything, maybe you could help?

**Comment by basil00** [comment]
What is the filter string used by clumsy?  WinDivert should work with either inbound or outbound traffic.

**Comment by NewbieXV** [comment]
This is what it says 

int divertStart(const char *filter, char buf[]) {
    int ix;

    divertHandle = WinDivertOpen(filter, WINDIVERT_LAYER_NETWORK, DIVERT_PRIORITY, 0);
    if (divertHandle == INVALID_HANDLE_VALUE) {
        DWORD lastError = GetLastError();
        if (lastError == ERROR_INVALID_PARAMETER) {
            strcpy(buf, "Failed to start filtering : filter syntax error.");
        } else {
            sprintf(buf, "Failed to start filtering : failed to open device (code:%lu).\n"
                "Make sure you run clumsy as Administrator.", lastError);
        }
        return FALSE;
    }
    LOG("Divert opened handle.");

**Comment by basil00** [comment]
It depends what the value of `filter` string is, which specifies what traffic should be diverted.  I'd assume the `filter` string excludes inbound traffic.
