### ISSUE TITLE
Will the packets successfully sent by WinDivertSend be dropped by the MiniPort (SSTP) driver?

### ISSUE THREAD

**Issue by asbai** [basil00/Divert#313]
We found that packets successfully sent by `WinDivertSend` to a MiniPort (SSTP) VPN NIC tx queue seem to have a probability of being dropped unexpectedly (failed to be receivedby the outer SSTP/ TCP connection).

The packets we send to the VPN network card through `WinDivertSend` are intercepted from the tx queue of the MiniPort Adapter through `WinDivertRecv`. We send it as-is via `WinDivertSend` without any changes. And we can ensure that we are the only interceptor in the test environment, and no other application or firewall processes the packets on this network card.

We have never encountered such a situation when writing packets to a tuntap virtual NIC device on linux: as long as the write is successful, the packet will not be discarded by the underlying driver. So we want to confirm: on windows, a packet that is well-formed and successfully inserted into the underlying NIC's tx queue via `WinDivertRecv` will be silently dropped by the NIC driver?

Thanks :-)

**Comment by basil00** [comment]
> So we want to confirm: on windows, a packet that is well-formed and successfully inserted into the underlying NIC's tx queue via `WinDivertRecv` will be silently dropped by the NIC driver?

It should not be dropped, but it is also not unknown for (buggy) NIC drivers to misbehave with packets originating from WinDivert.

To confirm, you can try capturing the WinDivert re-injected packet using Wireshark and check for errors.  If Wireshark does not report any error, then I'm inclined to think this is a bug in the NIC driver.  If it does find errors, then please reopen the issue.
