### ISSUE TITLE
Trying to tunnel packets but getting potentially reassembly errors?

### ISSUE THREAD

**Issue by sswrk11** [basil00/Divert#314]
Trying to tunnel packets between two endpoints, i perform ip in ip on the original packet to redirect to new destination however i see a lot of 
![image](https://user-images.githubusercontent.com/105488485/179749861-36f4dd3c-133c-4e5c-b74b-867d57e25066.png)

and my download/upload on my client machine becomes really slow, it works but its been capped somehow and i see alot of dup acks.

Anything obvious that youve come across before @basil00?

**Comment by sswrk11** [comment]
Looks like the tls handshake fails because the fragementation must have messed up as its reading invalid values:

![image](https://user-images.githubusercontent.com/105488485/179857343-e9249877-4279-44be-991f-355c76317c58.png)

**Comment by sswrk11** [comment]
Not sure why its fragmenting wrong...

**Comment by basil00** [comment]
No, WinDivert itself does not fragment packets, and I've not implemented tunneling in a long time.
