### ISSUE TITLE
IOCompletionCallback not work in RecvEx

### ISSUE THREAD

**Issue by xljiulang** [basil00/Divert#318]
First of all, thank you very much for this project!
I wanted to bind the "Overlapped" at WinDivertRecvEx to a complete callback，so the "hEvent" field of "Overlapped" must remain null. 
When I call WinDivertRecvEx  the function returns false and last error code  is 997, but the io completion callback is not called.
I wonder what went wrong:

**Call WinDivertRecvEx**
``` c#
var overlapped = new Overlapped(offsetLo: 0, offsetHi: 0, hEvent: IntPtr.Zero, asyncResult);
var nativeOverlapped = overlapped.UnsafePack(completionCallback, packet.Buffer);

var flag = WinDivertNative.WinDivertRecvEx(this.handle, packet.Buffer, packet.Buffer.Length, ref length, 0, ref addr, ref addrLength, nativeOverlapped);
if (flag == true)
{
    packet.Length = length;
    taskCompletionSource.SetResult(length);
    return taskCompletionSource.Task;
}

var errorCode = Marshal.GetLastWin32Error(); 
if (errorCode == 997)
{
    return taskCompletionSource.Task;
}

var exception = new Win32Exception();
taskCompletionSource.SetException(exception);
return taskCompletionSource.Task;
```

io completion callback
```
private unsafe static void IOCompletionCallback(uint errorCode, uint numBytes, NativeOverlapped* pOVERLAP)
{
    var overlapped = Overlapped.Unpack(pOVERLAP);
}
```

**Comment by basil00** [comment]
It would never be called if no packet were captured, for example.

Aside from that, I cannot really help.  I have used IO completion ports with WinDivert before, but this was a while ago and I do not remember any problem.  WinDivert handles are also ordinary Windows handles, so there is no reason why this API should not work.

**Comment by xljiulang** [comment]
Thanks for your careful reply. I found that the problem was caused by my code. Now I have solved it and used IOCP for asynchronous receiving and sending in dotnet.[WindivertController.cs](https://github.com/xljiulang/WindivertDotnet/blob/master/WindivertDotnet/WindivertController.cs)

**Comment by basil00** [comment]
Thanks for the update.
