### ISSUE TITLE
5 Tuple hash based load balacing?

### ISSUE THREAD

**Issue by Prakash-Kolandaivelu-ML** [basil00/Divert#322]
Is possible to do load balancing using the 5 Tuple(IP address(Src and Dst) ,port (Src and Dst) and Protocol similar to AF_PACKET (PACKET_FANOUT )in the before the WinDivertRecv by grouping the handles?

https://man7.org/linux/man-pages/man7/packet.7.html

**Comment by basil00** [comment]
This is a nice idea, but it would add more complexity to the driver, so I'd be reluctant to implement something like this.
