### ISSUE TITLE
Capturing packets that aren't targeting the local machine?

### ISSUE THREAD

**Issue by eylonR** [basil00/Divert#34]
Hi,

Is it possible with WinDivert to receive packets with source ip A and destination B, while I'm C but the packet was in the NIC?

I don't want to configure Windows as a router, and open an NETWORK _FORWARD layer handle.

Thanks!

**Comment by ianbannerman** [comment]
> Note that the forward layer can be confusing since some windows network services, such as the Windows NAT, generate fresh packets and they are injected on the outbound path (since they "originate" from C). This is the underlying WFP semantics that WinDivert inherits.

This explains what I am seeing. Windows NAT is on (via Internet Connection Sharing or bridging connections) and then I see packets on the outbound path. I *don't* see these packets on the forward layer in this case. Thank you for the clarification & information basil!

**Comment by basil00** [comment]
@eylonR It is really up to you to ensure the program does not crash.  If the filter is security critical, then there may be some defensive programming techniques to guard against crashing: e.g. run the filter in a separate process, restarting the filter on crash, or insert "safety net" filters with a lower priority using a different process, etc.

**Comment by eylonR** [comment]
Maybe enabling Windows NAT is also an option or it can make other security flaws? The forwarding feature for example is yes or no.
