### ISSUE TITLE
why not can not delete WinDivert64.sys

### ISSUE THREAD

**Issue by xengine-qyt** [basil00/Divert#342]
win10 x64....and can't delete even after reboot

![image](https://github.com/basil00/Divert/assets/37919215/ab3e880d-d50e-43a6-b79c-296788df0cd5)

**Comment by basil00** [comment]
Please use [WinDivertTool](https://github.com/basil00/WinDivertTool) for this kind of problem.  The tool can be downloaded from [here](https://github.com/basil00/WinDivertTool/releases).

Windows will refuse to unload a driver that is currently being used by a program (this is a Windows thing and not specific to WinDivert).  WinDivertTool will attempt to detect which program is using WinDivert and optionally kill it, allowing the driver to be unloaded.
