### ISSUE TITLE
Non-blocking use of WinDivertRecv

### ISSUE THREAD

**Issue by eylonR** [basil00/Divert#35]
Is there a way to use the WinDivertRecv API function in a non-blocking way, synchronously?

I need not to use any threads or IOCP methods, but want the flow to continue also if there's nothing to receive.

I tried to use the standard select() method to determine if there's something to read from the handle before using the receive function, but it seems to work only with regular sockets.

**Comment by prakashkolandaivelu** [comment]
WinDivertRecvEx is blocked when no packets are received on the interface. Is there any flag need to be turned on ?
Could not find anything in WinDivertSetParam also.

**Comment by bsc-inf-11-20** [comment]
> WinDivertRecvEx is blocked when no packets are received on the interface. Is there any flag need to be turned on ? Could not find anything in WinDivertSetParam also.

Anybony figured this out? Facing the same issue too.
