### ISSUE TITLE
DNS-Malformed Packet

### ISSUE THREAD

**Issue by BadBoy-a** [basil00/Divert#351]
Hi,I intercepted all DNS messages but no response was received.Through Wireshark packet capturing, I found that the packet is incorrect.After comparing with the correct packets,I found an error byte--'2e',which should have been the length.
Here is my code:

void main() {
	HANDLE handle;
	unsigned char packet[65535];
	UINT packet_len;
	WINDIVERT_ADDRESS addr;
	handle = WinDivertOpen("udp.DstPort == 53", WINDIVERT_LAYER_NETWORK, 0, 0);
	if (handle == INVALID_HANDLE_VALUE) {
		printf("WinDivertOpen error:", GetLastError());
		return;
	}
	while (1) {
		if (!WinDivertRecv(handle, packet, sizeof(packet), &packet_len, &addr)) {
			printf("WinDivertRecv error:", GetLastError());
			continue;
		}
		WinDivertHelperCalcChecksums(packet, packet_len, &addr, 0);
		WinDivertSend(handle, packet, packet_len, NULL, &addr);
	}
}

Screenshot of Wireshark:
![correct](https://github.com/basil00/Divert/assets/80302411/b6a85c16-25bc-412b-8618-8fc3e3afa3c3)
![error](https://github.com/basil00/Divert/assets/80302411/fd367949-46bb-44fc-833b-e3dc8fe8b331)

**Comment by majibow** [comment]
Have you tried the netdump.exe example program on your system? Seems to work on mine... see highlight 03 

![image](https://github.com/basil00/Divert/assets/21868469/421958fb-7314-4929-8024-8240c0bfc93e)

**Comment by basil00** [comment]
I think this is unlikely this is a WinDivert bug, or else there should be a flood of similar reports.
