### ISSUE TITLE
I don't know how to  identify icmp packets and associated process id , is there any reference for it ?

### ISSUE THREAD

**Issue by iouvxz** [basil00/Divert#352]

**Comment by majibow** [comment]
https://github.com/basil00/Divert/blob/134dd37bd0a87d3d236214e42edc1867b8911c6f/doc/windivert.html

See section filter language: filter for _icmp_ or _icmpv6_

**Comment by basil00** [comment]
To get icmp packets, you use the `NETWORK` layer.  To get the process ID, you need to use the `SOCKET` or `FLOW` layers.  Then you need to write some code to associate the two layers.  It is complex but possible.  [Tallow](https://github.com/basil00/TorWall/blob/5f1c9151037cdb4b1c685107cedc917e2c4ef8a7/redirect.c#L1135) does something like this, but for non-icmp traffic.
