### ISSUE TITLE
Appropriate way to use passthru example?

### ISSUE THREAD

**Issue by lonnietc** [basil00/Divert#356]
Hello,

I am testing out WinDivert for possible use in a project and am wondering what is the appropriate command line invocation for the passthru example?

I want to start up the passthru example on my Windows 11 Pro (x64) and then have it passthrough all of the packets on a particular active interface until I stop it as I am wanting to try and get a benchmark on how much latency the passthru example with WinDivert has in comparison to running native without WinDivert.

Any advice would be greatly appreciated.

**Comment by majibow** [comment]
`usage: passthru.exe [windivert-filter] [num-threads] [batch-size] [priority]`

You can literally just invoke passthrough without any arguments as the default is:
`passthru.exe true 1 1 0`

For a description of the args see the html api docs included in the release you downloaded.

**Comment by lonnietc** [comment]
Thanks for the information on this and I was able to get a bit more detail in the docs as well.
