### ISSUE TITLE
Why does moving of addr_len initialization outside of the infinite loop causes WinDivertRecvEx to only ever ready 1 packet?

### ISSUE THREAD

**Issue by vincenthawke** [basil00/Divert#357]
I noticed that if I change the code from:
```
    // Main loop:
    while (true)
    {
        // Read a matching multiple_packet_buffer.
        addr_len = batch * sizeof(WINDIVERT_ADDRESS);

        if (!WinDivertRecvEx(handle, multiple_packet_buffer, multiple_packet_buffer_length, &recv_len, 0, addr, &addr_len, nullptr))
        {
            fprintf(stderr, "warning: failed to read multiple_packet_buffer (%lu)\n", GetLastError());
            continue;
        }
...
```
to:
```
    addr_len = batch * sizeof(WINDIVERT_ADDRESS);
    // Main loop:
    while (true)
    {
        
        if (!WinDivertRecvEx(handle, multiple_packet_buffer, multiple_packet_buffer_length, &recv_len, 0, addr, &addr_len, nullptr))
        {
            fprintf(stderr, "warning: failed to read multiple_packet_buffer (%lu)\n", GetLastError());
            continue;
        }
...
```
Should `addr_len = batch * sizeof(WINDIVERT_ADDRESS);` not evaluate to the same value regardless of if it is initialized inside or outside the while loop? Instead it changes `addr_len` to always be `80`, which then logically means that `WinDivertRecvEx` can't receive more than one packet.

**Comment by basil00** [comment]
As per the docs, `WinDivertRecvEx` will change the value to reflect the actual number of packets received:

* `pAddrLen`: Initially, a pointer to the length of the pAddr buffer in bytes. This value is updated to the total bytes written to pAddr.

Re-initializing `addr_len` once per loop was correct.

**Comment by bsc-inf-11-20** [comment]
@basil00 @vincenthawke  am also getting the same problem, i used the code example in passthru.c as recommended in the documentation guiding batchmode usage but i also get a result of 80 packets. is there anybody able to get changing results if there batchmode really works? i just cant see what am missing
