### ISSUE TITLE
Monitoring Packets from a specific NIC

### ISSUE THREAD

**Issue by cdev1011** [basil00/Divert#359]
Can WinDivert Monitor packets coming from a specific NIC on a machine? Assuming there are two network connections available on the machine for eg. "Ethernet 2 and Ethernet 3"

**Comment by basil00** [comment]
Yes, each NIC will have a different `IfIdx` which can be used to filter traffic.  Use the Windows IP Helper API to map specific NICs to `IfIdx` values.
