### ISSUE TITLE
Switch Port mirroring

### ISSUE THREAD

**Issue by marianogenovese** [basil00/Divert#36]
There are any restriccions using windivert (v1.1.7) connected to a switch with port mirroring? because i'm using an app with windivert and dont receive any package. I'm also using a app with winpcap and with this application the packets are received.

**Comment by basil00** [comment]
There should not be any problem.  Are you using the FORWARD layer?

**Comment by marianogenovese** [comment]
Im using WINDIVERT_LAYER_NETWORK and WINDIVERT_FLAG_SNIFF as arguments in open function.

**Comment by basil00** [comment]
I do not know.  Winpcap should not affect WinDivert.  You may need to post more information.

**Comment by marianogenovese** [comment]
Im using a pc "A" with Windows 8.1 with wireshark installed, this pc "A" is connected to a switch with port mirroring, the port where "A" is connected, is configured as receive port in the port mirroring switch configuration, therefore "A" receive a copy of all packages generated from another pc "B" connected to the same switch. Running a continuous ping in "B" and runing wireshark in "A" i see a copy of the packages generated from "B", in "B" i navigate to a web page and in wireshark in "A" i see a copy of the tcp packages related to this action. Then, i need to receive a copy of this packages generated from "B" with and app using windivert running in "A" without winpcap, but don't work. I develop an app with windivert using forward layer, running this windiver app in "A" alone don't receive any package but running whireshark and my windivert app in the same pc "A" at the same time, the windivert app receive the packages, as I said previously seems like windivert driver reacts with winpcap.

Please, tell me is this information is usefull or if you need more info, what type of info do you need.

Thanks.

**Comment by basil00** [comment]
Unfortunately I do not know the reason for this behavior.  I can only speculate that somehow the winpcap driver is changing something that is causing the packets to flow through the WFP forward (and/or inbound?) path.  Winpcap is a NDIS protocol driver, so it really should not affect WinDivert.

**Comment by marianogenovese** [comment]
I understand, but basically my question is using windivert alone without any instalation of winpcap windivert dont receive a copy of the packages generated by the switch.

Thx,

**Comment by sardasanat** [comment]
I have issue wrt switch port mirroring and unable to find the solution. Windivert is running on PC which is configured to receive packets from the mirrored port on the switch. I am unable to receive any mirrored packets either using FORWARD LAYER or NETWORK LAYER. It does'nt give any error, After running app which uses windivert, just does'nt receive any packets. if run Wireshark on same PC as WinDivert can receive mirrored packets successfully. Using ICMP for testing. My environment is Windows 10, Divert 1-2-rc. Tried different filters (true, icmp, ip.Dst==,ip.Length,etc) Couple of times the PC using Windivert hanged and had to do hardware restart. Could you let me know what I am doing wrong ?

**Comment by mosesBD** [comment]
maybe windivert receives the data when you activate wireshark because wireshark enables promiscuous mode which allows the Ethernet layer to receive packets not destined to it's mac address

**Comment by basil00** [comment]
@mosesBD That is probably correct.

**Comment by mosesBD** [comment]
windivert has a wrapper in python called pydivert (you can find it on github).
i also found this python sniffer that enables promiscuous mode with python.
https://github.com/zeigotaro/python-sniffer/blob/master/snifferCore.py.
note that interface stays in promiscuous mode only until the socket is open.
you can combine these 2 to write your program to sniff mirrored packets.

**Comment by basil00** [comment]
@mosesBD's explanation is almost certainly correct, so time to close this ancient issue.
