### ISSUE TITLE
Inbound packet IPv4_HDR.Protocol empty and addr.TCPChecksum==0 addr.UDPChecksum==0

### ISSUE THREAD

**Issue by jeffry1829** [basil00/Divert#366]
I've used PCAP to capture inbound tcp/ip packet and succed.

However, when I want to modify the packet, I found that, if I set windivert_filter to "inbound and tcp", the ip_hdr.Protocol is empty and addr.TCPChecksum==0, UDPChecksum==1

Since I'm a newbie in sniffing packets, is that normal?

I used exactly the same method to parse packet data from raw packet in PCAP and WinDivert. The only difference is that, in PCAP, I need to parse Ethernet also, while in WinDivert, I check addr.IPChecksum==1, and then parse the packet from IP layer.

Is that the correct way? I just cannot get same inbound packet from PCAP and WinDivert.

Thanks for any help!

**Comment by jeffry1829** [comment]
I found that the addr.IPChecksum == 1 is not a good way to check if it's IPv4, and ip_hdr.Protocol is not empty, it's correct TCP protocol number.

I think the problem now is that seem like Checksum==0 is the normal state? And how do I know if it's IPv4 when WinDivertRecv?

Since the problem's solved, I'll close the issue

**Comment by basil00** [comment]
All packets read at the `NETWORK` layer will be either IPv4 or IPv6, and a packet will be IPv4 if `addr.IPv6 == 0`.  You should not use `addr.IPChecksum` since it is possible for an IPv4 packet to not have a checksum.
