### ISSUE TITLE
WinDivert 1.2 wishlist

### ISSUE THREAD

**Issue by basil00** [basil00/Divert#37]
Here are some ideas for WinDivert1.2 in 2015:

* Extend WinDivertRecvEx() and WinDivertSendEx() so that they can receive/send multiple packets at once.  For example, by passing in a special flag to WinDivertRecvEx(), the driver will fill the buffer with as many packets that (a) will fit, and (b) are available.  Likewise, via a special flag, the buffer passed to WinDivertSend() can contain several packets that are to be all sent at once.  The idea is to reduce the number of context switches required, and thus should be faster.  I am not sure how difficult this will be to implement.
* Make WINDIVERT_FLAG_NO_CHECKSUM the default behavior.  Instead, the driver never calculates checksums, and it is up to the user to call WinDivertHelperCalcChecksums() manually.  This will reduce overheads for users who do not think to pass the NO_CHECKSUM to WinDivertOpen(), but call CalcChecksums() anyway.  This seems to be the majority of users.

Comments?  Any other proposals?

**Comment by eylonR** [comment]
I really really hope for a way to capture packets that are not targeting the local machine, without the requirement to enable the packet forwarding option on Windows. If it's not that hard, I also can try to help developing it.

**Comment by basil00** [comment]
@eylonR What do you mean "enable the packet forwarding option on Windows"?  This does not seem related to WinDivert.

**Comment by eylonR** [comment]
I mean that I hope for a way to capture packets that aren't targeting the local IP address without using the forwarding layer, which is risky when the user-space app failed.

**Comment by basil00** [comment]
I probably still do not understand.  Any WinDivert filter installed by a program is removed once the program terminates (including if it crashes).  This doesn't have anything to do with the forward layer,.

**Comment by eylonR** [comment]
But sometimes you want to capture packets that just passes the NIC, not only packets that targeted to your computer, something like promiscuous mode. In order to do that, you have to enable the Windows forwarding option and to use the forwarding layer.

**Comment by basil00** [comment]
> something like promiscuous mode

WinDivert is all about packet blocking or filtering.  The only way to block a packet is if it is actually passing through your machine, and therefore you need to configure the machine as a router.

**Comment by ianbannerman** [comment]
Second suggestion is a great idea, the current style tripped me up initially as well.

Is it possible to support the network layer and forward layer without two WinDivertOpen calls? 

Is it possible to support Layer 2 filtering? http://msdn.microsoft.com/en-us/library/windows/hardware/hh440262(v=vs.85).aspx


Please forgive me if any of these questions are obviously silly; I still have a lot to learn :)

**Comment by basil00** [comment]
Thanks for the suggestions.

> Is it possible to support the network layer and forward layer without two WinDivertOpen calls?

This was my original intention some time ago.  However, most applications do not care about forward packets so I think it is a good idea to keep them as a separate case.

> Is it possible to support Layer 2 filtering?

I also want this.  However, WFP Layer 2 filtering is only supported on Windows 8 and later.   The other thing is that Layer 2 headers can already be derived from the IfIdx and the IP Helper API.  It is not quite as convenient, but it is possible nevertheless.

**Comment by mhils** [comment]
Let me add a late wish: Currently, the limitation section states that *the forward layer does not interact well with the Windows NAT. [..] As a general principle, you should not try and mix WinDivert at the forward layer with the Windows NAT implementation.*
Do you see any viable way (let it be Win8 only...) how one could work around this?

**Comment by basil00** [comment]
The fundamental problem is that both the NAT and WinDivert are trying to intercept the same packet and are therefore in competition.  I don't see a way around this.

**Comment by ianbannerman** [comment]
Hey Basil! Question - what happens when we bump our filter weight as WinDivert above the Windows NAT filter weight? It seems like that would skate us straight through this competition for the packets. 

The NATTraversal project ( http://www.rtsdd.ru/NATTraversal.aspx ) found that the NAT implementation in Windows uses a filter with weight of 0xFFFFFFFFFFFFFFFD. If we load WinDivert at weight E or F above it, we should get those packets first, no competition. WinDivertOpen caps the priority as a UINT16, so I'd need to recompile the driver to test this, but on first read this seems fair. 

I'm far from an expert here though haha :). What do you think?

**Comment by basil00** [comment]
The WinDivert priority does not affect the WFP sublayer weight (which determines whether WinDivert filters are collectively before or after the NAT).  WinDivert already inserts itself at the highest weight, so *should* see packets before the NAT.  It has been a while since I've looked at this though.

I think it is *possible* to combine WinDivert and the NAT -- the problem is that it requires reasonably detailed knowledge of how things work and interact (with both WinDivert and the NAT writing packets), which trips up a lot of users.

**Comment by ianbannerman** [comment]
Maybe I've read the source incorrectly then? Looking at windivert_install_callout(), I see weight set as such:

weight = WINDIVERT_FILTER_WEIGHT(context->priority);

And then filled in the FWPM_FILTER0 struct as:
    filter.weight.type               = FWP_UINT64;
    filter.weight.uint64             = &weight;

But priority is a UINT32 value filled from a UINT16 passed in via WinDivertOpen, so making a big assumption that I've read this correctly (I'm very new to the windivert souce :)), I don't think we're above 0xFFFFFFFFFFFFFFFD?

**Comment by ianbannerman** [comment]
On further look, I'm not sure competition between WinDivert and the Windows NAT plays a role here. I recompiled the WinDivert driver with a 0xFFFFFFFFFFFFFFFF weight but did not notice a change in packets seen. But, I'm also not missing any packets. With the Windows NAT running (via ICS), and with this approximation of the network, this is where I see packets:

Traffic from things connected to the Windows NAT (IPs between 192.168.25.2-255), WinDivert sees:
Outbound traffic to external servers on WINDIVERT_NETWORK_LAYER_FORWARD
Outbound traffic to Windows NAT itself (192.168.25.1) on WINDIVERT_NETWORK_LAYER

WinDivert *also* sees the exact same outbound traffic to external servers on WINDIVERT_NETWORK_LAYER but as coming from the IP of the computer running the NAT (10.1.1.5, 192.168.1.2, or whatever it may be). One difference here is that this is *all* outbound traffic from devices behind the NAT; on NETWORK_LAYER_FORWARD you see the specific IP assigned by the NAT and can distinguish between devices. Here all traffic is sourced from the 10.1.1.5/192.168.1.2/or whatever NAT computer.

Inbound traffic from external servers to things connected to the Windows NAT shows up on WINDIVERT_NETWORK_LAYER with the appropriate destination IP addresses.

So..... WinDivert is able to and does capture all packets. For me, I just need to open an extra WINDIVERT_NETWORK_LAYER_FORWARD handle for outbound-to-external-servers traffic from things behind the NAT if I'm not ok with seeing that traffic bundled together as coming from the NAT computer itself.

Not sure why I didn't figure that out earlier and got bogged down with filter weights! But I think I'm set now :). Sorry to derail things Basil!

**Comment by basil00** [comment]
It's confusing because there are two levels of weights: the WFP filter weight and the WFP sublayer weight.  Each sublayer contains several filters, and WinDivert and the NAT are each its own sublayer.  Therefore it is the sublayer weight that determines whether WinDivert or the NAT sees the packet first.  The filter weight (which corresponds to the WinDivert priority) merely determines the WFP filter weight within the WinDivert sublayer.

As I said, I think it is possible to use WinDivert and the NAT at the same time, it is just a bit tricky, and requires some low-level knowledge about how things work.  (It's not officially "supported" in the sense that "*basil cannot help you*" rather than not being technically possible). For example, the NAT injects modified packets on the WFP outbound path (for reasons I am not sure about), which is why WInDivert sees the packets on WINDIVERT_NETWORK_LAYER, rather than the FORWARD layer.  Inbound packets in the other direction are also on the non-FORWARD layer.

**Comment by ianbannerman** [comment]
Ah, thank you!! That makes a lot of sense. Much appreciated :)

**Comment by Phyxion** [comment]
Just wanted to say that I'm fully behind making WINDIVERT_FLAG_NO_CHECKSUM the default.

**Comment by basil00** [comment]
I am finally working on WinDivert again...

Some additional ideas I've been thinking about and prototyping:

* Extending the WinDivert helper API with functions for compiling an evaluating filter strings.  The idea is that these functions can be used to check whether a filter string is valid, and if not, can return the cause of the error, e.g. "bad token", "syntax error" at position X.  Currently WinDivertOpen simply fails with "invalid parameter" if the filter string is invalid, which is not very helpful.
* Extending the WinDivert filter language to support if-then-else style conditionals.  I was thinking of using the C-style syntax, e.g. `(udp? udp.DstPort == 53: false) or (tcp? tcp.DstPort == 80: false)`, etc.  This will make it easier to write complex filters, a problem I noticed with Tallow.

**Comment by Phyxion** [comment]
Great to hear @basil00!

I'm not convinced that the first point belongs in an API, this is more up to the developer to write correctly. The other point sounds great :+1:

**Comment by basil00** [comment]
Some applications (such as Tallow, clumsy, etc.) employ user configurable filter strings.  It will be useful to report meaningful error messages back to the user if they write an invalid filter.

**Comment by Phyxion** [comment]
I understand but I think it should belong in those applications rather than in WinDivert as it's not very useful for WinDivert itself.

**Comment by TechnikEmpire** [comment]
Hey basil, thanks for the great lib first of all. Can I make a wish? :p would it be possible to an addition to the examples demonstrating the *Ex functions? I've seen a lot of discussion of people requesting use of them in libs that use windivert but can't find an implementation using them anywhere.

**Comment by basil00** [comment]
The WinDivertRecvEx() function is used by test/test.c at least.

**Comment by TechnikEmpire** [comment]
Thanks dude, I've never really stepped outside of ::asio for network programming, so I wanted to see it in action. :)

**Comment by basil00** [comment]
The new filter compiler + extensions has been committed to the repository.  Note however this is still a work-in-progress and has not been well tested.

**Comment by Phyxion** [comment]
Looking good! Thanks @basil00.

**Comment by basil00** [comment]
The checksums idea has been implemented.

The send()/recv() multiple packets idea seems like it is non-trivial to implement.  So I think it will be deferred to WinDivert1.3.

**Comment by Phyxion** [comment]
Thank you very much @basil00. 
Could you give some examples of the new filter? Also, will all the old filters still work? With the latest version (the signed / compiled one) I still have https://github.com/basil00/Divert/issues/26 this issue, perhaps this new filter would help?

With Windows 10 around the corner, maybe it'll be nice for 1.2 to ensure compatibility with it.

**Comment by basil00** [comment]
WinDivert1.2 is not quite ready yet.  Still need to bump the version, test and debug, update the documentation, then release WinDivert1.2.0-rc.  After a few months with no complaints, release the non-RC version WinDivert1.2.1.

The old filters will still work.  WinDivert 1.2 will be backwards compatible with the exception that WinDivertRecv() will no longer guarantee packets have correct checksums.  Most applications do not care, so should not be affected.

As for an example of the new syntax, I am hoping for rule-based filters, e.g.

    (ip? ip.DstAddr != 127.0.0.1: true) and
    (ipv6? ipv6.DstAddr != ::1: true) and
    (udp? udp.DstPort == 53: true) and
    (tcp? tcp.DstPort == 80: true)

Attempting to write the same filter in the old syntax is possible but tricky, especially since the old syntax does not support logical negation.  This was an obvious problem Tallow, so hopefully this can now be fixed.

As for #26, it is still not clear what the cause is, so likely will remain unsolved until some new lead comes to light.

As for Windows 10, it should work but I will consider testing it if possible.

**Comment by basil00** [comment]
All planned WinDivert1.2 have been implemented.  I will run some tests and release within the week.

In lieu of dropping WINDIVERT_FLAG_NO_CHECKSUM support, I also added the following:

* The driver ensures that checksum fields are either valid or zero.
* A new WINDIVERT_HELPER_NO_REPLACE flag for WinDivertHelperCalcChecksums().  If enabled, only zero'ed checksum fields will be replaced.

The combination of these means that checksums for packets returned by WinDivertRecv() can be efficiently calculated.  Basically, if a checksum is absent, then the corresponding checksum field will be set to zero by the driver.  Calling WinDivertHelperCalcChecksums() with the NO_REPLACE will then calculate the checksum.  Otherwise, if the checksum is present and non-zero, the WinDivertHelperCalcChecksums() function (with NO_REPLACE) will skip the checksum computation.  There is a corner case where the checksum is valid and zero.  However, this is rare (1 in 2^16), so will not introduce significant overheads.

**Comment by Phyxion** [comment]
That's a very nice feature @basil00, thank you very much for adding it. 

Are ipv6 packets with extension headers now also supported with the new filter or is it just the syntax?

**Comment by basil00** [comment]
WinDivert Version 1.2.0-rc is now available [here](https://github.com/basil00/Divert/releases).

Keep in mind this is a "release candidate".  So although the new version passes all tests, there may be some new bugs introduced since version 1.1.7.

I also plan a WinDivert 1.1.8 bugfix release in the next few days.

**Comment by Phyxion** [comment]
Is the RC signed as well @basil00?

What will 1.1.8 fix? Thanks :+1:

**Comment by basil00** [comment]
The drivers are signed by Nemea as usual.  They should work for Windows 10 but this has not been tested.  Version 1.1.8 will fix two minor bugs: the handling on ip.TOS and IPv6 comparison bug in the filter interpreter

**Comment by Phyxion** [comment]
I'll make a Windows 10 install soon after official release (29th) and do some testing. If there is anything in specific you'd like tested, please let me know.

**Comment by basil00** [comment]
Thanks @Phyxion.  If any of the sample problems (e.g. netdump) work under Windows 10, then the new driver should be compatible.

**Comment by TechnikEmpire** [comment]
I have multiple PC's getting the 10 upgrade. Will test when I get it. Thanks again @basil00 .

**Comment by basil00** [comment]
Version 1.1.8 and 1.2.0-rc are now officially released and on [the website](https://reqrypt.org/windivert.html).  Time to close this issue.  Thanks to all who contributed.

If there are any further problems then please open a separate issue.
