### ISSUE TITLE
DNS redirection

### ISSUE THREAD

**Issue by jtokarchuk** [basil00/Divert#40]
hi there. 

was hoping on getting a hand. I'd like to modify the Web filter project to instead redirect DNS requests in blacklist to 127.0.0.1 (to blacklist ssl sites) 

was unsure how to proceed.  great product though!

**Comment by basil00** [comment]
Perhaps look at [Tallow](https://github.com/basil00/TorWall) which intercepts and replies to DNS requests.

If you want redirection you could capture the DNS packets, and forward the payload to a normal UDP socket bound to 127.0.0.1:53.  You also need to handle the reverse path.
