### ISSUE TITLE
Driver signature issue on Windows 10

### ISSUE THREAD

**Issue by dmdo** [basil00/Divert#44]
Hello,

Thank you for the awesome software!

I've tried to re-sign drivers with own certificate. We are using both SHA-1 and SHA-256 signatures at the same time in the single file.
This type of signature works fine on Windows 8 and Windows 7. But on Windows 10 (10162) we see 577 error on Windivert Open.

What it could be?

Thank you.

**Comment by basil00** [comment]
A quick Google search finds this: http://blogs.msdn.com/b/windows_hardware_certification/archive/2015/04/01/driver-signing-changes-in-windows-10.aspx

This is not good.  It appears Microsoft are once again severely restricting the driver signing process under the guise of security.  This may affect WinDivert and Windows 10 support.

**Comment by dmdo** [comment]
Hello,
It turned out to be issue with our signing processes. We have fixed that and now all works fine in Windows 10.

Thank you again for the great software!

**Comment by Phyxion** [comment]
I know you closed this, but it might be an issue in the future:

> No, existing drivers do not need to be re-signed.  To ensure backwards compatibility, drivers which are properly signed by a valid cross-signing certificate that was issued before the release of Windows 10 will continue to pass signing checks on Windows 10.

If I read it correctly, drivers signed 90 days after the release of Windows 10 needs to go through the Microsoft portal with an EV certificate. @basil00, which certificate is used to sign the current binaries?

**Comment by basil00** [comment]
The driver is normally signed by Nemea software.  I do not think they have EV or if they plan to get it.

I am aiming to have the 1.2 version of the driver signed by Nemea before the Windows 10 release date (29th of July).  This version should work for Windows 10 thanks to backwards compatibility, but it will not be possible to sign the driver after that.

The driver is stable, so hopefully this will buy some time.  However, if there is a critical bug discovered then Windows 10 users will not be able to upgrade, which may be ironic given the new driver signing policy is for "security" reasons.

**Comment by Phyxion** [comment]
Thank you for the information @basil00, I appreciate it. They have a point for security reasons although I think that the EV certificates are very expensive and severly impact open source projects such as this. It would be nice if Microsoft added an exception for open source projects, for which they were to supply a certificate.

**Comment by dmdo** [comment]
We are in processes of getting EV code sign cert for our company. If we get it, I think we will find a way to sign WinDivert. @basil00, send me a PM if you are interested.

**Comment by Phyxion** [comment]
There are no PMs on GitHub anymore @dmdo.

**Comment by basil00** [comment]
@dmdo Yes I would be interested.  Please contact me via email (basil at reqrypt dot org).
