### ISSUE TITLE
Updating filter expression in realtime

### ISSUE THREAD

**Issue by antonsviridenko** [basil00/Divert#46]
Hi

Is WinDivert well-suited for this use case?

For example, there are two open handles, one in sniffing mode for incoming DNS replies and second for HTTP packets. Userspace application analyzes DNS packets and decides to update HTTP filter rule (whitelisting/blacklisting, etc). Can I expect that closing existing HTTP filter handle and opening new one with updated filter expression will be completed before the browser starts connection to the IP received in DNS reply? So application can capture SYN packet from the new TCP connection to HTTP server using new filter?

**Comment by basil00** [comment]
There is currently no way to update filters once a handle has been opened.  Implementing such a feature would be relatively complicated and the benefits would be marginal, so it is probably not worth it.  Much of the overhead (filter compilation) is unavoidable either way.
