### ISSUE TITLE
Filter string length limit

### ISSUE THREAD

**Issue by antonsviridenko** [basil00/Divert#47]
https://github.com/basil00/Divert/blob/master/include/windivert_device.h#L118

#define WINDIVERT_FILTER_MAXLEN                     128

value 128 is too small, I propose to support arbitrary length filter strings or at least make this limit configurable in runtime

**Comment by antonsviridenko** [comment]
Will it work with custom built driver with WINDIVERT_FILTER_MAXLEN value changed to something like 1024 - 4096?

**Comment by basil00** [comment]
This is deliberate.  Filters should be as short as possible since WFP callouts should be as fast a possible. Complicated filtering (such as IP blacklists) should be done in userspace.
