### ISSUE TITLE
Windows 10 Issues

### ISSUE THREAD

**Issue by TechnikEmpire** [basil00/Divert#49]
So, I haven't quite narrowed down if this is indeed a WinDivert on Win 10 issue or not, but my transparent proxy driven by WinDivert is completely non-functional on Windows 10. Functional before upgrade, no changes to app code. All outbound connections just spin and timeout. Will report back when I get to the actual root of the issue.

**Comment by TechnikEmpire** [comment]
Nevermind, some jackass changed the WinDivert flags incorrectly and forgot about it, causing the breakage. That jackass is me. :)

**Comment by basil00** [comment]
Thanks for the report anyway.  So I take it that WinDivert works on Windows 10?

**Comment by TechnikEmpire** [comment]
Yeah everything seems to be working just fine.

**Comment by basil00** [comment]
That's good to know.  Thanks for testing it out.

**Comment by TechnikEmpire** [comment]
Hey no problem, thanks for the lib. :) I upgraded to the 1.2 RC from 1.1.7 on Win 10 x64. Everything running smooth, no issues. Just thought I'd report that as well.
