### ISSUE TITLE
WinDivertOpen fails with error code 317

### ISSUE THREAD

**Issue by antonsviridenko** [basil00/Divert#51]
```
WinDivertOpen("false", 0, 1000, 0);
```
GetLastError() returns 317 on Windows 7 32bit

according to MSDN, it is 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382%28v=vs.85%29.aspx
```
ERROR_MR_MID_NOT_FOUND

    317 (0x13D)

    The system cannot find message text for message number 0x%1 in the message file for %2.
```

I searched WinDivert sources for ERROR_MR_MID_NOT_FOUND but found nothing

Do you have any idea what could be the reason of this error?

**Comment by basil00** [comment]
Thanks for the report.

That's a weird error.  Does it occur with different parameters to WinDivertOpen? Also, do the WinDivert sample programs work?  E.g. netfilter, netdump, passthru.

**Comment by antonsviridenko** [comment]
Looks like error was caused by using different version of WinDivert DLL and driver, other than application was compiled with, sorry for delaying that report :)
