### ISSUE TITLE
ICS and Windivert Forward Layer

### ISSUE THREAD

**Issue by kelvinomolumo** [basil00/Divert#54]
First of all thank you for this very useful lilbrary.
I am using WinDivert along with ICS (Internet Connection Sharing) to capture forwarded packets. i was having problem getting it work but after going through the issues posted here i got it to work somehow.
I opened a first handle to capture forward packets like this:
HANDLE forward_handle = WinDivertOpen("tcp.DstPort==80", WINDIVERT_LAYER_NETWORK_FORWARD, -1000, 0);

Then i open a second handle to inject the modified packet captured from the forward_handle like this: 
HANDLE handle = WinDivertOpen("false", WINDIVERT_LAYER_NETWORK, 0, 0);

This works but at times the program crashes or sometimes the forwarded packets are not modified but am not really bothered by this i believe it might be a bug in my code. My real problem is, i am trying to add up the packetLen to get bandwith usage but the bandwith is always incorrect. After using the passthrue program provided with WinDivert i figured that the response packets are on the outbound path of the ICS machine. So i created a new thread where i open another handle to capture this packet and add up packetLen, this works for like a minute then calculation get wrong. Do you have any idea why this happens? i tried changing the priorities so many times but i still can't get it working properly. Would be glad if you can give me some insight on what to do. Thanks

**Comment by ianbannerman** [comment]
Can you a minimal version of the code you're using? I'm successfully using ICS & WinDivert on a few projects of mine at the moment, so I'm sure we can figure this out!

I'm still seeing & capturing with what I shared in issue 37:
    Outbound traffic to external servers on WINDIVERT_NETWORK_LAYER_FORWARD
    Outbound traffic to Windows NAT itself (192.168.25.1) on WINDIVERT_NETWORK_LAYER
    Inbound traffic from external servers on WINDIVERT_NETWORK_LAYER

**Comment by kelvinomolumo** [comment]
Ok so i want to blacklist some websites on the network. windivert sits in the ICS machine. then monitors the traffic on port 80 (have not implemented on port 443 yet). Because of ICS the packets are only visible on the forward layer. so i open a handle on the forward path then another handle to perform injection like this: 

    Sample Code:
    Thread 1:

    forward_handle = WinDivertOpen(filter, WINDIVERT_NETWORK_LAYER_FORWARD, -1000, 0); // forward handle
    handle = WinDivertOpen(filter, WINDIVERT_LAYER_NETWORK, 0, 0); // injection handle

    while(True){
    //capture forward packet
            if(!WinDivertRecv(forward_handle, packet, sizeof(packet), &addr, &packetLen)){
                continue;
            }
            //Parse packet
            WinDivertHelperParsePacket(packet, packetLen, &ip_hdr, NULL, NULL,
                                           NULL, &tcp_hdr, NULL, NULL, &payloadLen);

           //modify packet if url blacklisted else do nothing (forward packet can't be block i think)
          // also store the payloadLen if url not blacklisted
          //if packet modified inject new packet with the injection handle for each step of the modification
         WinDivertSend(handle, (PVOID) resetPacket, sizeof(TCPPACKET), &addr, NULL);
    }

    Thread 2:

    bandwith_handle = WinDivertOpen(filter, WINDIVERT_LAYER_NETWORK, 1000, WINDIVERT_FLAG_SNIFF);

    //Parse packet then store payloadLen if url in payload not blacklisted

**Comment by basil00** [comment]
The `payloadLen` is the length of the payload, not the total length which is `packetLen`.  For bandwidth counting it is common practice to use the latter.  This is the only thing I could think of.

Also note that if you only want the `packetLen` then you can use:

    WinDivertRecv(bandwidth_handle, NULL, 0, NULL, &packetLen)

This saves copying the packet from kernel -> user space.

**Comment by kelvinomolumo** [comment]
@basil00 thanks so much. now its working very well. another little question the way am tackling the forward packet redirection, is it the correct way to deal with it? Because like i said after some time packets are no more modified. I thought it was the handle but after setting the params to 8192 and the time 2048 am still experiencing the same issue. Thanks!!!

**Comment by basil00** [comment]
I am not sure why some packets are not modified.  The first thing to find out is whether the packets are being captured or not.

**Comment by kelvinomolumo** [comment]
@basil00 thanks for your help. i solved all the issues. it turned out the last issue was not from windivert but rather how my app was handling the captured packets. Thanks!!!
