### ISSUE TITLE
C# Wrapper

### ISSUE THREAD

**Issue by fahminlb33** [basil00/Divert#55]
I'm wrapping this library in C#. I have trouble with WinDivertRecv method.

I always get 0 handle in ```packData``` .

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

namespace ConsoleApplication2
{
    class Program
    {
        const int MAXBUF = 0xFFFF;

        static void Main(string[] args)
        {
            //Open handle
            IntPtr capHandle = NativeMethods.WinDivertOpen("true", WINDIVERT_LAYER.WINDIVERT_LAYER_NETWORK, 0, NativeConstants.WINDIVERT_FLAG_SNIFF);
            if (capHandle.ToInt64() < 0)
            {
                Console.WriteLine("Handle error.");
                Console.Read();
                Environment.Exit(0);
            }

            //Set queue length
            if (!NativeMethods.WinDivertSetParam(capHandle, WINDIVERT_PARAM.WINDIVERT_PARAM_QUEUE_LEN, 8192))
            {
                Console.WriteLine("Can't set queue length.");
                Console.Read();
                Environment.Exit(0);
            }

            //Set queue time
            if (!NativeMethods.WinDivertSetParam(capHandle, WINDIVERT_PARAM.WINDIVERT_PARAM_QUEUE_TIME, 2048))
            {
                Console.WriteLine("Can't set queue time.");
                Console.Read();
                Environment.Exit(0);
            }

            //Capture packets
            while (true)
            {
                //Receive packet
                IntPtr recvPacket = IntPtr.Zero;
                IntPtr recvAddr = IntPtr.Zero;
                IntPtr recvLength = IntPtr.Zero;
                if (!NativeMethods.WinDivertRecv(capHandle, ref recvPacket, (uint)IntPtr.Size, ref recvAddr, ref recvLength))
                {
                    //Console.WriteLine("Failed to read packet.");
                    continue;
                }

                Console.WriteLine("==============================================");

                //Copy data into managed data
                byte[] packData = new byte[MAXBUF];
                int packLength = recvLength.ToInt32(); //Marshal.ReadInt32(recvLength);
                Marshal.Copy(recvPacket, packData, 0, packLength);

                //Write to console
                for (int i = 0; i < packLength; i++)
                {
                    if (i % 20 == 0)
                    {
                        Console.Write("\n\t");
                    }
                    Console.Write("{0:2X}", packData[i]);
                }

                for (int i = 0; i < packLength; i++)
                {
                    if (i % 40 == 0)
                    {
                        Console.Write("\n\t");
                    }
                    Console.Write(packData[i]);
                }
            }
        }
    }
}
```
And this is my P/Invoke signature
```
/// Return Type: HANDLE->void*
        ///filter: char*
        ///layer: WINDIVERT_LAYER->Anonymous_ec549c13_388a_4ceb_9226_dbcceaafef56
        ///priority: INT16->short
        ///flags: UINT64->unsigned __int64
        [DllImportAttribute(NativeConstants.WinDivertLib, EntryPoint = "WinDivertOpen", CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
        public static extern System.IntPtr WinDivertOpen([InAttribute()] [MarshalAsAttribute(UnmanagedType.LPStr)] string filter, WINDIVERT_LAYER layer, short priority, ulong flags);
                
        /// Return Type: BOOL->int
        ///handle: HANDLE->void*
        ///pPacket: PVOID->void*
        ///packetLen: UINT->unsigned int
        ///pAddr: PWINDIVERT_ADDRESS->Anonymous_656602c6_58d0_42b1_aac9_fb4189b2366f*
        ///readLen: UINT*
        [DllImportAttribute(NativeConstants.WinDivertLib, EntryPoint = "WinDivertRecv", CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
        [return: MarshalAsAttribute(UnmanagedType.Bool)]
        public static extern bool WinDivertRecv([InAttribute()] System.IntPtr handle, ref System.IntPtr pPacket, [InAttribute()] uint packetLen, ref System.IntPtr pAddr, ref System.IntPtr readLen);


        /// Return Type: BOOL->int
        ///handle: HANDLE->void*
        ///pPacket: PVOID->void*
        ///packetLen: UINT->unsigned int
        ///pAddr: PWINDIVERT_ADDRESS->Anonymous_656602c6_58d0_42b1_aac9_fb4189b2366f*
        ///writeLen: UINT*
        [DllImportAttribute(NativeConstants.WinDivertLib, EntryPoint = "WinDivertSend", CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
        [return: MarshalAsAttribute(UnmanagedType.Bool)]
        public static extern bool WinDivertSend([InAttribute()] System.IntPtr handle, [InAttribute()] System.IntPtr pPacket, uint packetLen, [InAttribute()] ref WINDIVERT_ADDRESS pAddr, System.IntPtr writeLen);


        /// Return Type: BOOL->int
        ///handle: HANDLE->void*
        [DllImportAttribute(NativeConstants.WinDivertLib, EntryPoint = "WinDivertClose", CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
        [return: MarshalAsAttribute(UnmanagedType.Bool)]
        public static extern bool WinDivertClose([InAttribute()] System.IntPtr handle);


        /// Return Type: BOOL->int
        ///handle: HANDLE->void*
        ///param: WINDIVERT_PARAM->Anonymous_a7169b5f_684b_48de_a3cd_3e9f153061a1
        ///value: UINT64->unsigned __int64
        [DllImportAttribute(NativeConstants.WinDivertLib, EntryPoint = "WinDivertSetParam", CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
        [return: MarshalAsAttribute(UnmanagedType.Bool)]
        public static extern bool WinDivertSetParam([InAttribute()] System.IntPtr handle, WINDIVERT_PARAM param, ulong value);


        /// Return Type: BOOL->int
        ///handle: HANDLE->void*
        ///param: WINDIVERT_PARAM->Anonymous_a7169b5f_684b_48de_a3cd_3e9f153061a1
        ///pValue: UINT64*
        [DllImportAttribute(NativeConstants.WinDivertLib, EntryPoint = "WinDivertGetParam", CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
        [return: MarshalAsAttribute(UnmanagedType.Bool)]
        public static extern bool WinDivertGetParam([InAttribute()] System.IntPtr handle, WINDIVERT_PARAM param, [OutAttribute()] out ulong pValue);
```

**Comment by fahminlb33** [comment]
Also, the last error code is 997 (ERROR_IO_PENDING) but I'm not using WinDivertRecvEx.

**Comment by basil00** [comment]
I don't have anything more to add over what @TechnikEmpire said.

However, it is strange to get a 997 error for passing 3 null pointers.  Instead the call should just block until a packet is captured.

**Comment by fahminlb33** [comment]
So, I can't pass Null Pointer to WinDivertRecv method. But when I'm trying to pass allocated memory (using `Marshal.AllocHGlobal), I'm getting 998 (ERROR_NOACCESS). I'll post my new code ASAP.

**Comment by TechnikEmpire** [comment]
A quick search of google yields http://stackoverflow.com/questions/19259171/windivert-1-0-5-divertrecv-method-get-last-error-998. Someone already has tried what you're doing and had the same issue. That thread might be of value to you. I'd suggest if you have broken code, posting it on stackoverflow. I'm not speaking for everyone, just my opinion, but you're kind of outside of the scope of the project here and your issues are with your own implementation, not WinDivert. Just a suggestion, not trying to dismiss you.

**Comment by TechnikEmpire** [comment]
@fahminlb33 I've found my old C++/CLI wrapper for WinDivert. I'm just cleaning it up and splitting it into separate files (I had one huge header only implementation before). I should be done in a few hours tops, I'm pushing it here:

https://github.com/TechnikEmpire/Divert.Net

When I'm finished I'll build and publish a release and throw in an example of intercepting DNS packets and filtering DNS lookups, and another example of filtering which applications can access the internet.

**Comment by fahminlb33** [comment]
I'll waiting for your first release on Divert.Net
Also, I'll keep trying to figure out how to corectly marshall those Pointers in C#. :+1:

**Comment by fahminlb33** [comment]
My project's goal is to create "netdump" in C#

**Comment by TechnikEmpire** [comment]
@fahminlb33 Alright, I'll see if I can easily replicate those tests. I'm almost done, just have to do UDP header then find a clean way to put the WinDivert free functions into a class (functions like Parse/Send/Recv etc).

**Comment by fahminlb33** [comment]
I'm also creating class wrapper. But when I'm test my class wrapper in Console app, it won't work. So, I decided to copy all PInvoke into new project and test them. But, no luck at WinDivertRecv call.

**Comment by basil00** [comment]
Great work @TechnikEmpire.  I've been asked several times for a C# binding but nobody has ever released one.

**Comment by fahminlb33** [comment]
Maybe I'll release it if I had successfully on this project.

**Comment by TechnikEmpire** [comment]
@basil00 Thanks, you did all the hard work. :) Being a CLR library, this will provide bindings for all .NET languages like F#, VB.NET etc out of the box. I'll get a release and some tests published today. We talked briefly before about WinDivert being able to identify the process behind packet flows, I intend on integrating functionality that into the CLR library today too. 

@fahminlb33 publishing a pure pinvoke version for C# has benefits of its own, like not being bound to a specific WinDivert release during a linking phase. So yeah for sure if you can get it all sorted, sharing it would probably help someone. 

@basil00 What are your thoughts on me distributing WinDivert release binaries in my releases? I'm not 100% sure, will have to test, but I think the CLR binaries might be tightly bound to the specific WinDivert release it's compiled against. I'm conflicted about having to release copies of your releases because I don't want drive users away your site and repository.

**Comment by TechnikEmpire** [comment]
Errrr never mind I should finish my coffee before I start talking. Shouldn't be any binding, I was vaguely recalling mixing up dll and drivers for windivert :S

**Comment by fahminlb33** [comment]
I'm confused how to use WinDivert API because the documentation doesn't cover what expected argument to pass into the parameter. I'm hoping the documentation will cover anything like in MSDN.

**Comment by TechnikEmpire** [comment]
@fahminlb33 The documentation has extensive remarks about what is required for the arguments, as well as the inner workings of the methods: https://reqrypt.org/windivert-doc.html#divert_recv

**Comment by basil00** [comment]
@TechnikEmpire, there is no problem distributing the Windivert binaries along with your release.

**Comment by TechnikEmpire** [comment]
@basil00 Okay cool. Are you okay with me copying some snippets of documentation into comment sections of my code? I figured it'd be okay but I wanted to double check. I'm putting links back to the source in with such comments.

**Comment by fahminlb33** [comment]
@TechnikEmpire maybe I'm just misunderstand the documentation.
@basil00 as @TechnikEmpire said that he will copying documentation into comment sections of code, can I also copying the documentation into my wrapper (using XML Comments) and then create doc file using Sandcastle?

**Comment by basil00** [comment]
I don't mind you including snippets of the documentation.

**Comment by TechnikEmpire** [comment]
@basil00  okay great. I have to write tests and such but I've got the general functionality of netdump working, printing out captured packet information in sniffing mode. Anyway I basically just wrote this from scratch instead of using my old code, so there's bound to be bugs. I'll keep working away at it and let you know when a release is ready.

**Comment by fahminlb33** [comment]
I have successfully received raw packet using `WinDivertRecv` but I can't parse the raw data. This is my code.

```

**Comment by TechnikEmpire** [comment]
Reading the documentation will help you, a lot. `WinDivertHelperParsePacket` can return false in a valid situation. Don't even bother checking the return value of `WinDivertHelperParsePacket`, simply check the validity of the pointers you supplied to it.

https://reqrypt.org/windivert-doc.html#divert_helper_parse_packet

Quote: `Note that FALSE may sometimes be a legitimate return value, e.g., when both ppIpHdr and ppIpv6Hdr are non-NULL. `

**Comment by brunoklein99** [comment]
I keep getting `Cannot open include file: 'windivert.h': No such file or directory` when trying to compile the dll. Could you please add a `bin` folder with the proper binaries? Can't get simpler than that.

**Comment by fahminlb33** [comment]
Now I have a working method in C# wrapper for `WinDivertOpen`, `WinDivertRecv`, `WinDivertClose` and `WinDivertHelperParsePacket`. And I have completed my C# `netdump` implementation.


I'll soon commit it into my repo on GitHub : https://github.com/fahminlb33/SharpDivert

**Comment by TechnikEmpire** [comment]
@fahminlb33 nice. :+1:

**Comment by fahminlb33** [comment]
I have a question about `WinDivertHelperParsePacket`. Do I need to release the pointers returned from `WinDivertHelperParsePacket` in .NET code? Like calling `Marshal.FreeHGlobal` or I can just ignore the returned pointers?

**Comment by TechnikEmpire** [comment]
The only pointers you need to worry about deleting are the ones you create when you call `new` or `malloc`, or using the Marshal versions of either of those things. As far as the pointers you supply to WinDivertHelperParserPacket, the only pointer you created is for the buffer. Notice the other pointers are not just pointers, but rather pointers to pointers. WinDivert takes your pointers to pointers and points them at the right memory. You don't need to worry about freeing any of those.

**Comment by fahminlb33** [comment]
OK. thanks :+1:

**Comment by TechnikEmpire** [comment]
@fahminlb33 Might be a good idea to close this issue now.

**Comment by TechnikEmpire** [comment]
@basil00  @fahminlb33  You can find a PInvoke version here:

https://github.com/TechnikEmpire/DivertPInvoke

**Comment by fahminlb33** [comment]
I'll try it soon
