### ISSUE TITLE
WinDivert Forward Layer

### ISSUE THREAD

**Issue by kelvinomolumo** [basil00/Divert#56]
Hello everyone,
I have a problem and i really don't know how to go about it.  I want to block all packets from the forward layer. In windows 7 i did this by intercepting the response packet on the outbound path of the network layer. But in windows 8 and above this doesnt seem to work. I tried to open two handles like this: 

WinDivertOpen(filter, forward_layer, 998, WINDIVERT_FLAG_SNIFF);

WinDivertOpen(filter,  network_layer, 999, 0);

i still can't differentiate the packets from the forward path from the ones from the local machine's outbound path because the ip of the packet are all converted to that of the local machine. So my question is how can i get the forward packets on the outbound path without loosing its original ip

**Comment by TechnikEmpire** [comment]
@kelvinomolumo Can you add more information, such as a small compilable example? I'm not clear on what you're asking. @basil00 will eventually pick this thread up and will probably know better than I. As it stands right now, all I can point out is that if you want to drop everything from the forward layer, why aren't you just opening the handle with WINDIVERT_FLAG_DROP? WINDIVERT_FLAG_SNIFF copies the packets but does not suspend or divert transmission of the captured packet AFAIK.

**Comment by ianbannerman** [comment]
This comment may help out - https://github.com/basil00/Divert/issues/37#issuecomment-84166301

Windows 8 changed which layer inbound traffic with the proper IP is seen on.

**Comment by kelvinomolumo** [comment]
Sorry guys....now looking back at this my question I feel so st**id. Sorry for wasting your time. Thanks @TechnikEmpire  & @ianbannerman . Maybe its stress lol

**Comment by TechnikEmpire** [comment]
@kelvinomolumo Never feel stupid, there's always things that we don't know which someone else does, that's how this works. :) No time wasted, no apology needed.
