### ISSUE TITLE
Unable to capture traffic coming from other machines?

### ISSUE THREAD

**Issue by brunoklein99** [basil00/Divert#57]
I am trying to observe traffic from another machine in my network. I used the `netsh` command to change the arp table on my notebook and could successfully observe the traffic in Wireshark coming to my machine, but not in WinDivert.Net. This is my code: http://pastebin.com/9h7wLwsP. Is this behavior a WFP limitation?

**Comment by basil00** [comment]
WinDivert cannot see traffic captured by a NIC in promiscuous mode.  Wireshark does not have this limitation.  I am not sure about WFP in general.

For WinDivert it does not make sense to handle such traffic since there is no way to block or modify it.
