### ISSUE TITLE
Filter based on application?

### ISSUE THREAD

**Issue by quantum1423** [basil00/Divert#58]
Is the technically possible to divert traffic based on which application sent it? I looked through Tallow and it seems like it just assumes that ports 9001 etc are Tor, which isn't really true (a large number of Tor nodes actually run on port 443 to make it slightly harder to block Tor naively). Would it be possible to write an application that only diverts traffic if, say, it's not from `tor.exe`?

**Comment by TechnikEmpire** [comment]
@quantum1423 There is no support for this directly within WFP, upon which WinDivert is built. All you can do is use the Win32 api to attempt to determine the process generating a packet flow.

If you can suffer seeing a mix of visual C++ and the native C api, there's an example of how to get this information in my .net wrapper for WinDivert [here](https://github.com/TechnikEmpire/Divert.Net/blob/master/src/Diversion.cpp). Look at the `Diversion::GetPacketProcess` methods.

**Comment by TechnikEmpire** [comment]
Note also you can, with a little bit of modification, make [nDPI](http://www.ntop.org/products/deep-packet-inspection/ndpi/) work with WinDivert, which will provide port independent protocol mapping and would give you the same end result you're after. Tor is one of the many supported protocols.

**Comment by basil00** [comment]
No this is not technically possible.  The best you can do the the `GetPacketProcess` trick suggested by @TechnikEmpire.

The problem is that there is no process information associated with packets at the network layer.
