### ISSUE TITLE
promiscuous mode workaround

### ISSUE THREAD

**Issue by Yousefjb** [basil00/Divert#61]
hello,  
i read in another issue here that WinDivert doesn't work in promiscuous mode, i just want to get things clear. I am doing ARP spoofing to redirect traffic in the network to my device where WinDivert works fine, i am loosing a few packets due to arp spoofing race condition, i though i could get these missed packets by using winpcap in promiscuous mode, i wonder if windivert will keep on working since the same interface now is used in promiscuous mode.  
Thanks

**Comment by basil00** [comment]
It may be possible that WinDivert can capture the packet, however, it cannot block the packet as it is already a copy.  At least that is my understanding of promiscuous mode.
