### ISSUE TITLE
building project in vs2010 

### ISSUE THREAD

**Issue by abu21** [basil00/Divert#63]
how to run this project in vs2010 or 2013?
i am having issue in running wddk-build.bat file ..it is not creating dll and windivert64.sys file in INSTALL directory .
Also, i am having Win 10 . do i have to download Win driver kit for win 10?
Please help me.

**Comment by basil00** [comment]
To build WinDivert without building the driver, you just need to copy the pre-built driver files to the following directories:

    install\WDDK\amd64\WinDivert64.sys
    install\WDDK\i386\WinDivert32.sys

After that, you can run `msvc-build.bat` in a VS command-line build environment.

You can try this for VS2010 or VS2013.  I am not sure if it will work.  I think some of the `sln` files may be VS2012 specific and need downgrading/upgrading.
