### ISSUE TITLE
WinDivert WinDivertSend() problem

### ISSUE THREAD

**Issue by nowsec** [basil00/Divert#68]
Dear, basil. 
My name is Irog. I am a student studying about WinDivert :)
While compiling netfilter.c file that I modified, I met something unknown error. Here is a test.

[Test Case 1]

I tried to send a TCP packet receiving from WinDivertRecv function,  using WinDivertSend function.
I didn't modify any packet data. After receiving a TCP packet, and I inputed the packet into WinDivertSend parameter.
However, When I executed WinDivertSend function, it made 592 error("The TDI client could not handle the data received during an indication). 

[Here is my code]

Project File (https://drive.google.com/file/d/0B6Y5EfG1m_krWVhOS2JWZ0REZ0E/view?usp=sharing)
Source File (https://drive.google.com/file/d/0B6Y5EfG1m_krSkRwc0hlQjJqYmc/view?usp=sharing)

**Comment by basil00** [comment]
Sounds similar to [this problem](https://github.com/basil00/Divert/issues/12#issuecomment-235795212) reported a few days ago.  Which version of Windows are you using?

**Comment by nowsec** [comment]
I am using Windows 10 Pro 64 bits. Is this probrom due to window 10? 
------ Original Message ------
Date: Monday, Aug 1, 2016 11:33:14 AM

**Comment by basil00** [comment]
Which version of WinDivert are you using (1.1.8 or 1.2.X) ?

Looking at your code, you do not calculate the checksum before re-injecting, which is a problem for WinDivert 1.2.X.

The other issue may be unrelated.

**Comment by basil00** [comment]
No response so I will assume the issue was resolved.
