### ISSUE TITLE
Is WinDivert usable for Windows 8 and 10 ? 

### ISSUE THREAD

**Issue by u-riaz** [basil00/Divert#69]
Hi, 
WinDivert is based on WDK-7.1.0 and claims that it would support Windows Vista and up (7,8,10). But the Microsoft's [page](https://www.microsoft.com/en-pk/download/details.aspx?id=11800) claims that WDK 7.1.0 can only be used to build drivers for Windows 7 and lower. Can someone please help to let me understand how WinDivert will support Windows 8 and 10.
I want a traffic filter on all Windows versions who support WFP i.e. Vista upwards.

**Comment by basil00** [comment]
Windows 7 drivers are compatible for Windows 8 and 10, so there is no problem.

Latter versions of WDK build drivers that are only compatible with Windows 10, or require co-installer bloat to work on older versions of Windows.  That and the fact that WDK 10 requires VS2015 professional (non-free) makes WDK7 an easy choice.
