### ISSUE TITLE
Missing INF file for Digitally signing

### ISSUE THREAD

**Issue by u-riaz** [basil00/Divert#70]
I'm new to driver dev hence don't know much about driver signing. 
I'm trying to sign WinDivert64.sys using the help available within WDK. After creating *.cer file, creation of *.cat file is required. To create a cat file with "INF2CAT.exe" an INF file is required, but there is no such file in the WinDivert home directory. I'd build the WinDivert package using wddk-build.bat which doesn't generate any INF file. How i can generate INF file? 
Please help me to get out of it, i'd spent my whole day to figure it out but no success.

Are you people have a signed driver which i can use ?

**Comment by TechnikEmpire** [comment]
See #53

Currently the project is in need of a sponsor for the cert. To cover all windows platforms (ie Win 10) the cert needs to be an EV cert. Expensive.

**Comment by basil00** [comment]
@u-riaz Unless you are modifying WinDivert there is no need to sign the driver yourself, just copy-and-paste a pre-signed driver from a binary release: https://github.com/basil00/Divert

WinDivert does not use an inf file.  You can just use `signtool` directly on the driver, something like:

    signtool sign /a /v /ac path /s store /n name /t server WinDivert.sys

I forget all the details though.

Also, a @TechnikEmpire points out, signing the driver for Windows 10 just got more complicated and expensive.  Currently I have no way of signing new releases.  There is no immediate problem unless someone finds a bug in which case I cannot fix it.
