### ISSUE TITLE
Unable to capture forwarded packets without Windows ICS

### ISSUE THREAD

**Issue by anovokreschenov** [basil00/Divert#72]
Hi @basil00, I have tried to create a very simple firewall with NAT to share single Internet connection in small local network, but I have a troubles. This is a testing environment: PC with two physical network cards, the first NIC has static IP address and is connected to the ISP, the second NIC has static IP address and used as a default gateway for all other machines in the network;

My program opens two WinDivert handles, first handle to divert all forwarded packets (filter is "true"), the second to divert all incomming connections from Internet ("inbound"). At the first step I want to write to file log all the information about forwarded packets, but I can't receive them. When I configure my network to use Windows Internet Connection Sharing, then I see all forwarded packets. Is it possible to create a custom NAT solution without using of Windows ICS? Or how to capture packets sent from LAN to Internet through the gateway (PC with WinDivert)?

Sorry for my English.

**Comment by basil00** [comment]
Are you opening the WinDivert handle at the `WINDIVERT_LAYER_NETWORK_FORWARD` layer?

**Comment by anovokreschenov** [comment]
Yes of course, I've created a very simple test program, it opens a WinDivert handle - `WinDivertOpen('true', WINDIVERT_LAYER_NETWORK_FORWARD, 0, 0)`, the program reads and writes packets in separate thread without any modifications, just for logging purposes.

The test environment:
- PC with two physical network interfaces (LAN and WAN), this PC works under Windows 10 x64. The test program works on this PC, and tries to write the info about each packet forwarded from LAN segment to the log file.
- PC and mobile devices configured to use the LAN interface of the first PC as a default gateway.

Test 1 (clean system with default set of system services enabled, integrated firewall is disabled) - Fail, WinDivert doesn't show any forwarded packets.

Test 2 (same system with Internet Connection Sharing enabled) - Success, I see packets in the log, but with a small problem - I see a double set of packets, the second copy of each packet has been already processed by Windows NAT.

Test 3 (same system with Routing and Remote Access service enabled) - Success, I see all the packets.

Result: I should first enable the Routing and Remote Access service (it is disabled by default). Is it right? Or did you know another way to do it?

**Comment by basil00** [comment]
> Result: I should first enable the Routing and Remote Access service (it is disabled by default). Is it right? Or did you know another way to do it?

I think this is correct.  If you want forward packets, you basically need to configure Windows as a router, otherwise the packets are discarded/ignored by Windows by default.

I am not sure about the double packets problem for ICS.
