### ISSUE TITLE
ERROR_IO_PENDING if trying to reinject from netfilter example

### ISSUE THREAD

**Issue by satnatantas** [basil00/Divert#74]
V1.2.0rc, VS2015

I am trying to make a network filter, I am using `netfilter` as a template. I am having strange problems and reduced them to this code:
[netfilter.zip](https://github.com/basil00/Divert/files/639171/netfilter.zip)

I have taken the `netfilter.c` and commented out the info printing and the responses sending (like TCP reset), I pasted the reinjecting line from `passthru` (just to be sure that it 100% not me mistyping something). Every packet reinjection fails with 997, networking programs stop working.

At the same time the `passthru` example works as intended, networking programs are running fine.

Please point me at the error even if it is obvious.

testcase:
`netfilter true 0`
`passthru true 0`

**Comment by basil00** [comment]
`GetLastError` is only meaningful if the injection failed.  Are you sure that `WinDivertSend` returned `FALSE`?

It is plausible that `GetLastError` would return 997 on a successful injection.

**Comment by satnatantas** [comment]
I was sure until I checked the `minwindef.h`:
`#define FALSE               0`

I was so sure that `!0` means error (like in *nix)that I did not check the headers.

I need to excuse now: I do not know what exactly changed but now it is running perfectly fine.
