### ISSUE TITLE
Drop received packet and send another packet

### ISSUE THREAD

**Issue by spyware293** [basil00/Divert#76]
I want to make something like auto reply chat. When i received a specific message it will drop the received message and send a new crafted packet to the sender. How do i drop the packet properly and send a packet to the sender's address ?

**Comment by basil00** [comment]
You should start with the WinDivert documentation and sample programs.

**Comment by spyware293** [comment]
Why i can't drop packet by just not injecting it to windivertsend like this
`while (TRUE)
	{
		checker = false;
		if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
		{
			continue;
		}
		for (int a = 0; a <= packetLen; a++)
		{
			if (packet[a] == 0x31 && packet[a + 1] == 0x33 && packet[a + 2] == 0x35)
			{
				checker = true;
			}
		}
		if (checker && addr.Direction == WINDIVERT_DIRECTION_OUTBOUND)
		{
			continue;
		}
		//WinDivertHelperCalcChecksums(packet, packetLen, NULL);
		if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
		{
			continue;
		}`

I tried to resend 3 times captured send packets too
`for (int b = 0; b <= 3; b++)
			{
				WinDivertSend(handle, packet, packetLen, &addr, NULL);
			}
			continue;`
But it shows like this in wireshark
http://i.imgur.com/KNNCe9n.png
