### ISSUE TITLE
Bug with DDK sample DDproxy

### ISSUE THREAD

**Issue by zhangshuangjun** [basil00/Divert#77]
Hi, I think  Divert maybe have a bug in windivert_write function. Help me....

I build ddk sample DDproxy(just a little modify,see attach) to blocked all udp packet and reinject.

Anything is ok. But after i run passthru.exe with the filter as "outbound and udp"（windivert version 1.2).

The udp packet can't send out, i use wireshark capture the packet. I found Ip header is wrong(see attack)...Orz.....

Is windivert' bug or DDproxy's bug? Thank you....
[ddproxy.zip](https://github.com/basil00/Divert/files/785752/ddproxy.zip)

**Comment by basil00** [comment]
I don't think it can be WinDivert.  The driver checks that the IP version is valid before injection.

Note that mixing WFP filters that use the drop-and-clone idiom is known to be problematic: https://github.com/basil00/Divert/issues/41

**Comment by basil00** [comment]
I assume the problem has been resolved.
