### ISSUE TITLE
UDP packet sent anyway even if it's dropped (Edit outgoing UDP packet)

### ISSUE THREAD

**Issue by maximus780** [basil00/Divert#78]
```
Snippet:
// Modify/parse packet.
WINDIVERT_IPHDR *iphdr;
WINDIVERT_TCPHDR *tcphdr;
WINDIVERT_UDPHDR *udphdr;
char *data;
UINT payload_len;
WinDivertHelperParsePacket(packet, packetLen, &iphdr, 0, 0, 0, &tcphdr, &udphdr, (PVOID*)&data, &payload_len);

// make new packet
int nPacketSize = calc_psize(pCmd);
char* pSendBuf = new char[nPacketSize];
int nSize = craftnewdata(pSendBuf, nPacketSize, pcmd);
if (nSize > 0)
{
    memcpy(data, pSendBuf, nSize);
}
WinDivertHelperCalcChecksums(packet, packetLen, 0);

if (!WinDivertSend(hHandle, packet, packetLen, &addr, NULL))
{
	// Handle send error
	fprintf(stderr, "Error: Failed to send the packet! %d\n", GetLastError());
	continue;
}
```

Did I miss something? Nothing changes when I try to replace data. This is snippet to show the actual problem. memcpy doesn't seem to work and still sends the same packet. This is udp packet.

EDIT: same happens when i try to drop packet(avoid calling WinDivertSend) it's sent anyway. It happens so only for UDP packetsm when I drop TCP packets it works.

**Comment by basil00** [comment]
Are you sure it is not a bug in `craftnewdata`, e.g. returns 0?

**Comment by basil00** [comment]
I assume the problem was resolved.

**Comment by maximus780** [comment]
@basil00 even if I drop it the packet is still being sent. The packet is sent using sendto. I can successfully log it and display values etc. but I can't drop or modify it.

**Comment by basil00** [comment]
I am not sure what it going on.  However, since the same problem exists for winpkfilter and sendto hooks, it is unlikely to be a WinDivert issue.  All I can suggest is trying on a different machine/network to see if the same problem exists.
