### ISSUE TITLE
Filter policy in WinDivertOpen for proxy environments

### ISSUE THREAD

**Issue by rajeshvr83** [basil00/Divert#79]
Hi,

We are using a third party DLL to find the category of each URLs (packets from Windivert driver). For finding the category, third party DLL will send request to their server hosted on internet. We have added IP address of third party server on WinDivertOpen to exclude them from filtering. And this filter policy works fine for normal environments, but it is not working on proxy environments.

In case o f proxy environment, instead of third party server we are getting proxy IP as the destination IP. So we are not able to exclude traffic into third party server through Windivert filter policy. Since destination IP for all the packets are coming as proxy IP, we will not be able to exclude the proxy IP through Windivert filter policy.

For example- we are using WinGate proxy (version -WinGate8.5.9.4883-USE) on our environment, proxy IP- 192.168.1.50 and proxy port- 8080. And we are running the Windivert driver on another Windows 10 machine (64 bit) with proxy settings (kindly see the attachment for settings).

Kindly help us to solve this problem.

Thanks,
Rajesh
![internetoptions](https://cloud.githubusercontent.com/assets/25902753/23126812/817ec052-f79e-11e6-974f-08999d3d7f4c.jpg)
![ipv4 settings](https://cloud.githubusercontent.com/assets/25902753/23126813/8188e15e-f79e-11e6-9626-308b871f3341.jpg)

**Comment by TechnikEmpire** [comment]
@rajeshvr83 try doing some reading about how the Windows Filtering Platform factors into system proxy settings. Perhaps opening a handle with the highest priority will get you the packets before they're processed by those settings but that's just a guess.

 I have been able to write code detect socks 4 and socks 5 proxy CONNECT packets and extract the real destination ip or host name by looking at the packet specification in relevant RFCs but that probably doesn't apply here.

**Comment by TechnikEmpire** [comment]
Actually @rajeshvr83 you should still be able to see the true destination address or domain by inspecting the outgoing request headers. You're not going to build an effective filter at all without doing packet dissection and inspection.

**Comment by basil00** [comment]
I think @TechnikEmpire has the right idea.  If you want to filter traffic that goes via a proxy, it is up to your application to recognize such traffic using the relevant protocols (socks, http, etc.).  These are all application layer protocols anyway, and WinDivert only provides network/transport layer filtering.
