### ISSUE TITLE
WinDivertSend failed with Avast AV

### ISSUE THREAD

**Issue by rajeshvr83** [basil00/Divert#80]
Hi,

We are facing issue with Avast AV, issue is- when Avast WebShield is enabled then WinDivertSend() failed with error code 592 for HTTP websites. When we disable the webShield in Avast then this issue is not happening. So kindly suggest me any solutions to overcome this issue.

Thanks,
Rajesh

**Comment by TechnikEmpire** [comment]
@rajeshvr83 Uninstall Avast. Some AV's are poorly programmed and don't play nicely with the rest of the perfectly legitimate applications and drivers that may need to access network traffic. Bitdefender is another application (2015/2016 versions anyway) garbage antivirus that does this.

**Comment by TechnikEmpire** [comment]
Kaspersky Internet Security plays nice with WinDivert, but its own packet filtering is garbage and will significantly increase network latency.

**Comment by basil00** [comment]
This is a known problem with some AVs.  There is nothing that can be done about it other than uninstall the AV.
