### ISSUE TITLE
SendARP & FORWARD LAYER ISSUE

### ISSUE THREAD

**Issue by kelvinomolumo** [basil00/Divert#81]
Hi!

I'm trying to get the MAC address using the IP header either srcAddr or dstAddr (whichever is on the same subnet) from the packet diverted on the forward layer. I do this with the help of the SendARP function to retrieve the physical address of a client.

Now am facing an issue and i don't know what might be the problem here. Without the SendARP function i can reinject packet easily but once that portion of code is present the WinDivertSendEx packet cease to work.

SendARP function AFAIK doesn't change the diverted packet in any way. Please anyone know what is happening here and at best has a solution for me???

Edit:
To divert the packets i open two handles like this:
`HANDLE injectHandle = WinDivertOpen("false", WINDIVERT_LAYER_NETWORK, 0, 0); 
HANDLE handle = WinDivertOpen(filter.constData(), layer, priority, flag);`

Then i set the Queue Length & Time for both handles:
`WinDivertSetParam(injectHandle, WINDIVERT_PARAM_QUEUE_LEN, 8192) 
WinDivertSetParam(injectHandle, WINDIVERT_PARAM_QUEUE_TIME, 2048)
WinDivertSetParam(handle, WINDIVERT_PARAM_QUEUE_LEN, 8192) 
WinDivertSetParam(handle, WINDIVERT_PARAM_QUEUE_TIME, 2048)`

Is it possible win32 SendARP function is slow to retrieve the physical address which leads the packet to being discarded? That's the only possible problem i could think of because i am sure the code itself is fine

Thanks!

**Comment by basil00** [comment]
The usual way to get the MAC address is to use the `IfIdx` and the [IP Helper API](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366073(v=vs.85).aspx).  I am not familiar with the `SendARP` function, but if it sends a packet it might be diverted to your application leading to a deadlock.

**Comment by kelvinomolumo** [comment]
Oh it might be the very cause. Because to get the MAC address of a machine from the IP, SendARP needs to send some ARP packet. Wow. Now i need to detect these packets and whitelist it. I will give it a try and will post my findings. Thank you @basil00....

**Comment by kelvinomolumo** [comment]
OK i got it working sorry for delaying. WinDivert has no issue with SendARP. Works smootly. Thank you very much for your help. Am learning new things everyday about low level networking! Cheers
