### ISSUE TITLE
can i get the ethernet header?

### ISSUE THREAD

**Issue by Einsy** [basil00/Divert#83]
can i get the ethernet header?
I find that,I can get most is ip header,but i can not  get ethernet header? the filter_language

outbound, inbound  only effect for ip protocol？

which rule  can i get the ethernet frame?

  write  by einsy

**Comment by basil00** [comment]
No, currently WinDivert only supports the network layer (IP headers and above).  You can however filter by the interface (a.k.a. adapter) number (`ifIdx`),
