### ISSUE TITLE
Drop TCP Packet

### ISSUE THREAD

**Issue by Boudat** [basil00/Divert#84]
Hi,

I want to drop a specific tcp packet like this
`if (tcp.packet == myarraybyte)
{
continue; // continue to next while loop
}`
But the packet is not blocked. I just want to drop the packet. not the entire tcp connection.

Thanks

**Comment by TechnikEmpire** [comment]
@Boudat If only it were that simple. Are you looking for a specific payload? Because you need to supply a pointer to a pointer in order for WinDivert to set it to the actual packet payload. Plus you need to ensure you're accounting for byte ordering etc. You should really post stuff like this on programming help sites like that trashbin called stackoverflow, because I can assure you this is not a bug in WinDivert, and this is a bug ticket you've opened.

**Comment by Boudat** [comment]
Finding a specific payload is not the problem. I can't find any example to drop a tcp packet with windivert. Maybe providing an example/guide/tutorial to do this can improve windivert. Im opening an issue not a bug ticket.

**Comment by TechnikEmpire** [comment]
@Boudat Don't open in sniff mode and don't send the packet back out with the send function. There's an extraordinary amount of [documentation on the official site](https://reqrypt.org/windivert-doc-v1.2.html).

**Comment by Boudat** [comment]
```
while (checker)
	{
		
		if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
		{
		
			continue;
		}
		if (packetLen == 59)
		{
			for (int a = 0; a < packetLen; a++)
			{
				if (packet[a] == 0xFC && packet[a + 1] == 0xDD && packet[a + 2] == 0x1A)
				{
					continue;
					
				}
			}
		}
		
		WinDivertHelperCalcChecksums(packet, packetLen, NULL);
		if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
		{
		
			continue;
		}
		
	}
```
This isn't working. i wouldn't asked if this can be done just as like you said.
Drop mode will drop tcp connection entirely based on matched filter language. not specific packet.

**Comment by TechnikEmpire** [comment]
@Boudat If I can't compile your example code, then I can't help you debug it. Please post all of the code, and please stop being so combative in your language, I'm trying to help you. I have other things I can do with my time instead if that's a problem. By the way, have you compiled any of the example applications?

**Comment by Boudat** [comment]
```
// Windivert.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include "WinDivert.h"
#include <stdio.h>
#include <iostream>
#include <iomanip>
#include <thread>
#include <stdlib.h>
#include <conio.h>

using namespace std;


int __cdecl main(int argc, char **argv)
{
	HANDLE handle;          // WinDivert handle
	WINDIVERT_ADDRESS addr; // Packet address
	unsigned char packet[0xFFFF];    // Packet buffer
	unsigned char packetsend[0xFFFF];
	UINT packetLen;
	bool checker = true;
	unsigned char encrypteddata[0xFFFF];



	handle = WinDivertOpen("outbound and tcp.DstPort == 5000", WINDIVERT_LAYER_NETWORK, 0, 0);   // Open some filter
	if (handle == INVALID_HANDLE_VALUE)
	{
		if (GetLastError() == ERROR_INVALID_PARAMETER)
		{
			fprintf(stderr, "error: filter syntax error\n");
			exit(EXIT_FAILURE);
		}
		fprintf(stderr, "error: failed to open the WinDivert device (%d)\n",
			GetLastError());
		exit(EXIT_FAILURE);
	}
 

	// Main capture-modify-inject loop:
	while (checker)
	{
		
		if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
		{
		
			continue;
		}
		if (packetLen == 59)
		{
			for (int a = 0; a < packetLen; a++)
			{
				if (packet[a] == 0xFC && packet[a + 1] == 0xDD && packet[a + 2] == 0x1A)
				{
					continue;
					
				}
			}
		}
		
		WinDivertHelperCalcChecksums(packet, packetLen, NULL);
		if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
		{
		
			continue;
		}
		
	}
}
```
I have no problem manipulate send packet like this.
```
if (packet[a] == 0xFC && packet[a + 1] == 0xDD && packet[a + 2] == 0x1A)
				{
					packet[a] = 0x00;
				}
```
but when i want to drop the matched send packet with continue; to next loop. it's not blocked at all.

**Comment by TechnikEmpire** [comment]
@Boudat You're only continuing your inner most loop. You are not continuing the recv/send loop. See the [example about the continue keyword here](http://en.cppreference.com/w/cpp/language/continue).

Should be something like this:

```C++
bool sendThis = true;
if (packetLen == 59)
		{
			for (int a = 0; a < packetLen; a++)
			{
				if (packet[a] == 0xFC && packet[a + 1] == 0xDD && packet[a + 2] == 0x1A)
				{
					sendThis = false;
                                        // Break out of the for(i...) loop.
					break;
				}
			}
		}

if(sendThis == true)
{
               WinDivertHelperCalcChecksums(packet, packetLen, NULL);
		if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
		{
		
			continue;
		}
}
```

**Comment by TechnikEmpire** [comment]
@Boudat Also make sure you read my comments in my modified code example. There's other issues with the code that are going to 100% guaranteed crash your program.

**Comment by Boudat** [comment]
i've tried it like this.
```
while (checker)
	{
		
		if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
		{
		
			continue;
		}
		if (packetLen == 59)
		{
			for (int a = 0; a < packetLen; a++)
			{
				if (packet[a] == 0xFC && packet[a + 1] == 0xDD && packet[a + 2] == 0x1A)
				{
					goto drop;
					
				}
			}
		}
		
		WinDivertHelperCalcChecksums(packet, packetLen, NULL);
		if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
		{
		
			continue;
		}
		drop:
                  continue;

	}
```
if i block whole send packet like this
```
while (checker)
	{
		
		if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packetLen))
		{
		
			continue;
		}
		continue;
		WinDivertHelperCalcChecksums(packet, packetLen, NULL);
		if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
		{
		
			continue;
		}
		
	}
```
it's just delayed. not blocked, and wireshark shows something like this
![image](https://cloud.githubusercontent.com/assets/28234188/25591574/b7898a4e-2ee7-11e7-982e-1dc00a298cdb.png)
It's like keep retrying to send if its blocked

**Comment by Boudat** [comment]
I tried just like your code
```
bool sendThis = true;
if (packetLen == 59)
{
	for (int a = 0; a < packetLen; a++)
	{ 
                // Note also that you're not doing proper bounds checks here. You're definitely
                // going to go outside of the bounds with [a + 1] and [a + 2]. You should change
                // your for loop to subtract two from the packet length so you're sure not to
                // call an index out of bounds.
		if (packet[a] == 0xFC && packet[a + 1] == 0xDD && packet[a + 2] == 0x1A)
		{
			sendThis = false;
                        // Break out of the for(int a = 0; ...) loop.
                        cout << "trigger" << endl;
		        cout << packetLen << endl;
			break;
		}
	}
}

if(sendThis == true)
{
	WinDivertHelperCalcChecksums(packet, packetLen, NULL);
	if (!WinDivertSend(handle, packet, packetLen, &addr, NULL))
	{
	
		continue;
	}
}
```
and the output is like this
![image](https://cloud.githubusercontent.com/assets/28234188/25592445/69facd5c-2eeb-11e7-85a1-642370ee7f3e.png)

**Comment by basil00** [comment]
You can't just drop TCP packets anyway.  The whole purpose of TCP is to provide a *reliable* connection.  If a packet is dropped, the sender will detect this (through missing `ACK`s), and the endpoint will attempt to send the packet again and again.  The process will repeat until the packet is successfully transmitted or the connection drops.  Meanwhile, any data after the dropped packet will be stalled.

If you want to edit contents of a TCP stream, the correct approach is use WinDivert to redirect packets to a local proxy server, and do the editing there.  See [streamdump](https://github.com/basil00/Divert/blob/master/examples/streamdump/streamdump.c) for an example of how to do such redirection.
