### ISSUE TITLE
Type: question. Is packet rejection documented by Microsoft?

### ISSUE THREAD

**Issue by satnatantas** [basil00/Divert#86]
I am currently trying to generate network traffic for network testing. I am trying to inject large packets generated with libtins on Vista SP2.

And I never got anything except error 87 even though examples work just fine. This is bugging me.

For example:
`Tins::EthernetII pkt=Tins::EthernetII() / Tins::IP(Tins::IPv4Address(QHAdst.toIPv4Address()),Tins::IPv4Address(QHAsrc.toIPv4Address()))  /  Tins::UDP(6666,6666)  / Tins::RawPDU((uint8_t*)(void*)sample.data(),sizeof(sample));` - this puts raw data into UDP into IP.

I tried:
- sending sample at TCP level
- sending sample at UDP level
- sending sample to own NIC IP address
- generating packet with my own, calculating checksum with WinDivert and injecting it

It all fails. After studying sources I came to conclusion that the only source of this error can be WinAPI network injection call (namely `FwpsInjectNetworkSendAsync0`) but I could not find rejection criteria EXCEPT that raw sockets were severly cut since WIndows XP SP2 (seems to be unrelated): https://msdn.microsoft.com/en-us/library/windows/desktop/ms740548%28v=vs.85%29.aspx

Any tips?

**Comment by TechnikEmpire** [comment]
But you said you already came to a conclusion, so why are you opening a bug ticket and spamming dozens of watchers?

Unfortunately my crystal ball is having a hard time focusing on your computer screen, so I can't see the source code that you've obviously written incorrectly in order to correct you. I have jim standing in the roof with rabbit ears, but it's still too fuzzy.

Someone once told me when I first saw a computer with an error code that I should look up what the code means with the guy who invented the error code. His name was Basic Logic but he was probably an idiot anyway. If I follow his advice though, I see that error 87 from windows means that YOU have supplied an incorrect parameter to a function.

I've only written a full fledge intercepting transparent filtering proxy with windivert though so I probably don't have a clue what I'm talking about.

**Comment by satnatantas** [comment]
Here are my reasons for doing what I did:
- there is no big red flashing placard saying "do not post anything directly useful for developers here" 
- I found at least one similar ticket here (the reason for packet discarding was different)
- it might be generally interesting for other users considering that I did not find any reasonable description of what I am asking about on MSDN or whereever
- Basil commented that ticket (with same error number) and said that packet gets rejected by OS
- I have already studied sources of both dll/windivert.c and sys/windivert.c and there are indeed much more reasons to return that error number than just incorrect parameter (to what? WindivertSend?) (in contrary to what you say)
- any FwpsInjectNetworkSendAsync0 status/error gets passed to user of WinDivert

There is a whole plenty of ways for me to be wrong.

**Comment by TechnikEmpire** [comment]
I still don't see any source code for your issue. No one can help you. Showing up on a bug ticket thread with no minimal example to reproduce the issue is like a kid pulling the fire alarm at your hotel. You have no idea if it's legit and there's a fire you need to put out, or if it's a prank and someone needs a scolding.

It's a complete waste of time. Granted, this post caught me on a bad day but seriously dude I'm annoyed at the endless army of "programmers" who don't understand the basic process to solve a problem. Until there's some source code, this is the summary of your post:

 - I found a bug
 - I'm not telling you what it is
 - I'm not telling you how I found it
 - Trust me that I'm right cause I'm an expert and I've studied all the source code already

This issue should be closed

**Comment by TechnikEmpire** [comment]
I'm gonna go out on a limb and guess that your program using windivert is not running as an administrator. That's the best shot in the dark I can give an expert who refuses to show their code.

**Comment by satnatantas** [comment]
Code is copied from sample as much as possible. Oh yes I did launch it as admin, if I did not knew it samples would not work either.

Minimal code is:

```
	HANDLE WDVHdl;
	WDVHdl = WinDivertOpen("false", WINDIVERT_LAYER_NETWORK, priority, 0);
	if (WDVHdl == INVALID_HANDLE_VALUE){
		std::cerr<<"error: failed to open the WinDivert device "<<GetLastError()<<"\n";
		std::cerr<<"networkTest failed to access WinDivert, may be a privilege probkem, check out https://reqrypt.org/windivert-doc.html"<<std::endl;
		{
			running=false;
			return;
		}
	}
	auto sample = std::array<uint8_t, 65000>{0}; //whatever, tried small packets as well 
	Tins::EthernetII pkt=Tins::EthernetII() / Tins::IP(Tins::IPv4Address(QHAdst.toIPv4Address()/*NIC address here*/),Tins::IPv4Address(QHAsrc.toIPv4Address()/*any other valid address here, NIC's or other machine's*/)) / Tins::UDP(6666,6666) / Tins::RawPDU((uint8_t*)(void*)sample.data(),sizeof(sample));
	auto sample_packet=pkt.serialize();
	WINDIVERT_ADDRESS recv_addr;
	recv_addr.Direction=WINDIVERT_DIRECTION_OUTBOUND;
	recv_addr.IfIdx=interfaceIndex;
	recv_addr.SubIfIdx=0; //tried different values

		if (!WinDivertSend(WDVHdl, sample_packet.data(), sample_packet.size(),
						   &recv_addr, NULL))
			std::cerr<<"warning: failed to send sample "<<GetLastError()<<"\n";

```

**Comment by TechnikEmpire** [comment]
Neat. I pressed the "compile" button and it didn't work.

**Comment by satnatantas** [comment]
I'll bake small console thing tomorrow.

**Comment by TechnikEmpire** [comment]
Is this code accurate? Does this library actually override arithmetic operators and turns them into some sort of crafting operators?

**Comment by satnatantas** [comment]
Yes.
http://libtins.github.io/tutorial/sending/

**Comment by TechnikEmpire** [comment]
That's an egregious design decision on their part. Here's what I'd suggest. Try calling the [WinDivertHelperParsePacket](https://reqrypt.org/windivert-doc.html#divert_helper_parse_packet) function on your crafted packet before sending to ensure that it's formatted as WinDivert would expect. If that proves that your crafted packet is valid, then I'd re-check your use/values of [WINDIVERT_ADDRESS](https://reqrypt.org/windivert-doc.html#divert_address).

**Comment by TechnikEmpire** [comment]
Can you verify that the checksums are being calculated within the `.serialize()` method. The documentation is unclear on this. It states that checksums will be calculated if you use the built in sender, it does not indicate that it is automatically calculated just by calling `serialize()`. 

A quick search of the source code doesn't show the checksum taking place within this method.

Inspect your checksums. A simpler way would be to force the packet through WinDivert's checksum calculation helper, [WinDivertHelperCalcChecksums](https://reqrypt.org/windivert-doc.html#divert_helper_calc_checksums).

**Comment by basil00** [comment]
> Tins::EthernetII pkt=Tins::EthernetII() / ...

This appears to construct a layer-2 packet with an Ethernet header.  WinDivert works at the network layer (layer-3), so such a packet would be rejected with error 87.  The first header must be IPv4 or IPv6, so either construct such a packet directly, or skip over the Ethernet header with (`sample_packet.data()+14`/`sample_packet.size()-14`).

**Comment by satnatantas** [comment]
Working it out,, will post simple example tomorrow.

**Comment by TechnikEmpire** [comment]
Oh weird look at that, it was an invalid parameter.

**Comment by satnatantas** [comment]
@TechnikEmpire invalid parameter OF WHAT?

**Comment by TechnikEmpire** [comment]
@satnatantas lol look I'm sorry for being a jerk. The packet you were supplying as a parameter was invalid/incorrect if I understand the author correctly. Props to you for handling my grouchiness so well. I did genuinely try to help near the end but all I could do was guess without knowing the other library and having no other info to go on.

**Comment by satnatantas** [comment]
@TechnikEmpire I am perfectly trained for internetz after few years. Packet is not a parameter, pointer to packet is parameter. If it does not point at packet, it is incorrect.

But well, since WinDivert goes along WinAPI weirdness in this case I can only blame myself for not being familiar with it. But well, I did ask about rejection criteria in the first post.
