### ISSUE TITLE
build

### ISSUE THREAD

**Issue by MortezaMoFa** [basil00/Divert#88]
I'm trying to use windivert and go step by step in accordance with its README but can finished them and having trouble with **build** command, Error in below:

```
C:\Divert>wddk-build.bat
A subdirectory or file install\WDDK\ already exists.
'build' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by basil00** [comment]
Are you building from a WDK 7.1.0 command line environment?

**Comment by MortezaMoFa** [comment]
I don't know. (I'm crying mod)

![image](https://user-images.githubusercontent.com/15952600/28766644-c06c463e-75e5-11e7-9e1e-4a033357c571.png)

**Comment by basil00** [comment]
No, that is VS2017.  You need to build with WDK 7.1.0.
