### ISSUE TITLE
Windivert dropping and Winpcap/Wireshark

### ISSUE THREAD

**Issue by AlexeiScherbakov** [basil00/Divert#89]
How I can configure Windivert to drop packets before they reach Winpcap driver?
I need a complex filtering rule to block some bad packets and see in Winpcap/Wireshark what is happened, but it seems that Windivert & Winpcap working in parallel mode

**Comment by basil00** [comment]
Windivert/Winpcap rely on different Windows subsystems (Windivert is a WFP driver and Winpcap is a NDIS protocol driver), meaning that it is not possible to change the ordering.  Outbound packets will always visit WinDivert first, and inbound packets will always visit Winpcap first.
