### ISSUE TITLE
Divert  for name resolver

### ISSUE THREAD

**Issue by topeawolwo** [basil00/Divert#95]
**i know that Divert can  be used  for packet modification and redirection. I want to achieve DNS name resolution some thing similar to   C-ARES (https://c-ares.haxx.se/).....going through documentation i found our that Divert cannot be used  for such, if it can do correct me.

Secondly,  can DIVERT be extended with other  libraries .. i mean can i attach Divert with C-ARES to achieve name resolution, if it can what files within the folders are necessary. looking forward to getting the answers**

**Comment by TechnikEmpire** [comment]
@topeawolwo Did you not read the author's response the first time you asked this question?

https://github.com/basil00/Divert/issues/94

Look at his other project that he referenced and study the source code.

https://github.com/basil00/TorWall/blob/master/redirect.c#L316
https://github.com/basil00/TorWall/blob/master/redirect.c#L646

**Comment by topeawolwo** [comment]
**@TechnikEmpire      thanks for the response but,

from https://www.torproject.org/docs/faq#DoesntWork

"Tor is a program you can run on your computer that helps keep you safe on the Internet. It protects you by bouncing your communications around a distributed network of relays run by volunteers all around the world: it prevents somebody watching your Internet connection from learning what sites you visit, and it prevents the sites you visit from learning your physical location."

Am satisfied  using using Divert as  a Kernel driver, i want to achieve DNS resolution. You directed me to TorWall (https://github.com/basil00/TorWall/blob/master/redirect.c#L316), it cant achieve DNS RESOLUTION.


Do reply**

**Comment by TechnikEmpire** [comment]
@topeawolwo I'm really confused  now. Why are we talking about Tor, DNS, referring to Tor as to why DNS won't work. Why are we talking about DNS resolution? Can you plainly state your objectives please?

Are you trying to intercept every DNS query and redirect it to your own server? Are you trying to block some DNS queries from being fulfilled? Are you trying to capture all DNS queries and send them off into space for the aliens to answer one day? 

I have no idea what you're asking. Can you just plainly state your objectives?

**Comment by TechnikEmpire** [comment]
I mean no disrespect I just mean if you can spell out what you are trying to achieve, people seeing your question will be able to help more.

**Comment by basil00** [comment]
> if it can what files within the folders are necessary.

That is up to you to figure out.  We have already given you several hints.
