### ISSUE TITLE
consuming  Windivert.dll

### ISSUE THREAD

**Issue by winnieaj** [basil00/Divert#96]
My  project design
(1) THE WINDOWS SERVICE TALKS TO THE DLL (consumes the dll, use the dll, running in the background), the windows is installed by a setup installer, implemented in C#.
(2)THE DLL TALKS TO THE DRIVER 
(3) THE DRIVER DOES THE FILTERING

I built  divert in Visual Studio 2015, it gave me WinDivert.dll. I want to  consume the dll in a windows service (C#).....I want to know how do i call this WinDivert.dll in the C# windows service, I DONT KNOW HOW TO...do i need to break the WinDivert.dll down ...and what function in DIVERT is available for windows service usage

**Comment by TechnikEmpire** [comment]
@winnieaj You can use all of WinDivert from a Windows service, I'm doing this myself. WinDivert is a native library so to use it from C#/.NET you need either a Pinvoke wrapper or a managed C++/CLI wrapper. I have written both but they are of course unofficial.

https://github.com/TechnikEmpire/Divert.Net

https://github.com/TechnikEmpire/DivertPInvoke

I'd recommend just going with the DivertPInvoke and use unsafe code. The Divert.Net project requires some setup described in the Wiki that is a bit of a pain. Just use unsafe code, use topshelf and use Pinvoke version in your service and you'll see it works just fine.

**Comment by basil00** [comment]
I don't know anything about C#, so please refer to @TechnikEmpire's answer.
