### ISSUE TITLE
Crash on 32 bit Windows 7 with WDDK driver version 

### ISSUE THREAD

**Issue by ValdikSS** [basil00/Divert#97]
WinDivert 1.1.8 32 bit WDDK version crashes **the application** on Windows 7 32 bit almost instantly. I suppose this is due some bug in a dll, not the driver.

MinGW compiled DLL with WDDK compiled driver works correctly, as well, as MinGW DLL + MinGW SYS.

**Comment by ValdikSS** [comment]
Same problem with WinDivert 1.2.0 rc.

**Comment by basil00** [comment]
Thanks for the report.  Do you know the crash location (e.g. which function?).  If MinGW works then probably some undefined behavior somewhere.

**Comment by ValdikSS** [comment]
I'll install debugger and try to debug it today.

**Comment by ValdikSS** [comment]
If you have free time, you can get latest GoodbyeDPI and replace dll and sys with 32 bit wddk versions.

**Comment by basil00** [comment]
I don't have a 32bit version of Windows ready.  When I try on 64bit Windows there is no crash.
