### ISSUE TITLE
Low Level Question

### ISSUE THREAD

**Issue by chawkh** [basil00/Divert#99]
Hello,  
first of all, a really cool project. 
I feel ashamed, but got to ask for a small example in creating a packet and injecting in with windivertsend. 
For a start i tried to copy an existing packet with all bytes and windivert address and handle. Then in another thread I calculate checksum and pass it to windivertsend. It fails to inject. I didnt care about seqnum and such, maybe thats the problem. But I wouldnt have thought to get an injectionproblem. It would be great to see an easy example or to get some hint. Thank you.

**Comment by TechnikEmpire** [comment]
@chawkh There are sample programs.

https://reqrypt.org/windivert-doc-v1.2.html#samples

https://reqrypt.org/samples/passthru.html
https://reqrypt.org/samples/netfilter.html
https://reqrypt.org/samples/webfilter.html

etc

**Comment by TechnikEmpire** [comment]
Oh and I almost forgot:

https://github.com/basil00/Divert/tree/master/examples

**Comment by chawkh** [comment]
Thank you very much. But I already checked those. But a packetcreation process I couldnt find. Also I read all other issues here and searched the web. I saw already a few helpful posts from you in other issues. But cant find a solution for my problem. 
I want to create a packet. But right now even to copy it to another thread doesnt work. I sniff send and recv from an application and need to send completly new packets to the output and to the server. Sadly I am new to connection stuff and this project was very helpful to sniff everything. But yeah now I am stucked. In my Project I used the sniffflagg in WinDivertOpen() for the input way. I set default for the output and I divert the packets and reinject them. That does work. Now I want to send to the same path from another thread. I saw that all tcp-connectioninfo seems to be parsed in the first 40-52 bytes. So I thought to copy such a packet and send it again. Maybe I need to modify SeqNum and Acknum and such to get the server accept my packet, but I cant understand why I cant inject it to WinDivert send. 
Maybe I need to send to a proxy like in netdump and set up a socket connection to the server. But WinDivert looked like it might not be needed. 
This noobish way I copy the packet in the send_sniffthread:
if(packet_len==40&&tcp_header->Ack==1)
{
	memcpy(s_packet,packet,40);
	copy_handle=s__handle; //copy_handle and s__addr and s_packet are defind global
	s__addr=addr;
	printf("captured packet:%d\n",copy_handle);
}
then I got a sendit() func just to send the copied packet:
int sendit()
{	
    PWINDIVERT_IPHDR ip_header;
    PWINDIVERT_IPV6HDR ipv6_header;
    PWINDIVERT_ICMPHDR icmp_header;
    PWINDIVERT_ICMPV6HDR icmpv6_header;
    PWINDIVERT_TCPHDR tcp_header;
    PWINDIVERT_UDPHDR udp_header;
	
	WinDivertHelperParsePacket(s_packet, s__packet_len, &ip_header,
            &ipv6_header, &icmp_header, &icmpv6_header, &tcp_header,
            &udp_header, NULL, NULL);
        SetConsoleTextAttribute(console, FOREGROUND_RED);
        printf("Packet [Direction=%u IfIdx=%u SubIfIdx=%u]\n",
            s__addr.Direction, s__addr.IfIdx, s__addr.SubIfIdx);
// s_addr output seems ok
 if (ip_header != NULL)
{
//sadly this seems NULL and might be cause of my problem
//Is there more to the packets then its bytes? It seemes I am missing smth, I cant catch. In the bytes I see all Tcp info but I WinDivertHelperParsePacket() seems to NULL
}
WinDivertHelperCalcChecksums(s_packet,s__packet_len,0);
        if (!WinDivertSendEx(copy_handle , s_packet, s__packet_len,0, &s__addr, NULL,0))
        {
            fprintf(stderr, "warning: failed to reinject packet (%d)\n",
                GetLastError()); //error shown was 87 before but now only 122
        }
return 0
}

**Comment by TechnikEmpire** [comment]
Hmm, well I can't debug your code at the moment but just know that the error codes returned here are standard windows errors and they are extremely helpful.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

The two errors you're seeing here are:

`ERROR_INSUFFICIENT_BUFFER == 122`
`ERROR_INVALID_PARAMETER == 87`

**Comment by TechnikEmpire** [comment]
Also, not all packets are ipv4 packets, so obviously sometimes the pointer-to-pointer for the IPV4 header will be null.

**Comment by chawkh** [comment]
Great, maybe size of 40 for s_packet is too small.
But in generell my concept should be possible? 
That is enough to keep me working. If you by any chance could post a sample of an easy selfmade and correctly injected packet, it would help alot. I am asking here for much and in reallife I would compensate you with a dinner or present-basket.

**Comment by TechnikEmpire** [comment]
I do all my "packet crafting" with WinDivert by simply diverting traffic through a proxy and modifying the content dynamically. I don't have the stomach to get all low level manually crafting packets, I let the existing network stack handle all that stuff and just modify payloads by using the proxy. I believe the author's example, the webfilter, does some manual packet crafting. Have a peek there.

**Comment by chawkh** [comment]
if(packet_len==40&&tcp_header->Ack==1)
				{
					memcpy(s_packet,packet,40);
					copy_handle=s__handle;
					//s__addr=addr;
					printf("captured packet:%d\n",copy_handle);
					WinDivertRecvEx(handle, packet, sizeof(packet), 0,&s__addr, &s__packet_len,0);							
				}
Passing addr to s__addr seems to be working with WinDivertRecv. That way its injectable. Thank you so much for your help. Also webfilter seems more helpful, now that I got some experience.

**Comment by basil00** [comment]
> It would be great to see an easy example or to get some hint.

This is really what the example programs are meant for.

Anyway, it seems this issue is resolved.
